### PR TITLE
TEZ-4463: Upgrade jquery-ui to 1.13.2 due to CVE issues

### PR DESCRIPTION
**Pull request by maheshrajus**
Upgrade jquery-ui to 1.13.2 due to CVE issues
Bower not supporting jquery 1.13.2 version so moving required files into tez-ui.

### CODE REVIEW

**Comment by tez-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| +0 :ok: |  reexec  |   1m  1s |  Docker mode activated.  |
||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  0s |  No case conflicting files found.  |
| +1 :green_heart: |  @author  |   0m  1s |  The patch does not contain any @author tags.  |
| -1 :x: |  test4tests  |   0m  0s |  The patch doesn't appear to include any new or modified tests. Please justify why no new tests are needed for this patch. Also please list what manual steps were performed to verify this patch.  |
||| _ master Compile Tests _ |
| +1 :green_heart: |  mvninstall  |  17m 10s |  master passed  |
| +1 :green_heart: |  javadoc  |   0m 38s |  master passed with JDK Ubuntu-11.0.17+8-post-Ubuntu-1ubuntu220.04  |
| +1 :green_heart: |  javadoc  |   0m 18s |  master passed with JDK Private Build-1.8.0_352-8u352-ga-1~20.04-b08  |
||| _ Patch Compile Tests _ |
| -1 :x: |  mvninstall  |   0m 35s |  tez-ui in the patch failed.  |
| +1 :green_heart: |  whitespace  |   0m  0s |  The patch has no whitespace issues.  |
| +1 :green_heart: |  javadoc  |   0m 16s |  the patch passed with JDK Ubuntu-11.0.17+8-post-Ubuntu-1ubuntu220.04  |
| +1 :green_heart: |  javadoc  |   0m 18s |  the patch passed with JDK Private Build-1.8.0_352-8u352-ga-1~20.04-b08  |
||| _ Other Tests _ |
| -1 :x: |  unit  |   0m 20s |  tez-ui in the patch failed.  |
| +1 :green_heart: |  asflicense  |   0m 23s |  The patch does not generate ASF License warnings.  |
|  |   |  21m 45s |   |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.41 ServerAPI=1.41 base: https://ci-hadoop.apache.org/job/tez-multibranch/job/PR-259/1/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/tez/pull/259 |
| JIRA Issue | TEZ-4463 |
| Optional Tests | dupname asflicense javac javadoc unit |
| uname | Linux 719bfb20fae7 4.15.0-200-generic #211-Ubuntu SMP Thu Nov 24 18:16:04 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | personality/tez.sh |
| git revision | master / 34d681007 |
| Default Java | Private Build-1.8.0_352-8u352-ga-1~20.04-b08 |
| Multi-JDK versions | /usr/lib/jvm/java-11-openjdk-amd64:Ubuntu-11.0.17+8-post-Ubuntu-1ubuntu220.04 /usr/lib/jvm/java-8-openjdk-amd64:Private Build-1.8.0_352-8u352-ga-1~20.04-b08 |
| mvninstall | https://ci-hadoop.apache.org/job/tez-multibranch/job/PR-259/1/artifact/out/patch-mvninstall-tez-ui.txt |
| unit | https://ci-hadoop.apache.org/job/tez-multibranch/job/PR-259/1/artifact/out/patch-unit-tez-ui.txt |
|  Test Results | https://ci-hadoop.apache.org/job/tez-multibranch/job/PR-259/1/testReport/ |
| Max. process+thread count | 72 (vs. ulimit of 5500) |
| modules | C: tez-ui U: tez-ui |
| Console output | https://ci-hadoop.apache.org/job/tez-multibranch/job/PR-259/1/console |
| versions | git=2.25.1 maven=3.6.3 |
| Powered by | Apache Yetus 0.12.0 https://yetus.apache.org |


This message was automatically generated.

**Comment by tez-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| +0 :ok: |  reexec  |  36m 52s |  Docker mode activated.  |
||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  0s |  No case conflicting files found.  |
| +1 :green_heart: |  @author  |   0m  0s |  The patch does not contain any @author tags.  |
| -1 :x: |  test4tests  |   0m  0s |  The patch doesn't appear to include any new or modified tests. Please justify why no new tests are needed for this patch. Also please list what manual steps were performed to verify this patch.  |
||| _ master Compile Tests _ |
| +1 :green_heart: |  mvninstall  |  15m 48s |  master passed  |
| +1 :green_heart: |  javadoc  |   0m 39s |  master passed with JDK Ubuntu-11.0.17+8-post-Ubuntu-1ubuntu220.04  |
| +1 :green_heart: |  javadoc  |   0m 17s |  master passed with JDK Private Build-1.8.0_352-8u352-ga-1~20.04-b08  |
||| _ Patch Compile Tests _ |
| -1 :x: |  mvninstall  |   0m 34s |  tez-ui in the patch failed.  |
| +1 :green_heart: |  whitespace  |   0m  0s |  The patch has no whitespace issues.  |
| +1 :green_heart: |  javadoc  |   0m 17s |  the patch passed with JDK Ubuntu-11.0.17+8-post-Ubuntu-1ubuntu220.04  |
| +1 :green_heart: |  javadoc  |   0m 15s |  the patch passed with JDK Private Build-1.8.0_352-8u352-ga-1~20.04-b08  |
||| _ Other Tests _ |
| -1 :x: |  unit  |   0m 19s |  tez-ui in the patch failed.  |
| +1 :green_heart: |  asflicense  |   0m 23s |  The patch does not generate ASF License warnings.  |
|  |   |  56m 10s |   |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.41 ServerAPI=1.41 base: https://ci-hadoop.apache.org/job/tez-multibranch/job/PR-259/2/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/tez/pull/259 |
| JIRA Issue | TEZ-4463 |
| Optional Tests | dupname asflicense javac javadoc unit |
| uname | Linux 7ae86460ca4d 4.15.0-200-generic #211-Ubuntu SMP Thu Nov 24 18:16:04 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | personality/tez.sh |
| git revision | master / 39e5a8e71 |
| Default Java | Private Build-1.8.0_352-8u352-ga-1~20.04-b08 |
| Multi-JDK versions | /usr/lib/jvm/java-11-openjdk-amd64:Ubuntu-11.0.17+8-post-Ubuntu-1ubuntu220.04 /usr/lib/jvm/java-8-openjdk-amd64:Private Build-1.8.0_352-8u352-ga-1~20.04-b08 |
| mvninstall | https://ci-hadoop.apache.org/job/tez-multibranch/job/PR-259/2/artifact/out/patch-mvninstall-tez-ui.txt |
| unit | https://ci-hadoop.apache.org/job/tez-multibranch/job/PR-259/2/artifact/out/patch-unit-tez-ui.txt |
|  Test Results | https://ci-hadoop.apache.org/job/tez-multibranch/job/PR-259/2/testReport/ |
| Max. process+thread count | 72 (vs. ulimit of 5500) |
| modules | C: tez-ui U: tez-ui |
| Console output | https://ci-hadoop.apache.org/job/tez-multibranch/job/PR-259/2/console |
| versions | git=2.25.1 maven=3.6.3 |
| Powered by | Apache Yetus 0.12.0 https://yetus.apache.org |


This message was automatically generated.

**Comment by tez-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| +0 :ok: |  reexec  |   0m  0s |  Docker mode activated.  |
| -1 :x: |  docker  |   0m  2s |  Docker failed to build yetus/tez:c386865e7.  |


| Subsystem | Report/Notes |
|----------:|:-------------|
| GITHUB PR | https://github.com/apache/tez/pull/259 |
| JIRA Issue | TEZ-4463 |
| Console output | https://ci-hadoop.apache.org/job/tez-multibranch/job/PR-259/3/console |
| versions | git=2.17.1 |
| Powered by | Apache Yetus 0.12.0 https://yetus.apache.org |


This message was automatically generated.

**Comment by abstractdog** [comment]
@maheshrajus: can you please check why the tez-ui module fails?

**Comment by maheshrajus** [comment]
@abstractdog tez-ui module latest version 1.13.0 dependency failed to download with bower. Some how we need to pull this dependency with npm or other. I need to check this. any pointers/suggestions can help.

[INFO] bower jquery-ui#1.13.0                ENORESTARGET No version found that was able to satisfy 1.13.0

**Comment by maheshrajus** [comment]
> @abstractdog tez-ui module latest version 1.13.0 dependency failed to download with bower. Some how we need to pull this dependency with npm or other. I need to check this. any pointers/suggestions can help.
> 
> [INFO] bower jquery-ui#1.13.0 ENORESTARGET No version found that was able to satisfy 1.13.0

@abstractdog tez-ui module latest version 1.13.0 dependency failed to download with bower. Some how we need to pull this dependency with npm or other. I need to check this. any pointers/suggestions can help.

[INFO] bower jquery-ui#1.13.0 ENORESTARGET No version found that was able to satisfy 1.13.0

**Comment by maheshrajus** [comment]
> @abstractdog tez-ui module latest version 1.13.0 dependency failed to download with bower. Some how we need to pull this dependency with npm or other. I need to check this. any pointers/suggestions can help.
> 
> [INFO] bower jquery-ui#1.13.0 ENORESTARGET No version found that was able to satisfy 1.13.0



>

**Comment by tez-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| +0 :ok: |  reexec  |  24m 49s |  Docker mode activated.  |
||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  0s |  No case conflicting files found.  |
| +1 :green_heart: |  @author  |   0m  0s |  The patch does not contain any @author tags.  |
| -1 :x: |  test4tests  |   0m  0s |  The patch doesn't appear to include any new or modified tests. Please justify why no new tests are needed for this patch. Also please list what manual steps were performed to verify this patch.  |
||| _ master Compile Tests _ |
| +1 :green_heart: |  mvninstall  |  15m 35s |  master passed  |
| +1 :green_heart: |  javadoc  |   0m 38s |  master passed with JDK Ubuntu-11.0.18+10-post-Ubuntu-0ubuntu122.04  |
| +1 :green_heart: |  javadoc  |   0m 17s |  master passed with JDK Private Build-1.8.0_362-8u362-ga-0ubuntu1~22.04-b09  |
||| _ Patch Compile Tests _ |
| -1 :x: |  mvninstall  |   0m 32s |  tez-ui in the patch failed.  |
| +1 :green_heart: |  whitespace  |   0m  0s |  The patch has no whitespace issues.  |
| +1 :green_heart: |  javadoc  |   0m 15s |  the patch passed with JDK Ubuntu-11.0.18+10-post-Ubuntu-0ubuntu122.04  |
| +1 :green_heart: |  javadoc  |   0m 15s |  the patch passed with JDK Private Build-1.8.0_362-8u362-ga-0ubuntu1~22.04-b09  |
||| _ Other Tests _ |
| -1 :x: |  unit  |   0m 18s |  tez-ui in the patch failed.  |
| +1 :green_heart: |  asflicense  |   0m 22s |  The patch does not generate ASF License warnings.  |
|  |   |  43m 46s |   |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.42 ServerAPI=1.42 base: https://ci-hadoop.apache.org/job/tez-multibranch/job/PR-259/4/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/tez/pull/259 |
| JIRA Issue | TEZ-4463 |
| Optional Tests | dupname asflicense javac javadoc unit |
| uname | Linux 3508c09ba8db 4.15.0-206-generic #217-Ubuntu SMP Fri Feb 3 19:10:13 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | personality/tez.sh |
| git revision | master / 25a953677 |
| Default Java | Private Build-1.8.0_362-8u362-ga-0ubuntu1~22.04-b09 |
| Multi-JDK versions | /usr/lib/jvm/java-11-openjdk-amd64:Ubuntu-11.0.18+10-post-Ubuntu-0ubuntu122.04 /usr/lib/jvm/java-8-openjdk-amd64:Private Build-1.8.0_362-8u362-ga-0ubuntu1~22.04-b09 |
| mvninstall | https://ci-hadoop.apache.org/job/tez-multibranch/job/PR-259/4/artifact/out/patch-mvninstall-tez-ui.txt |
| unit | https://ci-hadoop.apache.org/job/tez-multibranch/job/PR-259/4/artifact/out/patch-unit-tez-ui.txt |
|  Test Results | https://ci-hadoop.apache.org/job/tez-multibranch/job/PR-259/4/testReport/ |
| Max. process+thread count | 72 (vs. ulimit of 5500) |
| modules | C: tez-ui U: tez-ui |
| Console output | https://ci-hadoop.apache.org/job/tez-multibranch/job/PR-259/4/console |
| versions | git=2.34.1 maven=3.6.3 |
| Powered by | Apache Yetus 0.12.0 https://yetus.apache.org |


This message was automatically generated.

**Comment by tez-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| +0 :ok: |  reexec  |  27m 48s |  Docker mode activated.  |
||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  0s |  No case conflicting files found.  |
| +1 :green_heart: |  @author  |   0m  0s |  The patch does not contain any @author tags.  |
| -1 :x: |  test4tests  |   0m  0s |  The patch doesn't appear to include any new or modified tests. Please justify why no new tests are needed for this patch. Also please list what manual steps were performed to verify this patch.  |
||| _ master Compile Tests _ |
| +1 :green_heart: |  mvninstall  |  15m 21s |  master passed  |
| +1 :green_heart: |  javadoc  |   0m 36s |  master passed with JDK Ubuntu-11.0.18+10-post-Ubuntu-0ubuntu122.04  |
| +1 :green_heart: |  javadoc  |   0m 16s |  master passed with JDK Private Build-1.8.0_362-8u362-ga-0ubuntu1~22.04-b09  |
||| _ Patch Compile Tests _ |
| -1 :x: |  mvninstall  |   0m 38s |  tez-ui in the patch failed.  |
| +1 :green_heart: |  jshint  |  58m 59s |  There were no new jshint issues.  |
| +1 :green_heart: |  whitespace  |   0m  0s |  The patch has no whitespace issues.  |
| +1 :green_heart: |  javadoc  |   0m 15s |  the patch passed with JDK Ubuntu-11.0.18+10-post-Ubuntu-0ubuntu122.04  |
| +1 :green_heart: |  javadoc  |   0m 16s |  the patch passed with JDK Private Build-1.8.0_362-8u362-ga-0ubuntu1~22.04-b09  |
||| _ Other Tests _ |
| -1 :x: |  unit  |   0m 22s |  tez-ui in the patch failed.  |
| +1 :green_heart: |  asflicense  |   0m 24s |  The patch does not generate ASF License warnings.  |
|  |   | 105m 41s |   |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.42 ServerAPI=1.42 base: https://ci-hadoop.apache.org/job/tez-multibranch/job/PR-259/5/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/tez/pull/259 |
| JIRA Issue | TEZ-4463 |
| Optional Tests | dupname asflicense javac javadoc unit jshint |
| uname | Linux 338b43344820 4.15.0-206-generic #217-Ubuntu SMP Fri Feb 3 19:10:13 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | personality/tez.sh |
| git revision | master / 25a953677 |
| Default Java | Private Build-1.8.0_362-8u362-ga-0ubuntu1~22.04-b09 |
| Multi-JDK versions | /usr/lib/jvm/java-11-openjdk-amd64:Ubuntu-11.0.18+10-post-Ubuntu-0ubuntu122.04 /usr/lib/jvm/java-8-openjdk-amd64:Private Build-1.8.0_362-8u362-ga-0ubuntu1~22.04-b09 |
| mvninstall | https://ci-hadoop.apache.org/job/tez-multibranch/job/PR-259/5/artifact/out/patch-mvninstall-tez-ui.txt |
| unit | https://ci-hadoop.apache.org/job/tez-multibranch/job/PR-259/5/artifact/out/patch-unit-tez-ui.txt |
|  Test Results | https://ci-hadoop.apache.org/job/tez-multibranch/job/PR-259/5/testReport/ |
| Max. process+thread count | 72 (vs. ulimit of 5500) |
| modules | C: tez-ui U: tez-ui |
| Console output | https://ci-hadoop.apache.org/job/tez-multibranch/job/PR-259/5/console |
| versions | git=2.34.1 maven=3.6.3 jshint=2.12.0 |
| Powered by | Apache Yetus 0.12.0 https://yetus.apache.org |


This message was automatically generated.

**Comment by maheshrajus** [comment]
for 1.13.0+jquery-ui version bower not supporting dependency. So changing bower to npm dependency way is complex and changes will be more.

**Comment by abstractdog** [comment]
why is this PR closed? I believe we still need to address CVE-s, even if collecting dependencies from different sources might be challenging
I can see the latest patchset tries to address this question, didn't it work? can you take a look at that @sreenaths ?

**Pull request closed without merging**
