### PR TITLE
TEZ-4568: ProfileServlet: add html to output formats and prepare for profiler 3.0

### PR DESCRIPTION
**Pull request by abstractdog**
This PR is for fixing the same problems as mentioned and tested in [HIVE-28305](https://issues.apache.org/jira/browse/HIVE-28305)
please look at that PR for details:
https://github.com/apache/hive/pull/5281

### CODE REVIEW

**Comment by tez-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| +0 :ok: |  reexec  |  13m 42s |  Docker mode activated.  |
||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  0s |  No case conflicting files found.  |
| +1 :green_heart: |  @author  |   0m  0s |  The patch does not contain any @author tags.  |
| -1 :x: |  test4tests  |   0m  0s |  The patch doesn't appear to include any new or modified tests. Please justify why no new tests are needed for this patch. Also please list what manual steps were performed to verify this patch.  |
||| _ master Compile Tests _ |
| +1 :green_heart: |  mvninstall  |  13m 26s |  master passed  |
| +1 :green_heart: |  compile  |   0m 18s |  master passed with JDK Ubuntu-11.0.22+7-post-Ubuntu-0ubuntu222.04.1  |
| +1 :green_heart: |  compile  |   0m 17s |  master passed with JDK Private Build-1.8.0_402-8u402-ga-2ubuntu1~22.04-b06  |
| +1 :green_heart: |  checkstyle  |   1m 21s |  master passed  |
| +1 :green_heart: |  javadoc  |   0m 40s |  master passed with JDK Ubuntu-11.0.22+7-post-Ubuntu-0ubuntu222.04.1  |
| +1 :green_heart: |  javadoc  |   0m 15s |  master passed with JDK Private Build-1.8.0_402-8u402-ga-2ubuntu1~22.04-b06  |
| +0 :ok: |  spotbugs  |   1m 31s |  Used deprecated FindBugs config; considering switching to SpotBugs.  |
| +1 :green_heart: |  findbugs  |   1m 29s |  master passed  |
||| _ Patch Compile Tests _ |
| +1 :green_heart: |  mvninstall  |   0m 10s |  the patch passed  |
| +1 :green_heart: |  compile  |   0m  9s |  the patch passed with JDK Ubuntu-11.0.22+7-post-Ubuntu-0ubuntu222.04.1  |
| +1 :green_heart: |  javac  |   0m  9s |  the patch passed  |
| +1 :green_heart: |  compile  |   0m  9s |  the patch passed with JDK Private Build-1.8.0_402-8u402-ga-2ubuntu1~22.04-b06  |
| +1 :green_heart: |  javac  |   0m  9s |  the patch passed  |
| +1 :green_heart: |  checkstyle  |   0m  5s |  the patch passed  |
| +1 :green_heart: |  whitespace  |   0m  0s |  The patch has no whitespace issues.  |
| +1 :green_heart: |  javadoc  |   0m  7s |  the patch passed with JDK Ubuntu-11.0.22+7-post-Ubuntu-0ubuntu222.04.1  |
| +1 :green_heart: |  javadoc  |   0m  6s |  the patch passed with JDK Private Build-1.8.0_402-8u402-ga-2ubuntu1~22.04-b06  |
| +1 :green_heart: |  findbugs  |   0m 24s |  the patch passed  |
||| _ Other Tests _ |
| +1 :green_heart: |  unit  |   0m 32s |  tez-common in the patch passed.  |
| +1 :green_heart: |  asflicense  |   0m 17s |  The patch does not generate ASF License warnings.  |
|  |   |  34m  5s |   |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.44 ServerAPI=1.44 base: https://ci-hadoop.apache.org/job/tez-multibranch/job/PR-360/1/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/tez/pull/360 |
| JIRA Issue | TEZ-4568 |
| Optional Tests | dupname asflicense javac javadoc unit spotbugs findbugs checkstyle compile |
| uname | Linux 26c1bc81bee7 5.15.0-94-generic #104-Ubuntu SMP Tue Jan 9 15:25:40 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | personality/tez.sh |
| git revision | master / 38c5aaccd |
| Default Java | Private Build-1.8.0_402-8u402-ga-2ubuntu1~22.04-b06 |
| Multi-JDK versions | /usr/lib/jvm/java-11-openjdk-amd64:Ubuntu-11.0.22+7-post-Ubuntu-0ubuntu222.04.1 /usr/lib/jvm/java-8-openjdk-amd64:Private Build-1.8.0_402-8u402-ga-2ubuntu1~22.04-b06 |
|  Test Results | https://ci-hadoop.apache.org/job/tez-multibranch/job/PR-360/1/testReport/ |
| Max. process+thread count | 100 (vs. ulimit of 5500) |
| modules | C: tez-common U: tez-common |
| Console output | https://ci-hadoop.apache.org/job/tez-multibranch/job/PR-360/1/console |
| versions | git=2.34.1 maven=3.6.3 findbugs=3.0.1 |
| Powered by | Apache Yetus 0.12.0 https://yetus.apache.org |


This message was automatically generated.

**Comment by tez-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| +0 :ok: |  reexec  |   0m 10s |  Docker mode activated.  |
||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  0s |  No case conflicting files found.  |
| +1 :green_heart: |  @author  |   0m  0s |  The patch does not contain any @author tags.  |
| -1 :x: |  test4tests  |   0m  0s |  The patch doesn't appear to include any new or modified tests. Please justify why no new tests are needed for this patch. Also please list what manual steps were performed to verify this patch.  |
||| _ master Compile Tests _ |
| +1 :green_heart: |  mvninstall  |  29m 25s |  master passed  |
| +1 :green_heart: |  compile  |   0m 14s |  master passed with JDK Ubuntu-11.0.22+7-post-Ubuntu-0ubuntu222.04.1  |
| +1 :green_heart: |  compile  |   0m 12s |  master passed with JDK Private Build-1.8.0_402-8u402-ga-2ubuntu1~22.04-b06  |
| +1 :green_heart: |  checkstyle  |   1m 18s |  master passed  |
| +1 :green_heart: |  javadoc  |   0m 31s |  master passed with JDK Ubuntu-11.0.22+7-post-Ubuntu-0ubuntu222.04.1  |
| +1 :green_heart: |  javadoc  |   0m 13s |  master passed with JDK Private Build-1.8.0_402-8u402-ga-2ubuntu1~22.04-b06  |
| +0 :ok: |  spotbugs  |   1m 19s |  Used deprecated FindBugs config; considering switching to SpotBugs.  |
| +1 :green_heart: |  findbugs  |   1m 18s |  master passed  |
||| _ Patch Compile Tests _ |
| +1 :green_heart: |  mvninstall  |   0m 12s |  the patch passed  |
| +1 :green_heart: |  compile  |   0m 11s |  the patch passed with JDK Ubuntu-11.0.22+7-post-Ubuntu-0ubuntu222.04.1  |
| +1 :green_heart: |  javac  |   0m 11s |  the patch passed  |
| +1 :green_heart: |  compile  |   0m  9s |  the patch passed with JDK Private Build-1.8.0_402-8u402-ga-2ubuntu1~22.04-b06  |
| +1 :green_heart: |  javac  |   0m  9s |  the patch passed  |
| +1 :green_heart: |  checkstyle  |   0m  6s |  the patch passed  |
| +1 :green_heart: |  whitespace  |   0m  0s |  The patch has no whitespace issues.  |
| +1 :green_heart: |  javadoc  |   0m  7s |  the patch passed with JDK Ubuntu-11.0.22+7-post-Ubuntu-0ubuntu222.04.1  |
| +1 :green_heart: |  javadoc  |   0m  6s |  the patch passed with JDK Private Build-1.8.0_402-8u402-ga-2ubuntu1~22.04-b06  |
| +1 :green_heart: |  findbugs  |   0m 29s |  the patch passed  |
||| _ Other Tests _ |
| +1 :green_heart: |  unit  |   0m 37s |  tez-common in the patch passed.  |
| +1 :green_heart: |  asflicense  |   0m 19s |  The patch does not generate ASF License warnings.  |
|  |   |  36m 17s |   |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.44 ServerAPI=1.44 base: https://ci-hadoop.apache.org/job/tez-multibranch/job/PR-360/2/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/tez/pull/360 |
| JIRA Issue | TEZ-4568 |
| Optional Tests | dupname asflicense javac javadoc unit spotbugs findbugs checkstyle compile |
| uname | Linux 5bc00289db7d 5.15.0-94-generic #104-Ubuntu SMP Tue Jan 9 15:25:40 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | personality/tez.sh |
| git revision | master / 38c5aaccd |
| Default Java | Private Build-1.8.0_402-8u402-ga-2ubuntu1~22.04-b06 |
| Multi-JDK versions | /usr/lib/jvm/java-11-openjdk-amd64:Ubuntu-11.0.22+7-post-Ubuntu-0ubuntu222.04.1 /usr/lib/jvm/java-8-openjdk-amd64:Private Build-1.8.0_402-8u402-ga-2ubuntu1~22.04-b06 |
|  Test Results | https://ci-hadoop.apache.org/job/tez-multibranch/job/PR-360/2/testReport/ |
| Max. process+thread count | 106 (vs. ulimit of 5500) |
| modules | C: tez-common U: tez-common |
| Console output | https://ci-hadoop.apache.org/job/tez-multibranch/job/PR-360/2/console |
| versions | git=2.34.1 maven=3.6.3 findbugs=3.0.1 |
| Powered by | Apache Yetus 0.12.0 https://yetus.apache.org |


This message was automatically generated.

**Review by ayushtkn — APPROVED** [review]
LGTM

**Comment by tez-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| +0 :ok: |  reexec  |   0m  9s |  Docker mode activated.  |
||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  0s |  No case conflicting files found.  |
| +1 :green_heart: |  @author  |   0m  0s |  The patch does not contain any @author tags.  |
| -1 :x: |  test4tests  |   0m  0s |  The patch doesn't appear to include any new or modified tests. Please justify why no new tests are needed for this patch. Also please list what manual steps were performed to verify this patch.  |
||| _ master Compile Tests _ |
| +1 :green_heart: |  mvninstall  |  14m 54s |  master passed  |
| +1 :green_heart: |  compile  |   0m 17s |  master passed with JDK Ubuntu-11.0.22+7-post-Ubuntu-0ubuntu222.04.1  |
| +1 :green_heart: |  compile  |   0m 16s |  master passed with JDK Private Build-1.8.0_402-8u402-ga-2ubuntu1~22.04-b06  |
| +1 :green_heart: |  checkstyle  |   1m 15s |  master passed  |
| +1 :green_heart: |  javadoc  |   0m 37s |  master passed with JDK Ubuntu-11.0.22+7-post-Ubuntu-0ubuntu222.04.1  |
| +1 :green_heart: |  javadoc  |   0m 14s |  master passed with JDK Private Build-1.8.0_402-8u402-ga-2ubuntu1~22.04-b06  |
| +0 :ok: |  spotbugs  |   1m  2s |  Used deprecated FindBugs config; considering switching to SpotBugs.  |
| +1 :green_heart: |  findbugs  |   1m  2s |  master passed  |
||| _ Patch Compile Tests _ |
| +1 :green_heart: |  mvninstall  |   0m 10s |  the patch passed  |
| +1 :green_heart: |  compile  |   0m 10s |  the patch passed with JDK Ubuntu-11.0.22+7-post-Ubuntu-0ubuntu222.04.1  |
| +1 :green_heart: |  javac  |   0m 10s |  the patch passed  |
| +1 :green_heart: |  compile  |   0m 10s |  the patch passed with JDK Private Build-1.8.0_402-8u402-ga-2ubuntu1~22.04-b06  |
| +1 :green_heart: |  javac  |   0m 10s |  the patch passed  |
| +1 :green_heart: |  checkstyle  |   0m  5s |  the patch passed  |
| +1 :green_heart: |  whitespace  |   0m  0s |  The patch has no whitespace issues.  |
| +1 :green_heart: |  javadoc  |   0m  7s |  the patch passed with JDK Ubuntu-11.0.22+7-post-Ubuntu-0ubuntu222.04.1  |
| +1 :green_heart: |  javadoc  |   0m  7s |  the patch passed with JDK Private Build-1.8.0_402-8u402-ga-2ubuntu1~22.04-b06  |
| +1 :green_heart: |  findbugs  |   0m 25s |  the patch passed  |
||| _ Other Tests _ |
| +1 :green_heart: |  unit  |   0m 28s |  tez-common in the patch passed.  |
| +1 :green_heart: |  asflicense  |   0m 14s |  The patch does not generate ASF License warnings.  |
|  |   |  21m 18s |   |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.44 ServerAPI=1.44 base: https://ci-hadoop.apache.org/job/tez-multibranch/job/PR-360/4/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/tez/pull/360 |
| Optional Tests | dupname asflicense javac javadoc unit spotbugs findbugs checkstyle compile |
| uname | Linux 0e53db02f7f8 5.15.0-94-generic #104-Ubuntu SMP Tue Jan 9 15:25:40 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | personality/tez.sh |
| git revision | master / 38c5aaccd |
| Default Java | Private Build-1.8.0_402-8u402-ga-2ubuntu1~22.04-b06 |
| Multi-JDK versions | /usr/lib/jvm/java-11-openjdk-amd64:Ubuntu-11.0.22+7-post-Ubuntu-0ubuntu222.04.1 /usr/lib/jvm/java-8-openjdk-amd64:Private Build-1.8.0_402-8u402-ga-2ubuntu1~22.04-b06 |
|  Test Results | https://ci-hadoop.apache.org/job/tez-multibranch/job/PR-360/4/testReport/ |
| Max. process+thread count | 101 (vs. ulimit of 5500) |
| modules | C: tez-common U: tez-common |
| Console output | https://ci-hadoop.apache.org/job/tez-multibranch/job/PR-360/4/console |
| versions | git=2.34.1 maven=3.6.3 findbugs=3.0.1 |
| Powered by | Apache Yetus 0.12.0 https://yetus.apache.org |


This message was automatically generated.

**Pull request merged**
