### PR TITLE
TEZ-4464: Update some links to https

### PR DESCRIPTION
**Pull request by raboof**

### CODE REVIEW

**Comment by tez-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| +0 :ok: |  reexec  |  31m 43s |  Docker mode activated.  |
||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  0s |  No case conflicting files found.  |
| +1 :green_heart: |  @author  |   0m  0s |  The patch does not contain any @author tags.  |
| -1 :x: |  test4tests  |   0m  0s |  The patch doesn't appear to include any new or modified tests. Please justify why no new tests are needed for this patch. Also please list what manual steps were performed to verify this patch.  |
||| _ master Compile Tests _ |
| +1 :green_heart: |  mvninstall  |  15m 11s |  master passed  |
| +1 :green_heart: |  compile  |   0m 23s |  master passed with JDK Ubuntu-11.0.17+8-post-Ubuntu-1ubuntu220.04  |
| +1 :green_heart: |  compile  |   0m 23s |  master passed with JDK Private Build-1.8.0_352-8u352-ga-1~20.04-b08  |
| +1 :green_heart: |  mvnsite  |   0m 24s |  master passed  |
| +1 :green_heart: |  javadoc  |   0m 46s |  master passed with JDK Ubuntu-11.0.17+8-post-Ubuntu-1ubuntu220.04  |
| +1 :green_heart: |  javadoc  |   0m 23s |  master passed with JDK Private Build-1.8.0_352-8u352-ga-1~20.04-b08  |
||| _ Patch Compile Tests _ |
| +1 :green_heart: |  mvninstall  |   0m  9s |  the patch passed  |
| +1 :green_heart: |  compile  |   0m  8s |  the patch passed with JDK Ubuntu-11.0.17+8-post-Ubuntu-1ubuntu220.04  |
| +1 :green_heart: |  javac  |   0m  8s |  the patch passed  |
| +1 :green_heart: |  compile  |   0m  8s |  the patch passed with JDK Private Build-1.8.0_352-8u352-ga-1~20.04-b08  |
| +1 :green_heart: |  javac  |   0m  8s |  the patch passed  |
| -1 :x: |  markdownlint  |   0m  7s |  The patch generated 2 new + 195 unchanged - 2 fixed = 197 total (was 197)  |
| +1 :green_heart: |  mvnsite  |   0m  7s |  the patch passed  |
| +1 :green_heart: |  whitespace  |   0m  0s |  The patch has no whitespace issues.  |
| +1 :green_heart: |  xml  |   0m  2s |  The patch has no ill-formed XML file.  |
| +1 :green_heart: |  javadoc  |   0m  8s |  the patch passed with JDK Ubuntu-11.0.17+8-post-Ubuntu-1ubuntu220.04  |
| +1 :green_heart: |  javadoc  |   0m  8s |  the patch passed with JDK Private Build-1.8.0_352-8u352-ga-1~20.04-b08  |
||| _ Other Tests _ |
| +1 :green_heart: |  unit  |   0m  9s |  docs in the patch passed.  |
| +1 :green_heart: |  asflicense  |   0m 15s |  The patch does not generate ASF License warnings.  |
|  |   |  51m 23s |   |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.41 ServerAPI=1.41 base: https://ci-hadoop.apache.org/job/tez-multibranch/job/PR-260/1/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/tez/pull/260 |
| Optional Tests | dupname asflicense javac javadoc unit xml compile markdownlint mvnsite |
| uname | Linux 15069793f0e3 4.15.0-200-generic #211-Ubuntu SMP Thu Nov 24 18:16:04 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | personality/tez.sh |
| git revision | master / 34d681007 |
| Default Java | Private Build-1.8.0_352-8u352-ga-1~20.04-b08 |
| Multi-JDK versions | /usr/lib/jvm/java-11-openjdk-amd64:Ubuntu-11.0.17+8-post-Ubuntu-1ubuntu220.04 /usr/lib/jvm/java-8-openjdk-amd64:Private Build-1.8.0_352-8u352-ga-1~20.04-b08 |
| markdownlint | https://ci-hadoop.apache.org/job/tez-multibranch/job/PR-260/1/artifact/out/diff-patch-markdownlint.txt |
|  Test Results | https://ci-hadoop.apache.org/job/tez-multibranch/job/PR-260/1/testReport/ |
| Max. process+thread count | 77 (vs. ulimit of 5500) |
| modules | C: docs U: docs |
| Console output | https://ci-hadoop.apache.org/job/tez-multibranch/job/PR-260/1/console |
| versions | git=2.25.1 maven=3.6.3 markdownlint=0.23.2 |
| Powered by | Apache Yetus 0.12.0 https://yetus.apache.org |


This message was automatically generated.

**Comment by abstractdog** [comment]
thanks for this contribution @raboof , can you please create jira also?
https://issues.apache.org/jira/projects/TEZ/

**Comment by raboof** [comment]
> Please justify why no new tests are needed for this patch.

no tests were added because adding a link checker to the CI seems beyond the scope of this PR.

> Also please list what manual steps were performed to verify this patch.

I manually followed most updated links to verify the linked sites indeed support https. I did not verify the pages still serve useful content.

> can you please create jira also?

Sure, done!

**Comment by tez-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| +0 :ok: |  reexec  |   0m 30s |  Docker mode activated.  |
||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  0s |  No case conflicting files found.  |
| +1 :green_heart: |  @author  |   0m  0s |  The patch does not contain any @author tags.  |
| -1 :x: |  test4tests  |   0m  0s |  The patch doesn't appear to include any new or modified tests. Please justify why no new tests are needed for this patch. Also please list what manual steps were performed to verify this patch.  |
||| _ master Compile Tests _ |
| +1 :green_heart: |  mvninstall  |  15m  8s |  master passed  |
| +1 :green_heart: |  compile  |   0m 24s |  master passed with JDK Ubuntu-11.0.17+8-post-Ubuntu-1ubuntu220.04  |
| +1 :green_heart: |  compile  |   0m 24s |  master passed with JDK Private Build-1.8.0_352-8u352-ga-1~20.04-b08  |
| +1 :green_heart: |  mvnsite  |   0m 26s |  master passed  |
| +1 :green_heart: |  javadoc  |   0m 43s |  master passed with JDK Ubuntu-11.0.17+8-post-Ubuntu-1ubuntu220.04  |
| +1 :green_heart: |  javadoc  |   0m 24s |  master passed with JDK Private Build-1.8.0_352-8u352-ga-1~20.04-b08  |
||| _ Patch Compile Tests _ |
| +1 :green_heart: |  mvninstall  |   0m 10s |  the patch passed  |
| +1 :green_heart: |  compile  |   0m  9s |  the patch passed with JDK Ubuntu-11.0.17+8-post-Ubuntu-1ubuntu220.04  |
| +1 :green_heart: |  javac  |   0m  9s |  the patch passed  |
| +1 :green_heart: |  compile  |   0m  8s |  the patch passed with JDK Private Build-1.8.0_352-8u352-ga-1~20.04-b08  |
| +1 :green_heart: |  javac  |   0m  8s |  the patch passed  |
| -1 :x: |  markdownlint  |   0m  7s |  The patch generated 2 new + 195 unchanged - 2 fixed = 197 total (was 197)  |
| +1 :green_heart: |  mvnsite  |   0m  8s |  the patch passed  |
| +1 :green_heart: |  whitespace  |   0m  0s |  The patch has no whitespace issues.  |
| +1 :green_heart: |  xml  |   0m  2s |  The patch has no ill-formed XML file.  |
| +1 :green_heart: |  javadoc  |   0m  8s |  the patch passed with JDK Ubuntu-11.0.17+8-post-Ubuntu-1ubuntu220.04  |
| +1 :green_heart: |  javadoc  |   0m  8s |  the patch passed with JDK Private Build-1.8.0_352-8u352-ga-1~20.04-b08  |
||| _ Other Tests _ |
| +1 :green_heart: |  unit  |   0m  8s |  docs in the patch passed.  |
| +1 :green_heart: |  asflicense  |   0m 15s |  The patch does not generate ASF License warnings.  |
|  |   |  20m 10s |   |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.41 ServerAPI=1.41 base: https://ci-hadoop.apache.org/job/tez-multibranch/job/PR-260/2/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/tez/pull/260 |
| JIRA Issue | TEZ-4464 |
| Optional Tests | dupname asflicense javac javadoc unit xml compile markdownlint mvnsite |
| uname | Linux 18bbacc570c2 4.15.0-200-generic #211-Ubuntu SMP Thu Nov 24 18:16:04 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | personality/tez.sh |
| git revision | master / 34d681007 |
| Default Java | Private Build-1.8.0_352-8u352-ga-1~20.04-b08 |
| Multi-JDK versions | /usr/lib/jvm/java-11-openjdk-amd64:Ubuntu-11.0.17+8-post-Ubuntu-1ubuntu220.04 /usr/lib/jvm/java-8-openjdk-amd64:Private Build-1.8.0_352-8u352-ga-1~20.04-b08 |
| markdownlint | https://ci-hadoop.apache.org/job/tez-multibranch/job/PR-260/2/artifact/out/diff-patch-markdownlint.txt |
|  Test Results | https://ci-hadoop.apache.org/job/tez-multibranch/job/PR-260/2/testReport/ |
| Max. process+thread count | 77 (vs. ulimit of 5500) |
| modules | C: docs U: docs |
| Console output | https://ci-hadoop.apache.org/job/tez-multibranch/job/PR-260/2/console |
| versions | git=2.25.1 maven=3.6.3 markdownlint=0.23.2 |
| Powered by | Apache Yetus 0.12.0 https://yetus.apache.org |


This message was automatically generated.

**Comment by tez-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| +0 :ok: |  reexec  |  40m  8s |  Docker mode activated.  |
||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  0s |  No case conflicting files found.  |
| +1 :green_heart: |  @author  |   0m  0s |  The patch does not contain any @author tags.  |
| -1 :x: |  test4tests  |   0m  0s |  The patch doesn't appear to include any new or modified tests. Please justify why no new tests are needed for this patch. Also please list what manual steps were performed to verify this patch.  |
||| _ master Compile Tests _ |
| +1 :green_heart: |  mvninstall  |  16m 18s |  master passed  |
| +1 :green_heart: |  compile  |   0m 18s |  master passed with JDK Ubuntu-11.0.17+8-post-Ubuntu-1ubuntu220.04  |
| +1 :green_heart: |  compile  |   0m 20s |  master passed with JDK Private Build-1.8.0_352-8u352-ga-1~20.04-b08  |
| +1 :green_heart: |  mvnsite  |   0m 22s |  master passed  |
| +1 :green_heart: |  javadoc  |   0m 39s |  master passed with JDK Ubuntu-11.0.17+8-post-Ubuntu-1ubuntu220.04  |
| +1 :green_heart: |  javadoc  |   0m 18s |  master passed with JDK Private Build-1.8.0_352-8u352-ga-1~20.04-b08  |
||| _ Patch Compile Tests _ |
| +1 :green_heart: |  mvninstall  |   0m  8s |  the patch passed  |
| +1 :green_heart: |  compile  |   0m  7s |  the patch passed with JDK Ubuntu-11.0.17+8-post-Ubuntu-1ubuntu220.04  |
| +1 :green_heart: |  javac  |   0m  7s |  the patch passed  |
| +1 :green_heart: |  compile  |   0m  9s |  the patch passed with JDK Private Build-1.8.0_352-8u352-ga-1~20.04-b08  |
| +1 :green_heart: |  javac  |   0m  9s |  the patch passed  |
| -1 :x: |  markdownlint  |   0m  6s |  The patch generated 2 new + 195 unchanged - 2 fixed = 197 total (was 197)  |
| +1 :green_heart: |  mvnsite  |   0m  7s |  the patch passed  |
| +1 :green_heart: |  whitespace  |   0m  0s |  The patch has no whitespace issues.  |
| +1 :green_heart: |  xml  |   0m  2s |  The patch has no ill-formed XML file.  |
| +1 :green_heart: |  javadoc  |   0m  8s |  the patch passed with JDK Ubuntu-11.0.17+8-post-Ubuntu-1ubuntu220.04  |
| +1 :green_heart: |  javadoc  |   0m  8s |  the patch passed with JDK Private Build-1.8.0_352-8u352-ga-1~20.04-b08  |
||| _ Other Tests _ |
| +1 :green_heart: |  unit  |   0m  8s |  docs in the patch passed.  |
| +1 :green_heart: |  asflicense  |   0m 14s |  The patch does not generate ASF License warnings.  |
|  |   |  60m 25s |   |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.41 ServerAPI=1.41 base: https://ci-hadoop.apache.org/job/tez-multibranch/job/PR-260/4/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/tez/pull/260 |
| JIRA Issue | TEZ-4464 |
| Optional Tests | dupname asflicense javac javadoc unit xml compile markdownlint mvnsite |
| uname | Linux 7fc12a0b6741 4.15.0-200-generic #211-Ubuntu SMP Thu Nov 24 18:16:04 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | personality/tez.sh |
| git revision | master / 34d681007 |
| Default Java | Private Build-1.8.0_352-8u352-ga-1~20.04-b08 |
| Multi-JDK versions | /usr/lib/jvm/java-11-openjdk-amd64:Ubuntu-11.0.17+8-post-Ubuntu-1ubuntu220.04 /usr/lib/jvm/java-8-openjdk-amd64:Private Build-1.8.0_352-8u352-ga-1~20.04-b08 |
| markdownlint | https://ci-hadoop.apache.org/job/tez-multibranch/job/PR-260/4/artifact/out/diff-patch-markdownlint.txt |
|  Test Results | https://ci-hadoop.apache.org/job/tez-multibranch/job/PR-260/4/testReport/ |
| Max. process+thread count | 72 (vs. ulimit of 5500) |
| modules | C: docs U: docs |
| Console output | https://ci-hadoop.apache.org/job/tez-multibranch/job/PR-260/4/console |
| versions | git=2.25.1 maven=3.6.3 markdownlint=0.23.2 |
| Powered by | Apache Yetus 0.12.0 https://yetus.apache.org |


This message was automatically generated.

**Comment by tez-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| +0 :ok: |  reexec  |  39m 40s |  Docker mode activated.  |
||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  0s |  No case conflicting files found.  |
| +1 :green_heart: |  @author  |   0m  0s |  The patch does not contain any @author tags.  |
| -1 :x: |  test4tests  |   0m  0s |  The patch doesn't appear to include any new or modified tests. Please justify why no new tests are needed for this patch. Also please list what manual steps were performed to verify this patch.  |
||| _ master Compile Tests _ |
| +1 :green_heart: |  mvninstall  |  18m  9s |  master passed  |
| +1 :green_heart: |  compile  |   0m 20s |  master passed with JDK Ubuntu-11.0.17+8-post-Ubuntu-1ubuntu220.04  |
| +1 :green_heart: |  compile  |   0m 17s |  master passed with JDK Private Build-1.8.0_352-8u352-ga-1~20.04-b08  |
| +1 :green_heart: |  mvnsite  |   0m 21s |  master passed  |
| +1 :green_heart: |  javadoc  |   0m 39s |  master passed with JDK Ubuntu-11.0.17+8-post-Ubuntu-1ubuntu220.04  |
| +1 :green_heart: |  javadoc  |   0m 19s |  master passed with JDK Private Build-1.8.0_352-8u352-ga-1~20.04-b08  |
||| _ Patch Compile Tests _ |
| +1 :green_heart: |  mvninstall  |   0m  8s |  the patch passed  |
| +1 :green_heart: |  compile  |   0m  8s |  the patch passed with JDK Ubuntu-11.0.17+8-post-Ubuntu-1ubuntu220.04  |
| +1 :green_heart: |  javac  |   0m  8s |  the patch passed  |
| +1 :green_heart: |  compile  |   0m  7s |  the patch passed with JDK Private Build-1.8.0_352-8u352-ga-1~20.04-b08  |
| +1 :green_heart: |  javac  |   0m  7s |  the patch passed  |
| -1 :x: |  markdownlint  |   0m  7s |  The patch generated 2 new + 195 unchanged - 2 fixed = 197 total (was 197)  |
| +1 :green_heart: |  mvnsite  |   0m  7s |  the patch passed  |
| +1 :green_heart: |  whitespace  |   0m  0s |  The patch has no whitespace issues.  |
| +1 :green_heart: |  xml  |   0m  3s |  The patch has no ill-formed XML file.  |
| +1 :green_heart: |  javadoc  |   0m  8s |  the patch passed with JDK Ubuntu-11.0.17+8-post-Ubuntu-1ubuntu220.04  |
| +1 :green_heart: |  javadoc  |   0m  8s |  the patch passed with JDK Private Build-1.8.0_352-8u352-ga-1~20.04-b08  |
||| _ Other Tests _ |
| +1 :green_heart: |  unit  |   0m  8s |  docs in the patch passed.  |
| +1 :green_heart: |  asflicense  |   0m 14s |  The patch does not generate ASF License warnings.  |
|  |   |  61m 46s |   |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.41 ServerAPI=1.41 base: https://ci-hadoop.apache.org/job/tez-multibranch/job/PR-260/3/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/tez/pull/260 |
| JIRA Issue | TEZ-4464 |
| Optional Tests | dupname asflicense javac javadoc unit xml compile markdownlint mvnsite |
| uname | Linux 427d1328a191 4.15.0-200-generic #211-Ubuntu SMP Thu Nov 24 18:16:04 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | personality/tez.sh |
| git revision | master / 34d681007 |
| Default Java | Private Build-1.8.0_352-8u352-ga-1~20.04-b08 |
| Multi-JDK versions | /usr/lib/jvm/java-11-openjdk-amd64:Ubuntu-11.0.17+8-post-Ubuntu-1ubuntu220.04 /usr/lib/jvm/java-8-openjdk-amd64:Private Build-1.8.0_352-8u352-ga-1~20.04-b08 |
| markdownlint | https://ci-hadoop.apache.org/job/tez-multibranch/job/PR-260/3/artifact/out/diff-patch-markdownlint.txt |
|  Test Results | https://ci-hadoop.apache.org/job/tez-multibranch/job/PR-260/3/testReport/ |
| Max. process+thread count | 72 (vs. ulimit of 5500) |
| modules | C: docs U: docs |
| Console output | https://ci-hadoop.apache.org/job/tez-multibranch/job/PR-260/3/console |
| versions | git=2.25.1 maven=3.6.3 markdownlint=0.23.2 |
| Powered by | Apache Yetus 0.12.0 https://yetus.apache.org |


This message was automatically generated.

**Review by abstractdog — APPROVED** [review]
markdownlint issues are not introduced by this patch, LGTM +1

**Pull request merged**
