### PR TITLE
TEZ-4296 - Use listStatusIterator instead of listStatus in DatePartitionedLogger.

### PR DESCRIPTION
**Pull request by harishjp**

### CODE REVIEW

**Comment by jteagles** [comment]
@harishjp, Looks pretty good. Can you help me understand why the file system implementation is set to org.apache.hadoop.fs.RawLocalFileSystem in the test? I assume it passes without change.

**Comment by harishjp** [comment]
The LocalFileSystem does not override listStatusIterator to remove the .crc files from the listing and that is returning the .crc as file which it should not. For now I'm setting it to RawLocalFileSystem which does not create the crc file and hence works. This has to be fixed in hadoop by overriding listStatusIterator which applies the PATH_FILTER, I'll file a bug in hadoop for this.

**Comment by jteagles** [comment]
@harishjp, what is the expected file system for this system. Would LocalFileSystem ever be used in this use case for customer installations?

**Comment by harishjp** [comment]
The expected filesystem is a filesystem like hdfs, s3fs, azure/abfs. I've not come across a case where LocalFileSystem is being used except tests.

**Comment by jteagles** [comment]
+1. Please file and link the HADOOP jira so it can be tracked. I can can check this in today.

**Comment by harishjp** [comment]
Thanks @jteagles, I've created and linked the hadoop issue.

**Pull request merged**
