### PR TITLE
Limit Operator Bailout

### PR DESCRIPTION
**Pull request by HarshitGupta11**
Don't Review Yet. Experimental Changes for testing purposes.

### CODE REVIEW

**Comment by hadoop-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| +0 :ok: |  reexec  |  17m 27s |  Docker mode activated.  |
||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  0s |  No case conflicting files found.  |
| +1 :green_heart: |  @author  |   0m  0s |  The patch does not contain any @author tags.  |
| -1 :x: |  test4tests  |   0m  0s |  The patch doesn't appear to include any new or modified tests. Please justify why no new tests are needed for this patch. Also please list what manual steps were performed to verify this patch.  |
||| _ branch-0.10.1 Compile Tests _ |
| +0 :ok: |  mvndep  |   4m 51s |  Maven dependency ordering for branch  |
| +1 :green_heart: |  mvninstall  |   8m 55s |  branch-0.10.1 passed  |
| +1 :green_heart: |  compile  |   3m 48s |  branch-0.10.1 passed with JDK Ubuntu-11.0.11+9-Ubuntu-0ubuntu2.20.04  |
| +1 :green_heart: |  compile  |   3m 22s |  branch-0.10.1 passed with JDK Private Build-1.8.0_292-8u292-b10-0ubuntu1~20.04-b10  |
| +1 :green_heart: |  checkstyle  |   2m  3s |  branch-0.10.1 passed  |
| +1 :green_heart: |  javadoc  |   3m 50s |  branch-0.10.1 passed with JDK Ubuntu-11.0.11+9-Ubuntu-0ubuntu2.20.04  |
| +1 :green_heart: |  javadoc  |   2m 50s |  branch-0.10.1 passed with JDK Private Build-1.8.0_292-8u292-b10-0ubuntu1~20.04-b10  |
| +0 :ok: |  spotbugs  |   7m 21s |  Used deprecated FindBugs config; considering switching to SpotBugs.  |
| +0 :ok: |  findbugs  |   7m 14s |  root in branch-0.10.1 has 2 extant findbugs warnings.  |
||| _ Patch Compile Tests _ |
| +0 :ok: |  mvndep  |   0m 15s |  Maven dependency ordering for patch  |
| +1 :green_heart: |  mvninstall  |   5m 13s |  the patch passed  |
| +1 :green_heart: |  compile  |   4m  0s |  the patch passed with JDK Ubuntu-11.0.11+9-Ubuntu-0ubuntu2.20.04  |
| +1 :green_heart: |  javac  |   4m  0s |  the patch passed  |
| +1 :green_heart: |  compile  |   3m 35s |  the patch passed with JDK Private Build-1.8.0_292-8u292-b10-0ubuntu1~20.04-b10  |
| +1 :green_heart: |  javac  |   3m 35s |  the patch passed  |
| +1 :green_heart: |  checkstyle  |   1m 39s |  the patch passed  |
| +1 :green_heart: |  whitespace  |   0m  0s |  The patch has no whitespace issues.  |
| +1 :green_heart: |  xml  |   0m  1s |  The patch has no ill-formed XML file.  |
| +1 :green_heart: |  javadoc  |   3m 34s |  the patch passed with JDK Ubuntu-11.0.11+9-Ubuntu-0ubuntu2.20.04  |
| +1 :green_heart: |  javadoc  |   2m 52s |  the patch passed with JDK Private Build-1.8.0_292-8u292-b10-0ubuntu1~20.04-b10  |
| -1 :x: |  findbugs  |   1m  2s |  tez-runtime-internals generated 1 new + 0 unchanged - 0 fixed = 1 total (was 0)  |
| -1 :x: |  findbugs  |   7m 46s |  root generated 1 new + 2 unchanged - 0 fixed = 3 total (was 2)  |
||| _ Other Tests _ |
| +1 :green_heart: |  unit  |   2m 22s |  tez-api in the patch passed.  |
| +1 :green_heart: |  unit  |   0m 46s |  tez-runtime-internals in the patch passed.  |
| +1 :green_heart: |  unit  |  75m 42s |  root in the patch passed.  |
| -1 :x: |  asflicense  |   1m  9s |  The patch generated 1 ASF License warnings.  |
|  |   | 170m  2s |   |


| Reason | Tests |
|-------:|:------|
| FindBugs | module:tez-runtime-internals |
|  |  Write to static field org.apache.tez.runtime.LogicalIOProcessorRuntimeTask.isLimitReached from instance method org.apache.tez.runtime.LogicalIOProcessorRuntimeTask.close()  At LogicalIOProcessorRuntimeTask.java:from instance method org.apache.tez.runtime.LogicalIOProcessorRuntimeTask.close()  At LogicalIOProcessorRuntimeTask.java:[line 409] |
| FindBugs | module:root |
|  |  Write to static field org.apache.tez.runtime.LogicalIOProcessorRuntimeTask.isLimitReached from instance method org.apache.tez.runtime.LogicalIOProcessorRuntimeTask.close()  At LogicalIOProcessorRuntimeTask.java:from instance method org.apache.tez.runtime.LogicalIOProcessorRuntimeTask.close()  At LogicalIOProcessorRuntimeTask.java:[line 409] |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.41 ServerAPI=1.41 base: https://ci-hadoop.apache.org/job/tez-multibranch/job/PR-159/1/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/tez/pull/159 |
| Optional Tests | dupname asflicense javac javadoc unit xml compile spotbugs findbugs checkstyle |
| uname | Linux 403f5e0e9e4c 4.15.0-153-generic #160-Ubuntu SMP Thu Jul 29 06:54:29 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | personality/tez.sh |
| git revision | branch-0.10.1 / 355fbc14c |
| Default Java | Private Build-1.8.0_292-8u292-b10-0ubuntu1~20.04-b10 |
| Multi-JDK versions | /usr/lib/jvm/java-11-openjdk-amd64:Ubuntu-11.0.11+9-Ubuntu-0ubuntu2.20.04 /usr/lib/jvm/java-8-openjdk-amd64:Private Build-1.8.0_292-8u292-b10-0ubuntu1~20.04-b10 |
| findbugs | https://ci-hadoop.apache.org/job/tez-multibranch/job/PR-159/1/artifact/out/new-findbugs-tez-runtime-internals.html |
| findbugs | https://ci-hadoop.apache.org/job/tez-multibranch/job/PR-159/1/artifact/out/new-findbugs-root.html |
|  Test Results | https://ci-hadoop.apache.org/job/tez-multibranch/job/PR-159/1/testReport/ |
| asflicense | https://ci-hadoop.apache.org/job/tez-multibranch/job/PR-159/1/artifact/out/patch-asflicense-problems.txt |
| Max. process+thread count | 1364 (vs. ulimit of 5500) |
| modules | C: tez-api tez-runtime-internals . U: . |
| Console output | https://ci-hadoop.apache.org/job/tez-multibranch/job/PR-159/1/console |
| versions | git=2.25.1 maven=3.6.3 findbugs=3.0.1 |
| Powered by | Apache Yetus 0.12.0 https://yetus.apache.org |


This message was automatically generated.

**Comment by hadoop-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| +0 :ok: |  reexec  |   1m 11s |  Docker mode activated.  |
||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  0s |  No case conflicting files found.  |
| +1 :green_heart: |  @author  |   0m  0s |  The patch does not contain any @author tags.  |
| -1 :x: |  test4tests  |   0m  0s |  The patch doesn't appear to include any new or modified tests. Please justify why no new tests are needed for this patch. Also please list what manual steps were performed to verify this patch.  |
||| _ branch-0.10.1 Compile Tests _ |
| +0 :ok: |  mvndep  |   4m 48s |  Maven dependency ordering for branch  |
| +1 :green_heart: |  mvninstall  |   8m 35s |  branch-0.10.1 passed  |
| +1 :green_heart: |  compile  |   3m 36s |  branch-0.10.1 passed with JDK Ubuntu-11.0.11+9-Ubuntu-0ubuntu2.20.04  |
| +1 :green_heart: |  compile  |   3m 15s |  branch-0.10.1 passed with JDK Private Build-1.8.0_292-8u292-b10-0ubuntu1~20.04-b10  |
| +1 :green_heart: |  checkstyle  |   2m  8s |  branch-0.10.1 passed  |
| +1 :green_heart: |  javadoc  |   3m 24s |  branch-0.10.1 passed with JDK Ubuntu-11.0.11+9-Ubuntu-0ubuntu2.20.04  |
| +1 :green_heart: |  javadoc  |   2m 51s |  branch-0.10.1 passed with JDK Private Build-1.8.0_292-8u292-b10-0ubuntu1~20.04-b10  |
| +0 :ok: |  spotbugs  |   5m 53s |  Used deprecated FindBugs config; considering switching to SpotBugs.  |
| +0 :ok: |  findbugs  |   5m 50s |  root in branch-0.10.1 has 2 extant findbugs warnings.  |
||| _ Patch Compile Tests _ |
| +0 :ok: |  mvndep  |   0m 13s |  Maven dependency ordering for patch  |
| +1 :green_heart: |  mvninstall  |   4m 48s |  the patch passed  |
| +1 :green_heart: |  compile  |   3m 37s |  the patch passed with JDK Ubuntu-11.0.11+9-Ubuntu-0ubuntu2.20.04  |
| +1 :green_heart: |  javac  |   3m 37s |  the patch passed  |
| +1 :green_heart: |  compile  |   3m 17s |  the patch passed with JDK Private Build-1.8.0_292-8u292-b10-0ubuntu1~20.04-b10  |
| +1 :green_heart: |  javac  |   3m 17s |  the patch passed  |
| -0 :warning: |  checkstyle  |   0m 20s |  tez-mapreduce: The patch generated 1 new + 4 unchanged - 0 fixed = 5 total (was 4)  |
| -0 :warning: |  checkstyle  |   0m 47s |  root: The patch generated 1 new + 49 unchanged - 0 fixed = 50 total (was 49)  |
| +1 :green_heart: |  whitespace  |   0m  0s |  The patch has no whitespace issues.  |
| +1 :green_heart: |  xml  |   0m  1s |  The patch has no ill-formed XML file.  |
| +1 :green_heart: |  javadoc  |   3m 17s |  the patch passed with JDK Ubuntu-11.0.11+9-Ubuntu-0ubuntu2.20.04  |
| +1 :green_heart: |  javadoc  |   2m 49s |  the patch passed with JDK Private Build-1.8.0_292-8u292-b10-0ubuntu1~20.04-b10  |
| +1 :green_heart: |  findbugs  |   8m 51s |  the patch passed  |
||| _ Other Tests _ |
| +1 :green_heart: |  unit  |   2m  2s |  tez-api in the patch passed.  |
| +1 :green_heart: |  unit  |   0m 40s |  tez-runtime-internals in the patch passed.  |
| +1 :green_heart: |  unit  |   1m 17s |  tez-mapreduce in the patch passed.  |
| -1 :x: |  unit  |  13m 47s |  root in the patch failed.  |
| -1 :x: |  asflicense  |   1m 16s |  The patch generated 1 ASF License warnings.  |
|  |   |  88m  4s |   |


| Reason | Tests |
|-------:|:------|
| Failed junit tests | tez.dag.app.rm.TestTaskScheduler |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.41 ServerAPI=1.41 base: https://ci-hadoop.apache.org/job/tez-multibranch/job/PR-159/2/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/tez/pull/159 |
| Optional Tests | dupname asflicense javac javadoc unit xml compile spotbugs findbugs checkstyle |
| uname | Linux e529445650c8 4.15.0-153-generic #160-Ubuntu SMP Thu Jul 29 06:54:29 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | personality/tez.sh |
| git revision | branch-0.10.1 / 355fbc14c |
| Default Java | Private Build-1.8.0_292-8u292-b10-0ubuntu1~20.04-b10 |
| Multi-JDK versions | /usr/lib/jvm/java-11-openjdk-amd64:Ubuntu-11.0.11+9-Ubuntu-0ubuntu2.20.04 /usr/lib/jvm/java-8-openjdk-amd64:Private Build-1.8.0_292-8u292-b10-0ubuntu1~20.04-b10 |
| checkstyle | https://ci-hadoop.apache.org/job/tez-multibranch/job/PR-159/2/artifact/out/diff-checkstyle-tez-mapreduce.txt |
| checkstyle | https://ci-hadoop.apache.org/job/tez-multibranch/job/PR-159/2/artifact/out/diff-checkstyle-root.txt |
| unit | https://ci-hadoop.apache.org/job/tez-multibranch/job/PR-159/2/artifact/out/patch-unit-root.txt |
|  Test Results | https://ci-hadoop.apache.org/job/tez-multibranch/job/PR-159/2/testReport/ |
| asflicense | https://ci-hadoop.apache.org/job/tez-multibranch/job/PR-159/2/artifact/out/patch-asflicense-problems.txt |
| Max. process+thread count | 2089 (vs. ulimit of 5500) |
| modules | C: tez-api tez-runtime-internals tez-mapreduce . U: . |
| Console output | https://ci-hadoop.apache.org/job/tez-multibranch/job/PR-159/2/console |
| versions | git=2.25.1 maven=3.6.3 findbugs=3.0.1 |
| Powered by | Apache Yetus 0.12.0 https://yetus.apache.org |


This message was automatically generated.

**Comment by shameersss1** [comment]
@HarshitGupta11  - Is this similar to https://issues.apache.org/jira/browse/TEZ-2103

**Comment by HarshitGupta11** [comment]
@shameersss1  It's similar but I was trying to fix this issue: https://issues.apache.org/jira/browse/HIVE-24207, this is an optimization on the Hive LLAP side. The patch for the issue causes a race condition between the consumer and the producer thread, inadvertently causing the vertex and the dag to fail.

**Pull request closed without merging**
