### PR TITLE
TEZ-4157: ShuffleHandler: upgrade to netty4

### PR DESCRIPTION
**Pull request by abstractdog**

### CODE REVIEW

**Comment by hadoop-yetus** [comment]
:confetti_ball: **+1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| +0 :ok: |  reexec  |  17m 31s |  Docker mode activated.  |
||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  0s |  No case conflicting files found.  |
| +1 :green_heart: |  @author  |   0m  0s |  The patch does not contain any @author tags.  |
| +1 :green_heart: |  test4tests  |   0m  0s |  The patch appears to include 2 new or modified test files.  |
||| _ master Compile Tests _ |
| +0 :ok: |  mvndep  |   5m 57s |  Maven dependency ordering for branch  |
| +1 :green_heart: |  mvninstall  |   8m 28s |  master passed  |
| +1 :green_heart: |  compile  |   3m  3s |  master passed with JDK Ubuntu-11.0.10+9-Ubuntu-0ubuntu1.20.04  |
| +1 :green_heart: |  compile  |   2m 45s |  master passed with JDK Private Build-1.8.0_282-8u282-b08-0ubuntu1~20.04-b08  |
| +1 :green_heart: |  checkstyle  |   1m 48s |  master passed  |
| +1 :green_heart: |  javadoc  |   2m 50s |  master passed with JDK Ubuntu-11.0.10+9-Ubuntu-0ubuntu1.20.04  |
| +1 :green_heart: |  javadoc  |   2m 16s |  master passed with JDK Private Build-1.8.0_282-8u282-b08-0ubuntu1~20.04-b08  |
| +0 :ok: |  spotbugs  |   5m 56s |  Used deprecated FindBugs config; considering switching to SpotBugs.  |
| +0 :ok: |  findbugs  |   5m 51s |  root in master has 2 extant findbugs warnings.  |
||| _ Patch Compile Tests _ |
| +0 :ok: |  mvndep  |   0m 16s |  Maven dependency ordering for patch  |
| +1 :green_heart: |  mvninstall  |   4m 43s |  the patch passed  |
| +1 :green_heart: |  compile  |   3m  2s |  the patch passed with JDK Ubuntu-11.0.10+9-Ubuntu-0ubuntu1.20.04  |
| +1 :green_heart: |  javac  |   3m  2s |  the patch passed  |
| +1 :green_heart: |  compile  |   2m 46s |  the patch passed with JDK Private Build-1.8.0_282-8u282-b08-0ubuntu1~20.04-b08  |
| +1 :green_heart: |  javac  |   2m 46s |  the patch passed  |
| -0 :warning: |  checkstyle  |   0m 18s |  tez-ext-service-tests: The patch generated 4 new + 31 unchanged - 7 fixed = 35 total (was 38)  |
| -0 :warning: |  checkstyle  |   0m 18s |  tez-plugins/tez-aux-services: The patch generated 1 new + 66 unchanged - 9 fixed = 67 total (was 75)  |
| -0 :warning: |  checkstyle  |   0m 46s |  root: The patch generated 5 new + 97 unchanged - 16 fixed = 102 total (was 113)  |
| +1 :green_heart: |  whitespace  |   0m  0s |  The patch has no whitespace issues.  |
| +1 :green_heart: |  xml  |   0m  4s |  The patch has no ill-formed XML file.  |
| +1 :green_heart: |  javadoc  |   2m 40s |  the patch passed with JDK Ubuntu-11.0.10+9-Ubuntu-0ubuntu1.20.04  |
| +1 :green_heart: |  javadoc  |   2m 17s |  the patch passed with JDK Private Build-1.8.0_282-8u282-b08-0ubuntu1~20.04-b08  |
| +1 :green_heart: |  findbugs  |   7m 32s |  the patch passed  |
||| _ Other Tests _ |
| +1 :green_heart: |  unit  |   4m  0s |  tez-ext-service-tests in the patch passed.  |
| +1 :green_heart: |  unit  |   2m 41s |  tez-aux-services in the patch passed.  |
| +1 :green_heart: |  unit  |  72m 13s |  root in the patch passed.  |
| +1 :green_heart: |  asflicense  |   1m  7s |  The patch does not generate ASF License warnings.  |
|  |   | 158m 37s |   |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.41 ServerAPI=1.41 base: https://ci-hadoop.apache.org/job/tez-multibranch/job/PR-118/1/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/tez/pull/118 |
| JIRA Issue | TEZ-4157 |
| Optional Tests | dupname asflicense javac javadoc unit xml compile spotbugs findbugs checkstyle |
| uname | Linux 33d97bd5399b 4.15.0-128-generic #131-Ubuntu SMP Wed Dec 9 06:57:35 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | personality/tez.sh |
| git revision | master / 2b671d621 |
| Default Java | Private Build-1.8.0_282-8u282-b08-0ubuntu1~20.04-b08 |
| Multi-JDK versions | /usr/lib/jvm/java-11-openjdk-amd64:Ubuntu-11.0.10+9-Ubuntu-0ubuntu1.20.04 /usr/lib/jvm/java-8-openjdk-amd64:Private Build-1.8.0_282-8u282-b08-0ubuntu1~20.04-b08 |
| checkstyle | https://ci-hadoop.apache.org/job/tez-multibranch/job/PR-118/1/artifact/out/diff-checkstyle-tez-ext-service-tests.txt |
| checkstyle | https://ci-hadoop.apache.org/job/tez-multibranch/job/PR-118/1/artifact/out/diff-checkstyle-tez-plugins_tez-aux-services.txt |
| checkstyle | https://ci-hadoop.apache.org/job/tez-multibranch/job/PR-118/1/artifact/out/diff-checkstyle-root.txt |
|  Test Results | https://ci-hadoop.apache.org/job/tez-multibranch/job/PR-118/1/testReport/ |
| Max. process+thread count | 1386 (vs. ulimit of 5500) |
| modules | C: tez-ext-service-tests tez-plugins/tez-aux-services . U: . |
| Console output | https://ci-hadoop.apache.org/job/tez-multibranch/job/PR-118/1/console |
| versions | git=2.25.1 maven=3.6.3 findbugs=3.0.1 |
| Powered by | Apache Yetus 0.12.0 https://yetus.apache.org |


This message was automatically generated.

**Comment by hadoop-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| +0 :ok: |  reexec  |  17m 11s |  Docker mode activated.  |
||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  0s |  No case conflicting files found.  |
| +1 :green_heart: |  @author  |   0m  0s |  The patch does not contain any @author tags.  |
| +1 :green_heart: |  test4tests  |   0m  0s |  The patch appears to include 2 new or modified test files.  |
||| _ master Compile Tests _ |
| +0 :ok: |  mvndep  |   5m 47s |  Maven dependency ordering for branch  |
| +1 :green_heart: |  mvninstall  |   8m 34s |  master passed  |
| +1 :green_heart: |  compile  |   3m  7s |  master passed with JDK Ubuntu-11.0.10+9-Ubuntu-0ubuntu1.20.04  |
| +1 :green_heart: |  compile  |   2m 55s |  master passed with JDK Private Build-1.8.0_282-8u282-b08-0ubuntu1~20.04-b08  |
| +1 :green_heart: |  checkstyle  |   1m 45s |  master passed  |
| +1 :green_heart: |  javadoc  |   3m  2s |  master passed with JDK Ubuntu-11.0.10+9-Ubuntu-0ubuntu1.20.04  |
| +1 :green_heart: |  javadoc  |   2m 34s |  master passed with JDK Private Build-1.8.0_282-8u282-b08-0ubuntu1~20.04-b08  |
| +0 :ok: |  spotbugs  |   6m 25s |  Used deprecated FindBugs config; considering switching to SpotBugs.  |
| +0 :ok: |  findbugs  |   6m 20s |  root in master has 2 extant findbugs warnings.  |
||| _ Patch Compile Tests _ |
| +0 :ok: |  mvndep  |   0m 18s |  Maven dependency ordering for patch  |
| +1 :green_heart: |  mvninstall  |   5m 47s |  the patch passed  |
| +1 :green_heart: |  compile  |   4m  2s |  the patch passed with JDK Ubuntu-11.0.10+9-Ubuntu-0ubuntu1.20.04  |
| +1 :green_heart: |  javac  |   4m  2s |  the patch passed  |
| +1 :green_heart: |  compile  |   3m 32s |  the patch passed with JDK Private Build-1.8.0_282-8u282-b08-0ubuntu1~20.04-b08  |
| +1 :green_heart: |  javac  |   3m 32s |  the patch passed  |
| -0 :warning: |  checkstyle  |   0m 22s |  tez-ext-service-tests: The patch generated 4 new + 31 unchanged - 7 fixed = 35 total (was 38)  |
| -0 :warning: |  checkstyle  |   0m 21s |  tez-plugins/tez-aux-services: The patch generated 1 new + 66 unchanged - 9 fixed = 67 total (was 75)  |
| -0 :warning: |  checkstyle  |   1m  2s |  root: The patch generated 5 new + 97 unchanged - 16 fixed = 102 total (was 113)  |
| +1 :green_heart: |  whitespace  |   0m  0s |  The patch has no whitespace issues.  |
| +1 :green_heart: |  xml  |   0m  4s |  The patch has no ill-formed XML file.  |
| +1 :green_heart: |  javadoc  |   3m 20s |  the patch passed with JDK Ubuntu-11.0.10+9-Ubuntu-0ubuntu1.20.04  |
| +1 :green_heart: |  javadoc  |   2m 49s |  the patch passed with JDK Private Build-1.8.0_282-8u282-b08-0ubuntu1~20.04-b08  |
| +1 :green_heart: |  findbugs  |   9m 59s |  the patch passed  |
||| _ Other Tests _ |
| -1 :x: |  unit  |   1m 10s |  tez-ext-service-tests in the patch failed.  |
| +1 :green_heart: |  unit  |   3m  5s |  tez-aux-services in the patch passed.  |
| -1 :x: |  unit  | 164m  4s |  root in the patch failed.  |
| +1 :green_heart: |  asflicense  |   1m 11s |  The patch does not generate ASF License warnings.  |
|  |   | 256m  4s |   |


| Reason | Tests |
|-------:|:------|
| Failed junit tests | tez.tests.TestExternalTezServicesErrors |
|   | tez.tests.TestExternalTezServices |
|   | tez.test.TestMiniTezCluster |
|   | tez.test.TestAMRecovery |
|   | tez.test.TestTezJobs |
|   | tez.test.TestDAGRecovery |
|   | tez.test.TestFaultTolerance |
|   | tez.test.TestExceptionPropagation |
|   | tez.mapreduce.TestMRRJobsDAGApi |
|   | tez.mapreduce.TestMRRJobs |
|   | tez.test.TestPipelinedShuffle |
|   | tez.test.TestDAGRecovery2 |
|   | tez.tests.TestExternalTezServicesErrors |
|   | tez.tests.TestExternalTezServices |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.41 ServerAPI=1.41 base: https://ci-hadoop.apache.org/job/tez-multibranch/job/PR-118/2/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/tez/pull/118 |
| JIRA Issue | TEZ-4157 |
| Optional Tests | dupname asflicense javac javadoc unit xml compile spotbugs findbugs checkstyle |
| uname | Linux 67f4c0d01b14 4.15.0-126-generic #129-Ubuntu SMP Mon Nov 23 18:53:38 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | personality/tez.sh |
| git revision | master / aea070714 |
| Default Java | Private Build-1.8.0_282-8u282-b08-0ubuntu1~20.04-b08 |
| Multi-JDK versions | /usr/lib/jvm/java-11-openjdk-amd64:Ubuntu-11.0.10+9-Ubuntu-0ubuntu1.20.04 /usr/lib/jvm/java-8-openjdk-amd64:Private Build-1.8.0_282-8u282-b08-0ubuntu1~20.04-b08 |
| checkstyle | https://ci-hadoop.apache.org/job/tez-multibranch/job/PR-118/2/artifact/out/diff-checkstyle-tez-ext-service-tests.txt |
| checkstyle | https://ci-hadoop.apache.org/job/tez-multibranch/job/PR-118/2/artifact/out/diff-checkstyle-tez-plugins_tez-aux-services.txt |
| checkstyle | https://ci-hadoop.apache.org/job/tez-multibranch/job/PR-118/2/artifact/out/diff-checkstyle-root.txt |
| unit | https://ci-hadoop.apache.org/job/tez-multibranch/job/PR-118/2/artifact/out/patch-unit-tez-ext-service-tests.txt |
| unit | https://ci-hadoop.apache.org/job/tez-multibranch/job/PR-118/2/artifact/out/patch-unit-root.txt |
|  Test Results | https://ci-hadoop.apache.org/job/tez-multibranch/job/PR-118/2/testReport/ |
| Max. process+thread count | 1386 (vs. ulimit of 5500) |
| modules | C: tez-ext-service-tests tez-plugins/tez-aux-services . U: . |
| Console output | https://ci-hadoop.apache.org/job/tez-multibranch/job/PR-118/2/console |
| versions | git=2.25.1 maven=3.6.3 findbugs=3.0.1 |
| Powered by | Apache Yetus 0.12.0 https://yetus.apache.org |


This message was automatically generated.

**Comment by hadoop-yetus** [comment]
:confetti_ball: **+1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| +0 :ok: |  reexec  |  24m  2s |  Docker mode activated.  |
||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  0s |  No case conflicting files found.  |
| +1 :green_heart: |  @author  |   0m  0s |  The patch does not contain any @author tags.  |
| +1 :green_heart: |  test4tests  |   0m  0s |  The patch appears to include 2 new or modified test files.  |
||| _ master Compile Tests _ |
| +0 :ok: |  mvndep  |   5m 53s |  Maven dependency ordering for branch  |
| +1 :green_heart: |  mvninstall  |   8m 47s |  master passed  |
| +1 :green_heart: |  compile  |   3m  3s |  master passed with JDK Ubuntu-11.0.10+9-Ubuntu-0ubuntu1.20.04  |
| +1 :green_heart: |  compile  |   2m 43s |  master passed with JDK Private Build-1.8.0_282-8u282-b08-0ubuntu1~20.04-b08  |
| +1 :green_heart: |  checkstyle  |   1m 47s |  master passed  |
| +1 :green_heart: |  javadoc  |   2m 53s |  master passed with JDK Ubuntu-11.0.10+9-Ubuntu-0ubuntu1.20.04  |
| +1 :green_heart: |  javadoc  |   2m 18s |  master passed with JDK Private Build-1.8.0_282-8u282-b08-0ubuntu1~20.04-b08  |
| +0 :ok: |  spotbugs  |   5m 55s |  Used deprecated FindBugs config; considering switching to SpotBugs.  |
| +0 :ok: |  findbugs  |   5m 51s |  root in master has 2 extant findbugs warnings.  |
||| _ Patch Compile Tests _ |
| +0 :ok: |  mvndep  |   0m 15s |  Maven dependency ordering for patch  |
| +1 :green_heart: |  mvninstall  |   4m 44s |  the patch passed  |
| +1 :green_heart: |  compile  |   3m  6s |  the patch passed with JDK Ubuntu-11.0.10+9-Ubuntu-0ubuntu1.20.04  |
| +1 :green_heart: |  javac  |   3m  6s |  the patch passed  |
| +1 :green_heart: |  compile  |   2m 52s |  the patch passed with JDK Private Build-1.8.0_282-8u282-b08-0ubuntu1~20.04-b08  |
| +1 :green_heart: |  javac  |   2m 52s |  the patch passed  |
| -0 :warning: |  checkstyle  |   0m 17s |  tez-ext-service-tests: The patch generated 4 new + 31 unchanged - 7 fixed = 35 total (was 38)  |
| -0 :warning: |  checkstyle  |   0m 19s |  tez-plugins/tez-aux-services: The patch generated 1 new + 66 unchanged - 9 fixed = 67 total (was 75)  |
| -0 :warning: |  checkstyle  |   0m 47s |  root: The patch generated 5 new + 97 unchanged - 16 fixed = 102 total (was 113)  |
| +1 :green_heart: |  whitespace  |   0m  0s |  The patch has no whitespace issues.  |
| +1 :green_heart: |  xml  |   0m  4s |  The patch has no ill-formed XML file.  |
| +1 :green_heart: |  javadoc  |   2m 40s |  the patch passed with JDK Ubuntu-11.0.10+9-Ubuntu-0ubuntu1.20.04  |
| +1 :green_heart: |  javadoc  |   2m 16s |  the patch passed with JDK Private Build-1.8.0_282-8u282-b08-0ubuntu1~20.04-b08  |
| +1 :green_heart: |  findbugs  |   7m 32s |  the patch passed  |
||| _ Other Tests _ |
| +1 :green_heart: |  unit  |   3m 56s |  tez-ext-service-tests in the patch passed.  |
| +1 :green_heart: |  unit  |   2m 41s |  tez-aux-services in the patch passed.  |
| +1 :green_heart: |  unit  |  71m 18s |  root in the patch passed.  |
| +1 :green_heart: |  asflicense  |   1m  5s |  The patch does not generate ASF License warnings.  |
|  |   | 164m 39s |   |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.41 ServerAPI=1.41 base: https://ci-hadoop.apache.org/job/tez-multibranch/job/PR-118/3/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/tez/pull/118 |
| JIRA Issue | TEZ-4157 |
| Optional Tests | dupname asflicense javac javadoc unit xml compile spotbugs findbugs checkstyle |
| uname | Linux 5dc5fcf555cf 4.15.0-128-generic #131-Ubuntu SMP Wed Dec 9 06:57:35 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | personality/tez.sh |
| git revision | master / aea070714 |
| Default Java | Private Build-1.8.0_282-8u282-b08-0ubuntu1~20.04-b08 |
| Multi-JDK versions | /usr/lib/jvm/java-11-openjdk-amd64:Ubuntu-11.0.10+9-Ubuntu-0ubuntu1.20.04 /usr/lib/jvm/java-8-openjdk-amd64:Private Build-1.8.0_282-8u282-b08-0ubuntu1~20.04-b08 |
| checkstyle | https://ci-hadoop.apache.org/job/tez-multibranch/job/PR-118/3/artifact/out/diff-checkstyle-tez-ext-service-tests.txt |
| checkstyle | https://ci-hadoop.apache.org/job/tez-multibranch/job/PR-118/3/artifact/out/diff-checkstyle-tez-plugins_tez-aux-services.txt |
| checkstyle | https://ci-hadoop.apache.org/job/tez-multibranch/job/PR-118/3/artifact/out/diff-checkstyle-root.txt |
|  Test Results | https://ci-hadoop.apache.org/job/tez-multibranch/job/PR-118/3/testReport/ |
| Max. process+thread count | 1359 (vs. ulimit of 5500) |
| modules | C: tez-ext-service-tests tez-plugins/tez-aux-services . U: . |
| Console output | https://ci-hadoop.apache.org/job/tez-multibranch/job/PR-118/3/console |
| versions | git=2.25.1 maven=3.6.3 findbugs=3.0.1 |
| Powered by | Apache Yetus 0.12.0 https://yetus.apache.org |


This message was automatically generated.

**Comment by abstractdog** [comment]
tests passed, I included all the fixes that were done in the scope of HIVE-24524

**Pull request merged**
