### PR TITLE
TEZ-4471: Precommit fails while building yetus image

### PR DESCRIPTION
**Pull request by abstractdog**

### CODE REVIEW

**Comment by tez-yetus** [comment]
(!) A patch to the testing environment has been detected. 
Re-executing against the patched versions to perform further tests. 
The console is at https://ci-hadoop.apache.org/job/tez-multibranch/job/PR-265/1/console in case of problems.

**Comment by abstractdog** [comment]
I haven't been able to reproduce the issue locally, so simply upgraded to the next LTS ubuntu version, seems to work

**Comment by tez-yetus** [comment]
:confetti_ball: **+1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| +0 :ok: |  reexec  |  23m  0s |  Docker mode activated.  |
||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  0s |  No case conflicting files found.  |
| +0 :ok: |  shelldocs  |   0m  0s |  Shelldocs was not available.  |
| +1 :green_heart: |  @author  |   0m  0s |  The patch does not contain any @author tags.  |
||| _ master Compile Tests _ |
||| _ Patch Compile Tests _ |
| +1 :green_heart: |  hadolint  |   0m  2s |  There were no new hadolint issues.  |
| +1 :green_heart: |  shellcheck  |   0m  0s |  There were no new shellcheck issues.  |
| +1 :green_heart: |  whitespace  |   0m  0s |  The patch has no whitespace issues.  |
||| _ Other Tests _ |
| +1 :green_heart: |  asflicense  |   0m 58s |  The patch does not generate ASF License warnings.  |
|  |   |  24m 44s |   |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.42 ServerAPI=1.42 base: https://ci-hadoop.apache.org/job/tez-multibranch/job/PR-265/1/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/tez/pull/265 |
| JIRA Issue | TEZ-4471 |
| Optional Tests | dupname asflicense hadolint shellcheck shelldocs |
| uname | Linux c2272959f76b 4.15.0-200-generic #211-Ubuntu SMP Thu Nov 24 18:16:04 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | personality/tez.sh |
| git revision | master / 39e5a8e71 |
| Max. process+thread count | 51 (vs. ulimit of 5500) |
| modules | C: . U: . |
| Console output | https://ci-hadoop.apache.org/job/tez-multibranch/job/PR-265/1/console |
| versions | git=2.34.1 maven=3.6.3 shellcheck=0.7.1 hadolint=1.18.0-0-g76eee5c |
| Powered by | Apache Yetus 0.12.0 https://yetus.apache.org |


This message was automatically generated.

**Comment by tez-yetus** [comment]
(!) A patch to the testing environment has been detected. 
Re-executing against the patched versions to perform further tests. 
The console is at https://ci-hadoop.apache.org/job/tez-multibranch/job/PR-265/2/console in case of problems.

**Comment by tez-yetus** [comment]
(!) A patch to the testing environment has been detected. 
Re-executing against the patched versions to perform further tests. 
The console is at https://ci-hadoop.apache.org/job/tez-multibranch/job/PR-265/3/console in case of problems.

**Comment by tez-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| +0 :ok: |  reexec  |   0m 20s |  Docker mode activated.  |
||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  0s |  No case conflicting files found.  |
| +0 :ok: |  shelldocs  |   0m  0s |  Shelldocs was not available.  |
| +1 :green_heart: |  @author  |   0m  0s |  The patch does not contain any @author tags.  |
| -1 :x: |  test4tests  |   0m  0s |  The patch doesn't appear to include any new or modified tests. Please justify why no new tests are needed for this patch. Also please list what manual steps were performed to verify this patch.  |
||| _ master Compile Tests _ |
| -1 :x: |  mvninstall  |  13m 38s |  root in master failed.  |
| -1 :x: |  compile  |   1m 24s |  root in master failed with JDK Ubuntu-11.0.17+8-post-Ubuntu-1ubuntu222.04.  |
| -1 :x: |  compile  |   1m 16s |  root in master failed with JDK Private Build-1.8.0_352-8u352-ga-1~22.04-b08.  |
| +1 :green_heart: |  javadoc  |   2m 28s |  master passed with JDK Ubuntu-11.0.17+8-post-Ubuntu-1ubuntu222.04  |
| +1 :green_heart: |  javadoc  |   1m 45s |  master passed with JDK Private Build-1.8.0_352-8u352-ga-1~22.04-b08  |
||| _ Patch Compile Tests _ |
| -1 :x: |  mvninstall  |   3m  7s |  root in the patch failed.  |
| -1 :x: |  compile  |   1m 25s |  root in the patch failed with JDK Ubuntu-11.0.17+8-post-Ubuntu-1ubuntu222.04.  |
| -1 :x: |  javac  |   1m 25s |  root in the patch failed with JDK Ubuntu-11.0.17+8-post-Ubuntu-1ubuntu222.04.  |
| -1 :x: |  compile  |   1m 18s |  root in the patch failed with JDK Private Build-1.8.0_352-8u352-ga-1~22.04-b08.  |
| -1 :x: |  javac  |   1m 18s |  root in the patch failed with JDK Private Build-1.8.0_352-8u352-ga-1~22.04-b08.  |
| +1 :green_heart: |  hadolint  |   0m  3s |  There were no new hadolint issues.  |
| +1 :green_heart: |  shellcheck  |   0m  0s |  There were no new shellcheck issues.  |
| -1 :x: |  whitespace  |   0m  0s |  The patch has 1 line(s) that end in whitespace. Use git apply --whitespace=fix <<patch_file>>. Refer https://git-scm.com/docs/git-apply  |
| +1 :green_heart: |  xml  |   0m  1s |  The patch has no ill-formed XML file.  |
| +1 :green_heart: |  javadoc  |   2m  3s |  the patch passed with JDK Ubuntu-11.0.17+8-post-Ubuntu-1ubuntu222.04  |
| +1 :green_heart: |  javadoc  |   1m 42s |  the patch passed with JDK Private Build-1.8.0_352-8u352-ga-1~22.04-b08  |
||| _ Other Tests _ |
| -1 :x: |  unit  |  72m 26s |  root in the patch failed.  |
| +1 :green_heart: |  asflicense  |   0m 36s |  The patch does not generate ASF License warnings.  |
|  |   | 104m 33s |   |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.42 ServerAPI=1.42 base: https://ci-hadoop.apache.org/job/tez-multibranch/job/PR-265/2/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/tez/pull/265 |
| JIRA Issue | TEZ-4471 |
| Optional Tests | dupname asflicense hadolint shellcheck shelldocs javac javadoc unit xml compile |
| uname | Linux b27b3fe1e5cb 4.15.0-200-generic #211-Ubuntu SMP Thu Nov 24 18:16:04 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | personality/tez.sh |
| git revision | master / 39e5a8e71 |
| Default Java | Private Build-1.8.0_352-8u352-ga-1~22.04-b08 |
| Multi-JDK versions | /usr/lib/jvm/java-11-openjdk-amd64:Ubuntu-11.0.17+8-post-Ubuntu-1ubuntu222.04 /usr/lib/jvm/java-8-openjdk-amd64:Private Build-1.8.0_352-8u352-ga-1~22.04-b08 |
| mvninstall | https://ci-hadoop.apache.org/job/tez-multibranch/job/PR-265/2/artifact/out/branch-mvninstall-root.txt |
| compile | https://ci-hadoop.apache.org/job/tez-multibranch/job/PR-265/2/artifact/out/branch-compile-root-jdkUbuntu-11.0.17+8-post-Ubuntu-1ubuntu222.04.txt |
| compile | https://ci-hadoop.apache.org/job/tez-multibranch/job/PR-265/2/artifact/out/branch-compile-root-jdkPrivateBuild-1.8.0_352-8u352-ga-1~22.04-b08.txt |
| mvninstall | https://ci-hadoop.apache.org/job/tez-multibranch/job/PR-265/2/artifact/out/patch-mvninstall-root.txt |
| compile | https://ci-hadoop.apache.org/job/tez-multibranch/job/PR-265/2/artifact/out/patch-compile-root-jdkUbuntu-11.0.17+8-post-Ubuntu-1ubuntu222.04.txt |
| javac | https://ci-hadoop.apache.org/job/tez-multibranch/job/PR-265/2/artifact/out/patch-compile-root-jdkUbuntu-11.0.17+8-post-Ubuntu-1ubuntu222.04.txt |
| compile | https://ci-hadoop.apache.org/job/tez-multibranch/job/PR-265/2/artifact/out/patch-compile-root-jdkPrivateBuild-1.8.0_352-8u352-ga-1~22.04-b08.txt |
| javac | https://ci-hadoop.apache.org/job/tez-multibranch/job/PR-265/2/artifact/out/patch-compile-root-jdkPrivateBuild-1.8.0_352-8u352-ga-1~22.04-b08.txt |
| whitespace | https://ci-hadoop.apache.org/job/tez-multibranch/job/PR-265/2/artifact/out/whitespace-eol.txt |
| unit | https://ci-hadoop.apache.org/job/tez-multibranch/job/PR-265/2/artifact/out/patch-unit-root.txt |
|  Test Results | https://ci-hadoop.apache.org/job/tez-multibranch/job/PR-265/2/testReport/ |
| Max. process+thread count | 2100 (vs. ulimit of 5500) |
| modules | C: . U: . |
| Console output | https://ci-hadoop.apache.org/job/tez-multibranch/job/PR-265/2/console |
| versions | git=2.34.1 maven=3.6.3 shellcheck=0.7.1 hadolint=1.18.0-0-g76eee5c |
| Powered by | Apache Yetus 0.12.0 https://yetus.apache.org |


This message was automatically generated.

**Comment by tez-yetus** [comment]
:confetti_ball: **+1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| +0 :ok: |  reexec  |  25m 16s |  Docker mode activated.  |
||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  0s |  No case conflicting files found.  |
| +0 :ok: |  shelldocs  |   0m  0s |  Shelldocs was not available.  |
| +1 :green_heart: |  @author  |   0m  0s |  The patch does not contain any @author tags.  |
||| _ master Compile Tests _ |
||| _ Patch Compile Tests _ |
| +1 :green_heart: |  hadolint  |   0m  3s |  There were no new hadolint issues.  |
| +1 :green_heart: |  shellcheck  |   0m  0s |  There were no new shellcheck issues.  |
| +1 :green_heart: |  whitespace  |   0m  0s |  The patch has no whitespace issues.  |
||| _ Other Tests _ |
| +1 :green_heart: |  asflicense  |   1m  2s |  The patch does not generate ASF License warnings.  |
|  |   |  27m  6s |   |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.42 ServerAPI=1.42 base: https://ci-hadoop.apache.org/job/tez-multibranch/job/PR-265/3/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/tez/pull/265 |
| JIRA Issue | TEZ-4471 |
| Optional Tests | dupname asflicense hadolint shellcheck shelldocs |
| uname | Linux 059bb1b0866e 4.15.0-200-generic #211-Ubuntu SMP Thu Nov 24 18:16:04 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | personality/tez.sh |
| git revision | master / 39e5a8e71 |
| Max. process+thread count | 51 (vs. ulimit of 5500) |
| modules | C: . U: . |
| Console output | https://ci-hadoop.apache.org/job/tez-multibranch/job/PR-265/3/console |
| versions | git=2.34.1 maven=3.6.3 shellcheck=0.7.1 hadolint=1.18.0-0-g76eee5c |
| Powered by | Apache Yetus 0.12.0 https://yetus.apache.org |


This message was automatically generated.

**Review by ayushtkn — APPROVED** [review]
LGTM.
Anyway good to upgrade to the latest LTS release

**Comment by tez-yetus** [comment]
(!) A patch to the testing environment has been detected. 
Re-executing against the patched versions to perform further tests. 
The console is at https://ci-hadoop.apache.org/job/tez-multibranch/job/PR-265/4/console in case of problems.

**Comment by tez-yetus** [comment]
(!) A patch to the testing environment has been detected. 
Re-executing against the patched versions to perform further tests. 
The console is at https://ci-hadoop.apache.org/job/tez-multibranch/job/PR-265/5/console in case of problems.

**Comment by abstractdog** [comment]
after some hacking I realized the root cause of installation failures in tez-ui is the absence of the bzip2 package, handling it with the latest commit
https://ci-hadoop.apache.org/job/tez-multibranch/job/PR-265/2/artifact/out/patch-compile-root-jdkPrivateBuild-1.8.0_352-8u352-ga-1~22.04-b08.txt
{code}
[INFO] tar (child): bzip2: Cannot exec: No such file or directory
{code}

**Comment by ayushtkn** [comment]
So, is there any commit which added the dependency on bzip2? Just curious then why didn't it fail in that PR jenkins report

**Comment by abstractdog** [comment]
it's because tez precommit flow depends on which files have been modified, e.g. when you only change the Dockerfile, there is no full precommit run, only the docker image is built
that's why I added a fake commit to change pom.xml to run full precommit:
https://github.com/apache/tez/pull/265/commits/e87a0de11404fbe24f8775b01ffe594d6ff172fc

actually, the bzip2 change is here:
https://github.com/apache/tez/pull/265/commits/b0fce54730024915ce1a8f978d901d46c393392b

once the precommit passes, I'll simply remove the pom.xml hack

**Comment by tez-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| +0 :ok: |  reexec  |  25m  6s |  Docker mode activated.  |
||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  0s |  No case conflicting files found.  |
| +0 :ok: |  shelldocs  |   0m  0s |  Shelldocs was not available.  |
| +1 :green_heart: |  @author  |   0m  0s |  The patch does not contain any @author tags.  |
| -1 :x: |  test4tests  |   0m  0s |  The patch doesn't appear to include any new or modified tests. Please justify why no new tests are needed for this patch. Also please list what manual steps were performed to verify this patch.  |
||| _ master Compile Tests _ |
| +1 :green_heart: |  mvninstall  |  15m 58s |  master passed  |
| +1 :green_heart: |  compile  |   2m 10s |  master passed with JDK Ubuntu-11.0.17+8-post-Ubuntu-1ubuntu222.04  |
| +1 :green_heart: |  compile  |   1m 59s |  master passed with JDK Private Build-1.8.0_352-8u352-ga-1~22.04-b08  |
| +1 :green_heart: |  javadoc  |   2m 25s |  master passed with JDK Ubuntu-11.0.17+8-post-Ubuntu-1ubuntu222.04  |
| +1 :green_heart: |  javadoc  |   1m 44s |  master passed with JDK Private Build-1.8.0_352-8u352-ga-1~22.04-b08  |
||| _ Patch Compile Tests _ |
| +1 :green_heart: |  mvninstall  |   3m 52s |  the patch passed  |
| +1 :green_heart: |  compile  |   2m  9s |  the patch passed with JDK Ubuntu-11.0.17+8-post-Ubuntu-1ubuntu222.04  |
| +1 :green_heart: |  javac  |   2m  9s |  the patch passed  |
| +1 :green_heart: |  compile  |   1m 59s |  the patch passed with JDK Private Build-1.8.0_352-8u352-ga-1~22.04-b08  |
| +1 :green_heart: |  javac  |   1m 59s |  the patch passed  |
| +1 :green_heart: |  hadolint  |   0m  1s |  There were no new hadolint issues.  |
| +1 :green_heart: |  shellcheck  |   0m  0s |  There were no new shellcheck issues.  |
| -1 :x: |  whitespace  |   0m  0s |  The patch has 1 line(s) that end in whitespace. Use git apply --whitespace=fix <<patch_file>>. Refer https://git-scm.com/docs/git-apply  |
| +1 :green_heart: |  xml  |   0m  2s |  The patch has no ill-formed XML file.  |
| +1 :green_heart: |  javadoc  |   2m  4s |  the patch passed with JDK Ubuntu-11.0.17+8-post-Ubuntu-1ubuntu222.04  |
| +1 :green_heart: |  javadoc  |   1m 46s |  the patch passed with JDK Private Build-1.8.0_352-8u352-ga-1~22.04-b08  |
||| _ Other Tests _ |
| -1 :x: |  unit  |  74m 51s |  root in the patch failed.  |
| +1 :green_heart: |  asflicense  |   0m 40s |  The patch does not generate ASF License warnings.  |
|  |   | 137m 47s |   |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.42 ServerAPI=1.42 base: https://ci-hadoop.apache.org/job/tez-multibranch/job/PR-265/5/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/tez/pull/265 |
| JIRA Issue | TEZ-4471 |
| Optional Tests | dupname asflicense hadolint shellcheck shelldocs javac javadoc unit xml compile |
| uname | Linux 9c49d59641ce 4.15.0-200-generic #211-Ubuntu SMP Thu Nov 24 18:16:04 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | personality/tez.sh |
| git revision | master / 39e5a8e71 |
| Default Java | Private Build-1.8.0_352-8u352-ga-1~22.04-b08 |
| Multi-JDK versions | /usr/lib/jvm/java-11-openjdk-amd64:Ubuntu-11.0.17+8-post-Ubuntu-1ubuntu222.04 /usr/lib/jvm/java-8-openjdk-amd64:Private Build-1.8.0_352-8u352-ga-1~22.04-b08 |
| whitespace | https://ci-hadoop.apache.org/job/tez-multibranch/job/PR-265/5/artifact/out/whitespace-eol.txt |
| unit | https://ci-hadoop.apache.org/job/tez-multibranch/job/PR-265/5/artifact/out/patch-unit-root.txt |
|  Test Results | https://ci-hadoop.apache.org/job/tez-multibranch/job/PR-265/5/testReport/ |
| Max. process+thread count | 2100 (vs. ulimit of 5500) |
| modules | C: . U: . |
| Console output | https://ci-hadoop.apache.org/job/tez-multibranch/job/PR-265/5/console |
| versions | git=2.34.1 maven=3.6.3 shellcheck=0.7.1 hadolint=1.18.0-0-g76eee5c |
| Powered by | Apache Yetus 0.12.0 https://yetus.apache.org |


This message was automatically generated.

**Comment by tez-yetus** [comment]
(!) A patch to the testing environment has been detected. 
Re-executing against the patched versions to perform further tests. 
The console is at https://ci-hadoop.apache.org/job/tez-multibranch/job/PR-265/6/console in case of problems.

**Comment by tez-yetus** [comment]
(!) A patch to the testing environment has been detected. 
Re-executing against the patched versions to perform further tests. 
The console is at https://ci-hadoop.apache.org/job/tez-multibranch/job/PR-265/7/console in case of problems.

**Comment by tez-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| +0 :ok: |  reexec  |  22m 47s |  Docker mode activated.  |
||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  0s |  No case conflicting files found.  |
| +0 :ok: |  shelldocs  |   0m  0s |  Shelldocs was not available.  |
| +1 :green_heart: |  @author  |   0m  0s |  The patch does not contain any @author tags.  |
| -1 :x: |  test4tests  |   0m  0s |  The patch doesn't appear to include any new or modified tests. Please justify why no new tests are needed for this patch. Also please list what manual steps were performed to verify this patch.  |
||| _ master Compile Tests _ |
| +0 :ok: |  mvndep  |   5m 50s |  Maven dependency ordering for branch  |
| +1 :green_heart: |  mvninstall  |  10m 43s |  master passed  |
| +1 :green_heart: |  compile  |   2m 57s |  master passed with JDK Ubuntu-11.0.17+8-post-Ubuntu-1ubuntu222.04  |
| +1 :green_heart: |  compile  |   2m 46s |  master passed with JDK Private Build-1.8.0_352-8u352-ga-1~22.04-b08  |
| +1 :green_heart: |  javadoc  |   2m 38s |  master passed with JDK Ubuntu-11.0.17+8-post-Ubuntu-1ubuntu222.04  |
| +1 :green_heart: |  javadoc  |   2m  6s |  master passed with JDK Private Build-1.8.0_352-8u352-ga-1~22.04-b08  |
||| _ Patch Compile Tests _ |
| +0 :ok: |  mvndep  |   0m 10s |  Maven dependency ordering for patch  |
| +1 :green_heart: |  mvninstall  |   4m 39s |  the patch passed  |
| +1 :green_heart: |  compile  |   2m 59s |  the patch passed with JDK Ubuntu-11.0.17+8-post-Ubuntu-1ubuntu222.04  |
| +1 :green_heart: |  javac  |   2m 59s |  the patch passed  |
| +1 :green_heart: |  compile  |   2m 45s |  the patch passed with JDK Private Build-1.8.0_352-8u352-ga-1~22.04-b08  |
| +1 :green_heart: |  javac  |   2m 45s |  the patch passed  |
| +1 :green_heart: |  hadolint  |   0m  2s |  There were no new hadolint issues.  |
| +1 :green_heart: |  shellcheck  |   0m  0s |  There were no new shellcheck issues.  |
| +1 :green_heart: |  whitespace  |   0m  0s |  The patch has no whitespace issues.  |
| +1 :green_heart: |  xml  |   0m  1s |  The patch has no ill-formed XML file.  |
| +1 :green_heart: |  javadoc  |   2m 26s |  the patch passed with JDK Ubuntu-11.0.17+8-post-Ubuntu-1ubuntu222.04  |
| +1 :green_heart: |  javadoc  |   2m  8s |  the patch passed with JDK Private Build-1.8.0_352-8u352-ga-1~22.04-b08  |
||| _ Other Tests _ |
| +1 :green_heart: |  unit  |   1m 35s |  tez-ui in the patch passed.  |
| +1 :green_heart: |  unit  |  70m  6s |  root in the patch passed.  |
| +1 :green_heart: |  asflicense  |   1m  6s |  The patch does not generate ASF License warnings.  |
|  |   | 138m 58s |   |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.42 ServerAPI=1.42 base: https://ci-hadoop.apache.org/job/tez-multibranch/job/PR-265/6/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/tez/pull/265 |
| JIRA Issue | TEZ-4471 |
| Optional Tests | dupname asflicense hadolint shellcheck shelldocs javac javadoc unit xml compile |
| uname | Linux a3ccd766fff2 4.15.0-200-generic #211-Ubuntu SMP Thu Nov 24 18:16:04 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | personality/tez.sh |
| git revision | master / 39e5a8e71 |
| Default Java | Private Build-1.8.0_352-8u352-ga-1~22.04-b08 |
| Multi-JDK versions | /usr/lib/jvm/java-11-openjdk-amd64:Ubuntu-11.0.17+8-post-Ubuntu-1ubuntu222.04 /usr/lib/jvm/java-8-openjdk-amd64:Private Build-1.8.0_352-8u352-ga-1~22.04-b08 |
|  Test Results | https://ci-hadoop.apache.org/job/tez-multibranch/job/PR-265/6/testReport/ |
| Max. process+thread count | 2100 (vs. ulimit of 5500) |
| modules | C: tez-ui . U: . |
| Console output | https://ci-hadoop.apache.org/job/tez-multibranch/job/PR-265/6/console |
| versions | git=2.34.1 maven=3.6.3 shellcheck=0.7.1 hadolint=1.18.0-0-g76eee5c |
| Powered by | Apache Yetus 0.12.0 https://yetus.apache.org |


This message was automatically generated.

**Comment by tez-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| +0 :ok: |  reexec  |   0m 39s |  Docker mode activated.  |
||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  0s |  No case conflicting files found.  |
| +0 :ok: |  shelldocs  |   0m  0s |  Shelldocs was not available.  |
| +1 :green_heart: |  @author  |   0m  0s |  The patch does not contain any @author tags.  |
| -1 :x: |  test4tests  |   0m  0s |  The patch doesn't appear to include any new or modified tests. Please justify why no new tests are needed for this patch. Also please list what manual steps were performed to verify this patch.  |
||| _ master Compile Tests _ |
| +0 :ok: |  mvndep  |   5m 57s |  Maven dependency ordering for branch  |
| +1 :green_heart: |  mvninstall  |  10m 41s |  master passed  |
| +1 :green_heart: |  compile  |   2m 57s |  master passed with JDK Ubuntu-11.0.17+8-post-Ubuntu-1ubuntu222.04  |
| +1 :green_heart: |  compile  |   2m 48s |  master passed with JDK Private Build-1.8.0_352-8u352-ga-1~22.04-b08  |
| +1 :green_heart: |  javadoc  |   2m 39s |  master passed with JDK Ubuntu-11.0.17+8-post-Ubuntu-1ubuntu222.04  |
| +1 :green_heart: |  javadoc  |   2m  7s |  master passed with JDK Private Build-1.8.0_352-8u352-ga-1~22.04-b08  |
||| _ Patch Compile Tests _ |
| +0 :ok: |  mvndep  |   0m 10s |  Maven dependency ordering for patch  |
| +1 :green_heart: |  mvninstall  |   4m 38s |  the patch passed  |
| +1 :green_heart: |  compile  |   2m 55s |  the patch passed with JDK Ubuntu-11.0.17+8-post-Ubuntu-1ubuntu222.04  |
| +1 :green_heart: |  javac  |   2m 55s |  the patch passed  |
| +1 :green_heart: |  compile  |   2m 48s |  the patch passed with JDK Private Build-1.8.0_352-8u352-ga-1~22.04-b08  |
| +1 :green_heart: |  javac  |   2m 48s |  the patch passed  |
| +1 :green_heart: |  hadolint  |   0m  3s |  There were no new hadolint issues.  |
| +1 :green_heart: |  shellcheck  |   0m  0s |  There were no new shellcheck issues.  |
| +1 :green_heart: |  whitespace  |   0m  0s |  The patch has no whitespace issues.  |
| +1 :green_heart: |  xml  |   0m  2s |  The patch has no ill-formed XML file.  |
| +1 :green_heart: |  javadoc  |   2m 27s |  the patch passed with JDK Ubuntu-11.0.17+8-post-Ubuntu-1ubuntu222.04  |
| +1 :green_heart: |  javadoc  |   2m  5s |  the patch passed with JDK Private Build-1.8.0_352-8u352-ga-1~22.04-b08  |
||| _ Other Tests _ |
| +1 :green_heart: |  unit  |   1m 37s |  tez-ui in the patch passed.  |
| +1 :green_heart: |  unit  |  75m 16s |  root in the patch passed.  |
| +1 :green_heart: |  asflicense  |   1m  5s |  The patch does not generate ASF License warnings.  |
|  |   | 122m  1s |   |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.42 ServerAPI=1.42 base: https://ci-hadoop.apache.org/job/tez-multibranch/job/PR-265/7/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/tez/pull/265 |
| JIRA Issue | TEZ-4471 |
| Optional Tests | dupname asflicense hadolint shellcheck shelldocs javac javadoc unit xml compile |
| uname | Linux 3eb61d42993a 4.15.0-200-generic #211-Ubuntu SMP Thu Nov 24 18:16:04 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | personality/tez.sh |
| git revision | master / 39e5a8e71 |
| Default Java | Private Build-1.8.0_352-8u352-ga-1~22.04-b08 |
| Multi-JDK versions | /usr/lib/jvm/java-11-openjdk-amd64:Ubuntu-11.0.17+8-post-Ubuntu-1ubuntu222.04 /usr/lib/jvm/java-8-openjdk-amd64:Private Build-1.8.0_352-8u352-ga-1~22.04-b08 |
|  Test Results | https://ci-hadoop.apache.org/job/tez-multibranch/job/PR-265/7/testReport/ |
| Max. process+thread count | 2100 (vs. ulimit of 5500) |
| modules | C: tez-ui . U: . |
| Console output | https://ci-hadoop.apache.org/job/tez-multibranch/job/PR-265/7/console |
| versions | git=2.34.1 maven=3.6.3 shellcheck=0.7.1 hadolint=1.18.0-0-g76eee5c |
| Powered by | Apache Yetus 0.12.0 https://yetus.apache.org |


This message was automatically generated.

**Comment by abstractdog** [comment]
okay, latest precommit passed, I'm about to proceed with it tomorrow

**Comment by rbalamohan** [comment]
LGTM +1

**Review by rbalamohan — APPROVED** [review]

**Pull request merged**
