### PR TITLE
TEZ-4496: Tez precommit fails while building yetus image - no alternatives for some executables

### PR DESCRIPTION
**Pull request by abstractdog**

### CODE REVIEW

**Comment by tez-yetus** [comment]
(!) A patch to the testing environment has been detected. 
Re-executing against the patched versions to perform further tests. 
The console is at https://ci-hadoop.apache.org/job/tez-multibranch/job/PR-289/1/console in case of problems.

**Comment by tez-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| +0 :ok: |  reexec  |   0m  0s |  Docker mode activated.  |
| -1 :x: |  docker  |   1m 45s |  Docker failed to build yetus/tez:e236f51ef.  |


| Subsystem | Report/Notes |
|----------:|:-------------|
| GITHUB PR | https://github.com/apache/tez/pull/289 |
| JIRA Issue | TEZ-4496 |
| Console output | https://ci-hadoop.apache.org/job/tez-multibranch/job/PR-289/2/console |
| versions | git=2.17.1 |
| Powered by | Apache Yetus 0.12.0 https://yetus.apache.org |


This message was automatically generated.

**Comment by tez-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| +0 :ok: |  reexec  |   0m  0s |  Docker mode activated.  |
| -1 :x: |  docker  |   3m 15s |  Docker failed to build yetus/tez:e236f51ef.  |


| Subsystem | Report/Notes |
|----------:|:-------------|
| GITHUB PR | https://github.com/apache/tez/pull/289 |
| JIRA Issue | TEZ-4496 |
| Console output | https://ci-hadoop.apache.org/job/tez-multibranch/job/PR-289/1/console |
| versions | git=2.17.1 |
| Powered by | Apache Yetus 0.12.0 https://yetus.apache.org |


This message was automatically generated.

**Comment by abstractdog** [comment]
need to merge this to unblock precommit

**Pull request merged**
