### PR TITLE
TEZ-4323: Jetty jars were removed from dist package with TEZ-4114

### PR DESCRIPTION
**Pull request by tasanuma**

### CODE REVIEW

**Comment by hadoop-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| +0 :ok: |  reexec  |  16m 18s |  Docker mode activated.  |
||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  0s |  No case conflicting files found.  |
| +1 :green_heart: |  @author  |   0m  0s |  The patch does not contain any @author tags.  |
| -1 :x: |  test4tests  |   0m  0s |  The patch doesn't appear to include any new or modified tests. Please justify why no new tests are needed for this patch. Also please list what manual steps were performed to verify this patch.  |
||| _ master Compile Tests _ |
| +1 :green_heart: |  mvninstall  |  12m 42s |  master passed  |
| +1 :green_heart: |  compile  |   2m 17s |  master passed with JDK Ubuntu-11.0.11+9-Ubuntu-0ubuntu2.20.04  |
| +1 :green_heart: |  compile  |   2m  2s |  master passed with JDK Private Build-1.8.0_292-8u292-b10-0ubuntu1~20.04-b10  |
| +1 :green_heart: |  javadoc  |   2m 17s |  master passed with JDK Ubuntu-11.0.11+9-Ubuntu-0ubuntu2.20.04  |
| +1 :green_heart: |  javadoc  |   1m 37s |  master passed with JDK Private Build-1.8.0_292-8u292-b10-0ubuntu1~20.04-b10  |
||| _ Patch Compile Tests _ |
| +1 :green_heart: |  mvninstall  |   4m  3s |  the patch passed  |
| +1 :green_heart: |  compile  |   2m 16s |  the patch passed with JDK Ubuntu-11.0.11+9-Ubuntu-0ubuntu2.20.04  |
| +1 :green_heart: |  javac  |   2m 16s |  the patch passed  |
| +1 :green_heart: |  compile  |   2m  5s |  the patch passed with JDK Private Build-1.8.0_292-8u292-b10-0ubuntu1~20.04-b10  |
| +1 :green_heart: |  javac  |   2m  5s |  the patch passed  |
| +1 :green_heart: |  whitespace  |   0m  0s |  The patch has no whitespace issues.  |
| +1 :green_heart: |  xml  |   0m  2s |  The patch has no ill-formed XML file.  |
| +1 :green_heart: |  javadoc  |   1m 58s |  the patch passed with JDK Ubuntu-11.0.11+9-Ubuntu-0ubuntu2.20.04  |
| +1 :green_heart: |  javadoc  |   1m 35s |  the patch passed with JDK Private Build-1.8.0_292-8u292-b10-0ubuntu1~20.04-b10  |
||| _ Other Tests _ |
| +1 :green_heart: |  unit  |  71m 36s |  root in the patch passed.  |
| +1 :green_heart: |  asflicense  |   0m 32s |  The patch does not generate ASF License warnings.  |
|  |   | 122m 18s |   |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.41 ServerAPI=1.41 base: https://ci-hadoop.apache.org/job/tez-multibranch/job/PR-140/1/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/tez/pull/140 |
| JIRA Issue | TEZ-4323 |
| Optional Tests | dupname asflicense javac javadoc unit xml compile |
| uname | Linux 4cc28be894d9 4.15.0-128-generic #131-Ubuntu SMP Wed Dec 9 06:57:35 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | personality/tez.sh |
| git revision | master / 464d86d8f |
| Default Java | Private Build-1.8.0_292-8u292-b10-0ubuntu1~20.04-b10 |
| Multi-JDK versions | /usr/lib/jvm/java-11-openjdk-amd64:Ubuntu-11.0.11+9-Ubuntu-0ubuntu2.20.04 /usr/lib/jvm/java-8-openjdk-amd64:Private Build-1.8.0_292-8u292-b10-0ubuntu1~20.04-b10 |
|  Test Results | https://ci-hadoop.apache.org/job/tez-multibranch/job/PR-140/1/testReport/ |
| Max. process+thread count | 2010 (vs. ulimit of 5500) |
| modules | C: . U: . |
| Console output | https://ci-hadoop.apache.org/job/tez-multibranch/job/PR-140/1/console |
| versions | git=2.25.1 maven=3.6.3 |
| Powered by | Apache Yetus 0.12.0 https://yetus.apache.org |


This message was automatically generated.

**Comment by tez-yetus** [comment]
+1. Looks good. Is there anything else to do with this jira before it is merged?

**Comment by tasanuma** [comment]
I confirmed that the version of the generated jetty jars is the same of hadoop's jetty version.

```
# jetty version in Hadoop-3.2.2 is 9.4.20.v20190813

$ mvn clean package -DskipTests -Dmaven.javadoc.skip=true
...

find tez-dist/target | grep jetty
tez-dist/target/tez-0.10.2-SNAPSHOT/lib/jetty-io-9.4.20.v20190813.jar
tez-dist/target/tez-0.10.2-SNAPSHOT/lib/jetty-util-9.4.20.v20190813.jar
tez-dist/target/tez-0.10.2-SNAPSHOT/lib/jetty-server-9.4.20.v20190813.jar
tez-dist/target/tez-0.10.2-SNAPSHOT/lib/jetty-webapp-9.4.20.v20190813.jar
tez-dist/target/tez-0.10.2-SNAPSHOT/lib/jetty-http-9.4.20.v20190813.jar
tez-dist/target/tez-0.10.2-SNAPSHOT/lib/jetty-xml-9.4.20.v20190813.jar
tez-dist/target/tez-0.10.2-SNAPSHOT/lib/jetty-security-9.4.20.v20190813.jar
tez-dist/target/tez-0.10.2-SNAPSHOT/lib/jetty-servlet-9.4.20.v20190813.jar
```

```
# jetty version in Hadoop-3.3.1 is 9.4.40.v20210413

$ mvn clean package -Dhadoop.version=3.3.1 -DskipTests -Dmaven.javadoc.skip=true
...

find tez-dist/target | grep jetty
tez-dist/target/tez-0.10.2-SNAPSHOT/lib/jetty-util-ajax-9.4.40.v20210413.jar
tez-dist/target/tez-0.10.2-SNAPSHOT/lib/jetty-webapp-9.4.40.v20210413.jar
tez-dist/target/tez-0.10.2-SNAPSHOT/lib/jetty-io-9.4.40.v20210413.jar
tez-dist/target/tez-0.10.2-SNAPSHOT/lib/jetty-server-9.4.40.v20210413.jar
tez-dist/target/tez-0.10.2-SNAPSHOT/lib/jetty-util-9.4.40.v20210413.jar
tez-dist/target/tez-0.10.2-SNAPSHOT/lib/jetty-servlet-9.4.40.v20210413.jar
tez-dist/target/tez-0.10.2-SNAPSHOT/lib/jetty-http-9.4.40.v20210413.jar
tez-dist/target/tez-0.10.2-SNAPSHOT/lib/jetty-client-9.4.40.v20210413.jar
tez-dist/target/tez-0.10.2-SNAPSHOT/lib/jetty-xml-9.4.40.v20210413.jar
tez-dist/target/tez-0.10.2-SNAPSHOT/lib/jetty-security-9.4.40.v20210413.jar
```

**Comment by tasanuma** [comment]
@abstractdog Could you review this PR?

**Comment by abstractdog** [comment]
looks good, merged to master
thanks @tasanuma for the patch!

**Comment by tasanuma** [comment]
Thanks for your review!

**Pull request merged**
