### PR TITLE
TEZ-4276: Clean Up Use of Preconditions

### PR DESCRIPTION
**Pull request by belugabehr**

### CODE REVIEW

**Comment by abstractdog** [comment]
basically, I like the idea of using java features instead of third-party methods, could you please rebase and squash @belugabehr ?

**Comment by belugabehr** [comment]
@abstractdog Good to go :)

**Comment by tez-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| +0 :ok: |  reexec  |  12m 44s |  Docker mode activated.  |
||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  1s |  No case conflicting files found.  |
| +1 :green_heart: |  @author  |   0m  0s |  The patch does not contain any @author tags.  |
| -1 :x: |  test4tests  |   0m  0s |  The patch doesn't appear to include any new or modified tests. Please justify why no new tests are needed for this patch. Also please list what manual steps were performed to verify this patch.  |
||| _ master Compile Tests _ |
| +0 :ok: |  mvndep  |   4m 22s |  Maven dependency ordering for branch  |
| +1 :green_heart: |  mvninstall  |   9m 28s |  master passed  |
| +1 :green_heart: |  compile  |   4m 13s |  master passed with JDK Ubuntu-11.0.13+8-Ubuntu-0ubuntu1.20.04  |
| +1 :green_heart: |  compile  |   4m  4s |  master passed with JDK Private Build-1.8.0_312-8u312-b07-0ubuntu1~20.04-b07  |
| +1 :green_heart: |  checkstyle  |   3m 38s |  master passed  |
| +1 :green_heart: |  javadoc  |   4m  2s |  master passed with JDK Ubuntu-11.0.13+8-Ubuntu-0ubuntu1.20.04  |
| +1 :green_heart: |  javadoc  |   3m 44s |  master passed with JDK Private Build-1.8.0_312-8u312-b07-0ubuntu1~20.04-b07  |
| +0 :ok: |  spotbugs  |   0m 47s |  Used deprecated FindBugs config; considering switching to SpotBugs.  |
| +0 :ok: |  findbugs  |   0m 45s |  tez-tools/analyzers/job-analyzer in master has 4 extant findbugs warnings.  |
||| _ Patch Compile Tests _ |
| +0 :ok: |  mvndep  |   0m  9s |  Maven dependency ordering for patch  |
| +1 :green_heart: |  mvninstall  |   2m 53s |  the patch passed  |
| +1 :green_heart: |  compile  |   2m 52s |  the patch passed with JDK Ubuntu-11.0.13+8-Ubuntu-0ubuntu1.20.04  |
| +1 :green_heart: |  javac  |   2m 52s |  the patch passed  |
| +1 :green_heart: |  compile  |   2m 30s |  the patch passed with JDK Private Build-1.8.0_312-8u312-b07-0ubuntu1~20.04-b07  |
| +1 :green_heart: |  javac  |   2m 30s |  the patch passed  |
| +1 :green_heart: |  checkstyle  |   0m 15s |  tez-api: The patch generated 0 new + 80 unchanged - 1 fixed = 80 total (was 81)  |
| +1 :green_heart: |  checkstyle  |   0m 10s |  The patch passed checkstyle in tez-common  |
| +1 :green_heart: |  checkstyle  |   0m 10s |  The patch passed checkstyle in tez-runtime-internals  |
| +1 :green_heart: |  checkstyle  |   0m 19s |  The patch passed checkstyle in tez-runtime-library  |
| +1 :green_heart: |  checkstyle  |   0m 13s |  The patch passed checkstyle in tez-mapreduce  |
| +1 :green_heart: |  checkstyle  |   0m 19s |  The patch passed checkstyle in tez-dag  |
| +1 :green_heart: |  checkstyle  |   0m 11s |  The patch passed checkstyle in tez-history-parser  |
| +1 :green_heart: |  checkstyle  |   0m 10s |  The patch passed checkstyle in job-analyzer  |
| +1 :green_heart: |  whitespace  |   0m  0s |  The patch has no whitespace issues.  |
| +1 :green_heart: |  javadoc  |   2m 21s |  the patch passed with JDK Ubuntu-11.0.13+8-Ubuntu-0ubuntu1.20.04  |
| +1 :green_heart: |  javadoc  |   2m  8s |  the patch passed with JDK Private Build-1.8.0_312-8u312-b07-0ubuntu1~20.04-b07  |
| +1 :green_heart: |  findbugs  |   6m 25s |  the patch passed  |
||| _ Other Tests _ |
| +1 :green_heart: |  unit  |   1m 59s |  tez-api in the patch passed.  |
| +1 :green_heart: |  unit  |   0m 28s |  tez-common in the patch passed.  |
| +1 :green_heart: |  unit  |   0m 34s |  tez-runtime-internals in the patch passed.  |
| +1 :green_heart: |  unit  |   5m 21s |  tez-runtime-library in the patch passed.  |
| +1 :green_heart: |  unit  |   1m 15s |  tez-mapreduce in the patch passed.  |
| +1 :green_heart: |  unit  |   4m 22s |  tez-dag in the patch passed.  |
| +1 :green_heart: |  unit  |   2m 21s |  tez-history-parser in the patch passed.  |
| -1 :x: |  unit  |  11m 26s |  job-analyzer in the patch failed.  |
| +1 :green_heart: |  asflicense  |   1m 12s |  The patch does not generate ASF License warnings.  |
|  |   | 106m 33s |   |


| Reason | Tests |
|-------:|:------|
| Failed junit tests | tez.analyzer.TestAnalyzer |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.41 ServerAPI=1.41 base: https://ci-hadoop.apache.org/job/tez-multibranch/job/PR-96/4/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/tez/pull/96 |
| JIRA Issue | TEZ-4276 |
| Optional Tests | dupname asflicense javac javadoc unit spotbugs findbugs checkstyle compile |
| uname | Linux e0d7db9ff89d 4.15.0-156-generic #163-Ubuntu SMP Thu Aug 19 23:31:58 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | personality/tez.sh |
| git revision | master / c9b8e90db |
| Default Java | Private Build-1.8.0_312-8u312-b07-0ubuntu1~20.04-b07 |
| Multi-JDK versions | /usr/lib/jvm/java-11-openjdk-amd64:Ubuntu-11.0.13+8-Ubuntu-0ubuntu1.20.04 /usr/lib/jvm/java-8-openjdk-amd64:Private Build-1.8.0_312-8u312-b07-0ubuntu1~20.04-b07 |
| unit | https://ci-hadoop.apache.org/job/tez-multibranch/job/PR-96/4/artifact/out/patch-unit-tez-tools_analyzers_job-analyzer.txt |
|  Test Results | https://ci-hadoop.apache.org/job/tez-multibranch/job/PR-96/4/testReport/ |
| Max. process+thread count | 2099 (vs. ulimit of 5500) |
| modules | C: tez-api tez-common tez-runtime-internals tez-runtime-library tez-mapreduce tez-dag tez-plugins/tez-history-parser tez-tools/analyzers/job-analyzer U: . |
| Console output | https://ci-hadoop.apache.org/job/tez-multibranch/job/PR-96/4/console |
| versions | git=2.25.1 maven=3.6.3 findbugs=3.0.1 |
| Powered by | Apache Yetus 0.12.0 https://yetus.apache.org |


This message was automatically generated.

**Comment by abstractdog** [comment]
thanks @belugabehr, can you please check if TestAnalyzer failure is related/reproducible?

**Review by abstractdog — APPROVED** [review]

**Comment by abstractdog** [comment]
merged to master, thanks @belugabehr for the patch!

**Pull request merged**
