### PR TITLE
TEZ-4492 : Approach 2 :  Disable strict-ssl for Bower and Yarn Registry to avoid Registry CERT_EXPIRE issue

### PR DESCRIPTION
**Pull request by AnmolSun**

### CODE REVIEW

**Comment by tez-yetus** [comment]
:confetti_ball: **+1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| +0 :ok: |  reexec  |   0m 48s |  Docker mode activated.  |
||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  0s |  No case conflicting files found.  |
| +1 :green_heart: |  @author  |   0m  0s |  The patch does not contain any @author tags.  |
||| _ master Compile Tests _ |
||| _ Patch Compile Tests _ |
| +1 :green_heart: |  whitespace  |   0m  0s |  The patch has no whitespace issues.  |
||| _ Other Tests _ |
| +1 :green_heart: |  asflicense  |   0m 53s |  The patch does not generate ASF License warnings.  |
|  |   |   2m 20s |   |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.42 ServerAPI=1.42 base: https://ci-hadoop.apache.org/job/tez-multibranch/job/PR-283/1/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/tez/pull/283 |
| Optional Tests | dupname asflicense |
| uname | Linux 6dc5516257f5 4.15.0-206-generic #217-Ubuntu SMP Fri Feb 3 19:10:13 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | personality/tez.sh |
| git revision | master / 249e017b3 |
| Max. process+thread count | 46 (vs. ulimit of 5500) |
| modules | C: tez-ui U: tez-ui |
| Console output | https://ci-hadoop.apache.org/job/tez-multibranch/job/PR-283/1/console |
| versions | git=2.34.1 maven=3.6.3 |
| Powered by | Apache Yetus 0.12.0 https://yetus.apache.org |


This message was automatically generated.

**Comment by tez-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| +0 :ok: |  reexec  |   0m 30s |  Docker mode activated.  |
||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  0s |  No case conflicting files found.  |
| +1 :green_heart: |  @author  |   0m  0s |  The patch does not contain any @author tags.  |
||| _ master Compile Tests _ |
||| _ Patch Compile Tests _ |
| +1 :green_heart: |  whitespace  |   0m  0s |  The patch has no whitespace issues.  |
||| _ Other Tests _ |
| -1 :x: |  asflicense  |   0m 52s |  The patch generated 1 ASF License warnings.  |
|  |   |   2m  0s |   |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.42 ServerAPI=1.42 base: https://ci-hadoop.apache.org/job/tez-multibranch/job/PR-283/2/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/tez/pull/283 |
| Optional Tests | dupname asflicense |
| uname | Linux b0b6f8443503 4.15.0-206-generic #217-Ubuntu SMP Fri Feb 3 19:10:13 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | personality/tez.sh |
| git revision | master / 249e017b3 |
| asflicense | https://ci-hadoop.apache.org/job/tez-multibranch/job/PR-283/2/artifact/out/patch-asflicense-problems.txt |
| Max. process+thread count | 46 (vs. ulimit of 5500) |
| modules | C: tez-ui U: tez-ui |
| Console output | https://ci-hadoop.apache.org/job/tez-multibranch/job/PR-283/2/console |
| versions | git=2.34.1 maven=3.6.3 |
| Powered by | Apache Yetus 0.12.0 https://yetus.apache.org |


This message was automatically generated.

**Comment by tez-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| +0 :ok: |  reexec  |   0m 30s |  Docker mode activated.  |
||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  0s |  No case conflicting files found.  |
| +1 :green_heart: |  @author  |   0m  0s |  The patch does not contain any @author tags.  |
||| _ master Compile Tests _ |
||| _ Patch Compile Tests _ |
| +1 :green_heart: |  whitespace  |   0m  0s |  The patch has no whitespace issues.  |
||| _ Other Tests _ |
| -1 :x: |  asflicense  |   0m 51s |  The patch generated 1 ASF License warnings.  |
|  |   |   1m 59s |   |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.42 ServerAPI=1.42 base: https://ci-hadoop.apache.org/job/tez-multibranch/job/PR-283/3/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/tez/pull/283 |
| Optional Tests | dupname asflicense |
| uname | Linux 1d06b2d921c8 4.15.0-206-generic #217-Ubuntu SMP Fri Feb 3 19:10:13 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | personality/tez.sh |
| git revision | master / 249e017b3 |
| asflicense | https://ci-hadoop.apache.org/job/tez-multibranch/job/PR-283/3/artifact/out/patch-asflicense-problems.txt |
| Max. process+thread count | 46 (vs. ulimit of 5500) |
| modules | C: tez-ui U: tez-ui |
| Console output | https://ci-hadoop.apache.org/job/tez-multibranch/job/PR-283/3/console |
| versions | git=2.34.1 maven=3.6.3 |
| Powered by | Apache Yetus 0.12.0 https://yetus.apache.org |


This message was automatically generated.

**Comment by tez-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| +0 :ok: |  reexec  |  27m 16s |  Docker mode activated.  |
||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  0s |  No case conflicting files found.  |
| +1 :green_heart: |  @author  |   0m  0s |  The patch does not contain any @author tags.  |
||| _ master Compile Tests _ |
||| _ Patch Compile Tests _ |
| +1 :green_heart: |  whitespace  |   0m  0s |  The patch has no whitespace issues.  |
||| _ Other Tests _ |
| -1 :x: |  asflicense  |   0m 53s |  The patch generated 1 ASF License warnings.  |
|  |   |  28m 49s |   |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.42 ServerAPI=1.42 base: https://ci-hadoop.apache.org/job/tez-multibranch/job/PR-283/4/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/tez/pull/283 |
| Optional Tests | dupname asflicense |
| uname | Linux 8286fe8bfd12 4.15.0-206-generic #217-Ubuntu SMP Fri Feb 3 19:10:13 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | personality/tez.sh |
| git revision | master / 249e017b3 |
| asflicense | https://ci-hadoop.apache.org/job/tez-multibranch/job/PR-283/4/artifact/out/patch-asflicense-problems.txt |
| Max. process+thread count | 51 (vs. ulimit of 5500) |
| modules | C: tez-ui U: tez-ui |
| Console output | https://ci-hadoop.apache.org/job/tez-multibranch/job/PR-283/4/console |
| versions | git=2.34.1 maven=3.6.3 |
| Powered by | Apache Yetus 0.12.0 https://yetus.apache.org |


This message was automatically generated.

**Comment by abstractdog** [comment]
solved by https://github.com/apache/tez/pull/284

**Pull request closed without merging**
