### PR TITLE
TEZ-4428: Use protoc-jar-maven-plugin to generate protobuf classes

### PR DESCRIPTION
**Pull request by mbathori-cloudera**
Replace the current protobuf handler plugin with `protoc-jar-maven-plugin`. The plugin handles the platform detection, binary download and execution with the provided protoc version. Because of that all the custom scriptd can be removed which were handling these tasks (`install-protobuf.sh` etc).
The plugin also supports the use of other already installed versions of protoc in the system. It can be configured through the PROTOC_PATH environment variable or by using -Dprotoc.path parameter during build.

Based on [this](https://github.com/os72/protoc-jar-maven-plugin/blob/master/src/main/java/com/github/os72/protocjar/maven/ProtocJarMojo.java#L456) if there is no `protoCommand` provided then the plugin will download the protoc binary with version provided in `${protobuf.version}`, otherwise it will use the external protoc on the provided path.

### CODE REVIEW

**Review by slachiewicz — APPROVED** [review]

**Comment by tez-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| +0 :ok: |  reexec  |   9m 10s |  Docker mode activated.  |
||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  0s |  No case conflicting files found.  |
| +0 :ok: |  shelldocs  |   0m  0s |  Shelldocs was not available.  |
| +1 :green_heart: |  @author  |   0m  0s |  The patch does not contain any @author tags.  |
| -1 :x: |  test4tests  |   0m  0s |  The patch doesn't appear to include any new or modified tests. Please justify why no new tests are needed for this patch. Also please list what manual steps were performed to verify this patch.  |
||| _ master Compile Tests _ |
| +0 :ok: |  mvndep  |   7m  1s |  Maven dependency ordering for branch  |
| -1 :x: |  mvninstall  |   6m 12s |  root in master failed.  |
| -1 :x: |  compile  |   0m 37s |  tez-api in master failed with JDK Private Build-11.0.15+10-Ubuntu-0ubuntu0.20.04.1.  |
| -1 :x: |  compile  |   0m 42s |  tez-runtime-internals in master failed with JDK Private Build-11.0.15+10-Ubuntu-0ubuntu0.20.04.1.  |
| -1 :x: |  compile  |   0m 35s |  tez-runtime-library in master failed with JDK Private Build-11.0.15+10-Ubuntu-0ubuntu0.20.04.1.  |
| -1 :x: |  compile  |   0m 36s |  tez-mapreduce in master failed with JDK Private Build-11.0.15+10-Ubuntu-0ubuntu0.20.04.1.  |
| -1 :x: |  compile  |   0m 33s |  tez-dag in master failed with JDK Private Build-11.0.15+10-Ubuntu-0ubuntu0.20.04.1.  |
| -1 :x: |  compile  |   0m 34s |  tez-ext-service-tests in master failed with JDK Private Build-11.0.15+10-Ubuntu-0ubuntu0.20.04.1.  |
| -1 :x: |  compile  |   0m 34s |  tez-protobuf-history-plugin in master failed with JDK Private Build-11.0.15+10-Ubuntu-0ubuntu0.20.04.1.  |
| -1 :x: |  compile  |   0m 39s |  root in master failed with JDK Private Build-11.0.15+10-Ubuntu-0ubuntu0.20.04.1.  |
| -1 :x: |  compile  |   0m 35s |  tez-api in master failed with JDK Private Build-1.8.0_312-8u312-b07-0ubuntu1~20.04-b07.  |
| -1 :x: |  compile  |   0m 29s |  tez-runtime-internals in master failed with JDK Private Build-1.8.0_312-8u312-b07-0ubuntu1~20.04-b07.  |
| -1 :x: |  compile  |   0m 30s |  tez-runtime-library in master failed with JDK Private Build-1.8.0_312-8u312-b07-0ubuntu1~20.04-b07.  |
| -1 :x: |  compile  |   0m 30s |  tez-mapreduce in master failed with JDK Private Build-1.8.0_312-8u312-b07-0ubuntu1~20.04-b07.  |
| -1 :x: |  compile  |   0m 31s |  tez-dag in master failed with JDK Private Build-1.8.0_312-8u312-b07-0ubuntu1~20.04-b07.  |
| -1 :x: |  compile  |   0m 30s |  tez-ext-service-tests in master failed with JDK Private Build-1.8.0_312-8u312-b07-0ubuntu1~20.04-b07.  |
| -1 :x: |  compile  |   0m 32s |  tez-protobuf-history-plugin in master failed with JDK Private Build-1.8.0_312-8u312-b07-0ubuntu1~20.04-b07.  |
| -1 :x: |  compile  |   0m 32s |  root in master failed with JDK Private Build-1.8.0_312-8u312-b07-0ubuntu1~20.04-b07.  |
| -1 :x: |  javadoc  |   0m 34s |  tez-api in master failed with JDK Private Build-11.0.15+10-Ubuntu-0ubuntu0.20.04.1.  |
| -1 :x: |  javadoc  |   0m 30s |  tez-runtime-internals in master failed with JDK Private Build-11.0.15+10-Ubuntu-0ubuntu0.20.04.1.  |
| -1 :x: |  javadoc  |   0m 30s |  tez-runtime-library in master failed with JDK Private Build-11.0.15+10-Ubuntu-0ubuntu0.20.04.1.  |
| -1 :x: |  javadoc  |   0m 35s |  tez-mapreduce in master failed with JDK Private Build-11.0.15+10-Ubuntu-0ubuntu0.20.04.1.  |
| -1 :x: |  javadoc  |   0m 33s |  tez-dag in master failed with JDK Private Build-11.0.15+10-Ubuntu-0ubuntu0.20.04.1.  |
| -1 :x: |  javadoc  |   0m 31s |  tez-ext-service-tests in master failed with JDK Private Build-11.0.15+10-Ubuntu-0ubuntu0.20.04.1.  |
| -1 :x: |  javadoc  |   0m 29s |  tez-protobuf-history-plugin in master failed with JDK Private Build-11.0.15+10-Ubuntu-0ubuntu0.20.04.1.  |
| -1 :x: |  javadoc  |   0m 49s |  root in master failed with JDK Private Build-11.0.15+10-Ubuntu-0ubuntu0.20.04.1.  |
| -1 :x: |  javadoc  |   0m 32s |  tez-api in master failed with JDK Private Build-1.8.0_312-8u312-b07-0ubuntu1~20.04-b07.  |
| -1 :x: |  javadoc  |   0m 34s |  tez-runtime-internals in master failed with JDK Private Build-1.8.0_312-8u312-b07-0ubuntu1~20.04-b07.  |
| -1 :x: |  javadoc  |   0m 31s |  tez-runtime-library in master failed with JDK Private Build-1.8.0_312-8u312-b07-0ubuntu1~20.04-b07.  |
| -1 :x: |  javadoc  |   0m 32s |  tez-mapreduce in master failed with JDK Private Build-1.8.0_312-8u312-b07-0ubuntu1~20.04-b07.  |
| -1 :x: |  javadoc  |   0m 37s |  tez-dag in master failed with JDK Private Build-1.8.0_312-8u312-b07-0ubuntu1~20.04-b07.  |
| -1 :x: |  javadoc  |   0m 31s |  tez-ext-service-tests in master failed with JDK Private Build-1.8.0_312-8u312-b07-0ubuntu1~20.04-b07.  |
| -1 :x: |  javadoc  |   0m 37s |  tez-protobuf-history-plugin in master failed with JDK Private Build-1.8.0_312-8u312-b07-0ubuntu1~20.04-b07.  |
| -1 :x: |  javadoc  |   0m 39s |  root in master failed with JDK Private Build-1.8.0_312-8u312-b07-0ubuntu1~20.04-b07.  |
||| _ Patch Compile Tests _ |
| +0 :ok: |  mvndep  |   0m 18s |  Maven dependency ordering for patch  |
| +1 :green_heart: |  mvninstall  |   8m 49s |  the patch passed  |
| +1 :green_heart: |  compile  |   7m 46s |  the patch passed with JDK Private Build-11.0.15+10-Ubuntu-0ubuntu0.20.04.1  |
| -1 :x: |  javac  |   0m 44s |  tez-runtime-library-jdkPrivateBuild-11.0.15+10-Ubuntu-0ubuntu0.20.04.1 with JDK Private Build-11.0.15+10-Ubuntu-0ubuntu0.20.04.1 generated 4 new + 0 unchanged - 0 fixed = 4 total (was 0)  |
| -1 :x: |  javac  |   2m 45s |  root-jdkPrivateBuild-11.0.15+10-Ubuntu-0ubuntu0.20.04.1 with JDK Private Build-11.0.15+10-Ubuntu-0ubuntu0.20.04.1 generated 4 new + 0 unchanged - 0 fixed = 4 total (was 0)  |
| +1 :green_heart: |  compile  |   7m 46s |  the patch passed with JDK Private Build-1.8.0_312-8u312-b07-0ubuntu1~20.04-b07  |
| -1 :x: |  javac  |   0m 45s |  tez-runtime-library-jdkPrivateBuild-1.8.0_312-8u312-b07-0ubuntu1~20.04-b07 with JDK Private Build-1.8.0_312-8u312-b07-0ubuntu1~20.04-b07 generated 4 new + 0 unchanged - 0 fixed = 4 total (was 0)  |
| -1 :x: |  javac  |   2m 24s |  root-jdkPrivateBuild-1.8.0_312-8u312-b07-0ubuntu1~20.04-b07 with JDK Private Build-1.8.0_312-8u312-b07-0ubuntu1~20.04-b07 generated 4 new + 0 unchanged - 0 fixed = 4 total (was 0)  |
| +1 :green_heart: |  hadolint  |   0m  2s |  There were no new hadolint issues.  |
| +1 :green_heart: |  shellcheck  |   0m  1s |  The patch generated 0 new + 0 unchanged - 2 fixed = 0 total (was 2)  |
| +1 :green_heart: |  whitespace  |   0m  0s |  The patch has no whitespace issues.  |
| +1 :green_heart: |  xml  |   0m 11s |  The patch has no ill-formed XML file.  |
| +1 :green_heart: |  yamllint  |   0m  0s |  There were no new yamllint issues.  |
| -1 :x: |  javadoc  |   0m 41s |  tez-api-jdkPrivateBuild-11.0.15+10-Ubuntu-0ubuntu0.20.04.1 with JDK Private Build-11.0.15+10-Ubuntu-0ubuntu0.20.04.1 generated 13 new + 0 unchanged - 0 fixed = 13 total (was 0)  |
| -1 :x: |  javadoc  |   0m 37s |  tez-runtime-library-jdkPrivateBuild-11.0.15+10-Ubuntu-0ubuntu0.20.04.1 with JDK Private Build-11.0.15+10-Ubuntu-0ubuntu0.20.04.1 generated 15 new + 0 unchanged - 0 fixed = 15 total (was 0)  |
| -1 :x: |  javadoc  |   0m 39s |  tez-mapreduce-jdkPrivateBuild-11.0.15+10-Ubuntu-0ubuntu0.20.04.1 with JDK Private Build-11.0.15+10-Ubuntu-0ubuntu0.20.04.1 generated 1 new + 0 unchanged - 0 fixed = 1 total (was 0)  |
| -1 :x: |  javadoc  |   0m 47s |  tez-dag-jdkPrivateBuild-11.0.15+10-Ubuntu-0ubuntu0.20.04.1 with JDK Private Build-11.0.15+10-Ubuntu-0ubuntu0.20.04.1 generated 2 new + 0 unchanged - 0 fixed = 2 total (was 0)  |
| -1 :x: |  javadoc  |   2m 12s |  root-jdkPrivateBuild-11.0.15+10-Ubuntu-0ubuntu0.20.04.1 with JDK Private Build-11.0.15+10-Ubuntu-0ubuntu0.20.04.1 generated 81 new + 0 unchanged - 0 fixed = 81 total (was 0)  |
| +1 :green_heart: |  javadoc  |   6m  8s |  the patch passed with JDK Private Build-1.8.0_312-8u312-b07-0ubuntu1~20.04-b07  |
||| _ Other Tests _ |
| +1 :green_heart: |  unit  |   2m 41s |  tez-api in the patch passed.  |
| +1 :green_heart: |  unit  |   1m  0s |  tez-runtime-internals in the patch passed.  |
| +1 :green_heart: |  unit  |   5m 45s |  tez-runtime-library in the patch passed.  |
| +1 :green_heart: |  unit  |   1m 50s |  tez-mapreduce in the patch passed.  |
| +1 :green_heart: |  unit  |   5m 42s |  tez-dag in the patch passed.  |
| +1 :green_heart: |  unit  |   4m 23s |  tez-ext-service-tests in the patch passed.  |
| +1 :green_heart: |  unit  |   0m 44s |  tez-protobuf-history-plugin in the patch passed.  |
| +1 :green_heart: |  unit  |  74m 47s |  root in the patch passed.  |
| +1 :green_heart: |  asflicense  |   6m  8s |  The patch does not generate ASF License warnings.  |
|  |   | 183m 12s |   |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.41 ServerAPI=1.41 base: https://ci-hadoop.apache.org/job/tez-multibranch/job/PR-218/1/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/tez/pull/218 |
| JIRA Issue | TEZ-4428 |
| Optional Tests | dupname asflicense hadolint shellcheck shelldocs javac javadoc unit xml compile yamllint |
| uname | Linux 9b7dc066bef9 4.15.0-58-generic #64-Ubuntu SMP Tue Aug 6 11:12:41 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | personality/tez.sh |
| git revision | master / e5a557802 |
| Default Java | Private Build-1.8.0_312-8u312-b07-0ubuntu1~20.04-b07 |
| Multi-JDK versions | /usr/lib/jvm/java-11-openjdk-amd64:Private Build-11.0.15+10-Ubuntu-0ubuntu0.20.04.1 /usr/lib/jvm/java-8-openjdk-amd64:Private Build-1.8.0_312-8u312-b07-0ubuntu1~20.04-b07 |
| mvninstall | https://ci-hadoop.apache.org/job/tez-multibranch/job/PR-218/1/artifact/out/branch-mvninstall-root.txt |
| compile | https://ci-hadoop.apache.org/job/tez-multibranch/job/PR-218/1/artifact/out/branch-compile-tez-api-jdkPrivateBuild-11.0.15+10-Ubuntu-0ubuntu0.20.04.1.txt |
| compile | https://ci-hadoop.apache.org/job/tez-multibranch/job/PR-218/1/artifact/out/branch-compile-tez-runtime-internals-jdkPrivateBuild-11.0.15+10-Ubuntu-0ubuntu0.20.04.1.txt |
| compile | https://ci-hadoop.apache.org/job/tez-multibranch/job/PR-218/1/artifact/out/branch-compile-tez-runtime-library-jdkPrivateBuild-11.0.15+10-Ubuntu-0ubuntu0.20.04.1.txt |
| compile | https://ci-hadoop.apache.org/job/tez-multibranch/job/PR-218/1/artifact/out/branch-compile-tez-mapreduce-jdkPrivateBuild-11.0.15+10-Ubuntu-0ubuntu0.20.04.1.txt |
| compile | https://ci-hadoop.apache.org/job/tez-multibranch/job/PR-218/1/artifact/out/branch-compile-tez-dag-jdkPrivateBuild-11.0.15+10-Ubuntu-0ubuntu0.20.04.1.txt |
| compile | https://ci-hadoop.apache.org/job/tez-multibranch/job/PR-218/1/artifact/out/branch-compile-tez-ext-service-tests-jdkPrivateBuild-11.0.15+10-Ubuntu-0ubuntu0.20.04.1.txt |
| compile | https://ci-hadoop.apache.org/job/tez-multibranch/job/PR-218/1/artifact/out/branch-compile-tez-plugins_tez-protobuf-history-plugin-jdkPrivateBuild-11.0.15+10-Ubuntu-0ubuntu0.20.04.1.txt |
| compile | https://ci-hadoop.apache.org/job/tez-multibranch/job/PR-218/1/artifact/out/branch-compile-root-jdkPrivateBuild-11.0.15+10-Ubuntu-0ubuntu0.20.04.1.txt |
| compile | https://ci-hadoop.apache.org/job/tez-multibranch/job/PR-218/1/artifact/out/branch-compile-tez-api-jdkPrivateBuild-1.8.0_312-8u312-b07-0ubuntu1~20.04-b07.txt |
| compile | https://ci-hadoop.apache.org/job/tez-multibranch/job/PR-218/1/artifact/out/branch-compile-tez-runtime-internals-jdkPrivateBuild-1.8.0_312-8u312-b07-0ubuntu1~20.04-b07.txt |
| compile | https://ci-hadoop.apache.org/job/tez-multibranch/job/PR-218/1/artifact/out/branch-compile-tez-runtime-library-jdkPrivateBuild-1.8.0_312-8u312-b07-0ubuntu1~20.04-b07.txt |
| compile | https://ci-hadoop.apache.org/job/tez-multibranch/job/PR-218/1/artifact/out/branch-compile-tez-mapreduce-jdkPrivateBuild-1.8.0_312-8u312-b07-0ubuntu1~20.04-b07.txt |
| compile | https://ci-hadoop.apache.org/job/tez-multibranch/job/PR-218/1/artifact/out/branch-compile-tez-dag-jdkPrivateBuild-1.8.0_312-8u312-b07-0ubuntu1~20.04-b07.txt |
| compile | https://ci-hadoop.apache.org/job/tez-multibranch/job/PR-218/1/artifact/out/branch-compile-tez-ext-service-tests-jdkPrivateBuild-1.8.0_312-8u312-b07-0ubuntu1~20.04-b07.txt |
| compile | https://ci-hadoop.apache.org/job/tez-multibranch/job/PR-218/1/artifact/out/branch-compile-tez-plugins_tez-protobuf-history-plugin-jdkPrivateBuild-1.8.0_312-8u312-b07-0ubuntu1~20.04-b07.txt |
| compile | https://ci-hadoop.apache.org/job/tez-multibranch/job/PR-218/1/artifact/out/branch-compile-root-jdkPrivateBuild-1.8.0_312-8u312-b07-0ubuntu1~20.04-b07.txt |
| javadoc | https://ci-hadoop.apache.org/job/tez-multibranch/job/PR-218/1/artifact/out/branch-javadoc-tez-api-jdkPrivateBuild-11.0.15+10-Ubuntu-0ubuntu0.20.04.1.txt |
| javadoc | https://ci-hadoop.apache.org/job/tez-multibranch/job/PR-218/1/artifact/out/branch-javadoc-tez-runtime-internals-jdkPrivateBuild-11.0.15+10-Ubuntu-0ubuntu0.20.04.1.txt |
| javadoc | https://ci-hadoop.apache.org/job/tez-multibranch/job/PR-218/1/artifact/out/branch-javadoc-tez-runtime-library-jdkPrivateBuild-11.0.15+10-Ubuntu-0ubuntu0.20.04.1.txt |
| javadoc | https://ci-hadoop.apache.org/job/tez-multibranch/job/PR-218/1/artifact/out/branch-javadoc-tez-mapreduce-jdkPrivateBuild-11.0.15+10-Ubuntu-0ubuntu0.20.04.1.txt |
| javadoc | https://ci-hadoop.apache.org/job/tez-multibranch/job/PR-218/1/artifact/out/branch-javadoc-tez-dag-jdkPrivateBuild-11.0.15+10-Ubuntu-0ubuntu0.20.04.1.txt |
| javadoc | https://ci-hadoop.apache.org/job/tez-multibranch/job/PR-218/1/artifact/out/branch-javadoc-tez-ext-service-tests-jdkPrivateBuild-11.0.15+10-Ubuntu-0ubuntu0.20.04.1.txt |
| javadoc | https://ci-hadoop.apache.org/job/tez-multibranch/job/PR-218/1/artifact/out/branch-javadoc-tez-plugins_tez-protobuf-history-plugin-jdkPrivateBuild-11.0.15+10-Ubuntu-0ubuntu0.20.04.1.txt |
| javadoc | https://ci-hadoop.apache.org/job/tez-multibranch/job/PR-218/1/artifact/out/branch-javadoc-root-jdkPrivateBuild-11.0.15+10-Ubuntu-0ubuntu0.20.04.1.txt |
| javadoc | https://ci-hadoop.apache.org/job/tez-multibranch/job/PR-218/1/artifact/out/branch-javadoc-tez-api-jdkPrivateBuild-1.8.0_312-8u312-b07-0ubuntu1~20.04-b07.txt |
| javadoc | https://ci-hadoop.apache.org/job/tez-multibranch/job/PR-218/1/artifact/out/branch-javadoc-tez-runtime-internals-jdkPrivateBuild-1.8.0_312-8u312-b07-0ubuntu1~20.04-b07.txt |
| javadoc | https://ci-hadoop.apache.org/job/tez-multibranch/job/PR-218/1/artifact/out/branch-javadoc-tez-runtime-library-jdkPrivateBuild-1.8.0_312-8u312-b07-0ubuntu1~20.04-b07.txt |
| javadoc | https://ci-hadoop.apache.org/job/tez-multibranch/job/PR-218/1/artifact/out/branch-javadoc-tez-mapreduce-jdkPrivateBuild-1.8.0_312-8u312-b07-0ubuntu1~20.04-b07.txt |
| javadoc | https://ci-hadoop.apache.org/job/tez-multibranch/job/PR-218/1/artifact/out/branch-javadoc-tez-dag-jdkPrivateBuild-1.8.0_312-8u312-b07-0ubuntu1~20.04-b07.txt |
| javadoc | https://ci-hadoop.apache.org/job/tez-multibranch/job/PR-218/1/artifact/out/branch-javadoc-tez-ext-service-tests-jdkPrivateBuild-1.8.0_312-8u312-b07-0ubuntu1~20.04-b07.txt |
| javadoc | https://ci-hadoop.apache.org/job/tez-multibranch/job/PR-218/1/artifact/out/branch-javadoc-tez-plugins_tez-protobuf-history-plugin-jdkPrivateBuild-1.8.0_312-8u312-b07-0ubuntu1~20.04-b07.txt |
| javadoc | https://ci-hadoop.apache.org/job/tez-multibranch/job/PR-218/1/artifact/out/branch-javadoc-root-jdkPrivateBuild-1.8.0_312-8u312-b07-0ubuntu1~20.04-b07.txt |
| javac | https://ci-hadoop.apache.org/job/tez-multibranch/job/PR-218/1/artifact/out/diff-compile-javac-tez-runtime-library-jdkPrivateBuild-11.0.15+10-Ubuntu-0ubuntu0.20.04.1.txt |
| javac | https://ci-hadoop.apache.org/job/tez-multibranch/job/PR-218/1/artifact/out/diff-compile-javac-root-jdkPrivateBuild-11.0.15+10-Ubuntu-0ubuntu0.20.04.1.txt |
| javac | https://ci-hadoop.apache.org/job/tez-multibranch/job/PR-218/1/artifact/out/diff-compile-javac-tez-runtime-library-jdkPrivateBuild-1.8.0_312-8u312-b07-0ubuntu1~20.04-b07.txt |
| javac | https://ci-hadoop.apache.org/job/tez-multibranch/job/PR-218/1/artifact/out/diff-compile-javac-root-jdkPrivateBuild-1.8.0_312-8u312-b07-0ubuntu1~20.04-b07.txt |
| javadoc | https://ci-hadoop.apache.org/job/tez-multibranch/job/PR-218/1/artifact/out/diff-javadoc-javadoc-tez-api-jdkPrivateBuild-11.0.15+10-Ubuntu-0ubuntu0.20.04.1.txt |
| javadoc | https://ci-hadoop.apache.org/job/tez-multibranch/job/PR-218/1/artifact/out/diff-javadoc-javadoc-tez-runtime-library-jdkPrivateBuild-11.0.15+10-Ubuntu-0ubuntu0.20.04.1.txt |
| javadoc | https://ci-hadoop.apache.org/job/tez-multibranch/job/PR-218/1/artifact/out/diff-javadoc-javadoc-tez-mapreduce-jdkPrivateBuild-11.0.15+10-Ubuntu-0ubuntu0.20.04.1.txt |
| javadoc | https://ci-hadoop.apache.org/job/tez-multibranch/job/PR-218/1/artifact/out/diff-javadoc-javadoc-tez-dag-jdkPrivateBuild-11.0.15+10-Ubuntu-0ubuntu0.20.04.1.txt |
| javadoc | https://ci-hadoop.apache.org/job/tez-multibranch/job/PR-218/1/artifact/out/diff-javadoc-javadoc-root-jdkPrivateBuild-11.0.15+10-Ubuntu-0ubuntu0.20.04.1.txt |
|  Test Results | https://ci-hadoop.apache.org/job/tez-multibranch/job/PR-218/1/testReport/ |
| Max. process+thread count | 2099 (vs. ulimit of 5500) |
| modules | C: tez-api tez-runtime-internals tez-runtime-library tez-mapreduce tez-dag tez-ext-service-tests tez-plugins/tez-protobuf-history-plugin . U: . |
| Console output | https://ci-hadoop.apache.org/job/tez-multibranch/job/PR-218/1/console |
| versions | git=2.25.1 maven=3.6.3 shellcheck=0.7.1 hadolint=1.18.0-0-g76eee5c yamllint=1.24.2 |
| Powered by | Apache Yetus 0.12.0 https://yetus.apache.org |


This message was automatically generated.

**Comment by abstractdog** [comment]
change looks good to me, 2 things to check:
1. whether above precommit failures can be fixed, or they're because of the nature of the precommit process
2. double-check arm architecture regarding platform detection, we were working on that with in the scope of TEZ-4300

**Comment by tez-yetus** [comment]
(!) A patch to the testing environment has been detected. 
Re-executing against the patched versions to perform further tests. 
The console is at https://ci-hadoop.apache.org/job/tez-multibranch/job/PR-218/2/console in case of problems.

**Review by martin-g — APPROVED** [review]

**Comment by tez-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| +0 :ok: |  reexec  |   6m 35s |  Docker mode activated.  |
||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  1s |  No case conflicting files found.  |
| +0 :ok: |  shelldocs  |   0m  1s |  Shelldocs was not available.  |
| +1 :green_heart: |  @author  |   0m  0s |  The patch does not contain any @author tags.  |
| -1 :x: |  test4tests  |   0m  0s |  The patch doesn't appear to include any new or modified tests. Please justify why no new tests are needed for this patch. Also please list what manual steps were performed to verify this patch.  |
||| _ master Compile Tests _ |
| +0 :ok: |  mvndep  |   6m 51s |  Maven dependency ordering for branch  |
| +1 :green_heart: |  mvninstall  |  10m 29s |  master passed  |
| +1 :green_heart: |  compile  |   8m 18s |  master passed with JDK Private Build-11.0.15+10-Ubuntu-0ubuntu0.20.04.1  |
| +1 :green_heart: |  compile  |   8m  3s |  master passed with JDK Private Build-1.8.0_312-8u312-b07-0ubuntu1~20.04-b07  |
| +1 :green_heart: |  javadoc  |   8m  4s |  master passed with JDK Private Build-11.0.15+10-Ubuntu-0ubuntu0.20.04.1  |
| +1 :green_heart: |  javadoc  |   7m 18s |  master passed with JDK Private Build-1.8.0_312-8u312-b07-0ubuntu1~20.04-b07  |
||| _ Patch Compile Tests _ |
| +0 :ok: |  mvndep  |   0m 20s |  Maven dependency ordering for patch  |
| +1 :green_heart: |  mvninstall  |   6m 59s |  the patch passed  |
| +1 :green_heart: |  compile  |   8m 22s |  the patch passed with JDK Private Build-11.0.15+10-Ubuntu-0ubuntu0.20.04.1  |
| +1 :green_heart: |  javac  |   8m 22s |  the patch passed  |
| +1 :green_heart: |  compile  |   8m  0s |  the patch passed with JDK Private Build-1.8.0_312-8u312-b07-0ubuntu1~20.04-b07  |
| +1 :green_heart: |  javac  |   8m  0s |  the patch passed  |
| +1 :green_heart: |  hadolint  |   0m  3s |  There were no new hadolint issues.  |
| +1 :green_heart: |  shellcheck  |   0m  1s |  The patch generated 0 new + 0 unchanged - 2 fixed = 0 total (was 2)  |
| +1 :green_heart: |  whitespace  |   0m  0s |  The patch has no whitespace issues.  |
| +1 :green_heart: |  xml  |   0m 10s |  The patch has no ill-formed XML file.  |
| +1 :green_heart: |  yamllint  |   0m  0s |  There were no new yamllint issues.  |
| +1 :green_heart: |  javadoc  |   7m 48s |  the patch passed with JDK Private Build-11.0.15+10-Ubuntu-0ubuntu0.20.04.1  |
| +1 :green_heart: |  javadoc  |   7m 19s |  the patch passed with JDK Private Build-1.8.0_312-8u312-b07-0ubuntu1~20.04-b07  |
||| _ Other Tests _ |
| +1 :green_heart: |  unit  |   2m 42s |  tez-api in the patch passed.  |
| +1 :green_heart: |  unit  |   1m  4s |  tez-runtime-internals in the patch passed.  |
| +1 :green_heart: |  unit  |   5m 56s |  tez-runtime-library in the patch passed.  |
| +1 :green_heart: |  unit  |   1m 50s |  tez-mapreduce in the patch passed.  |
| +1 :green_heart: |  unit  |   5m 42s |  tez-dag in the patch passed.  |
| +1 :green_heart: |  unit  |   4m 38s |  tez-ext-service-tests in the patch passed.  |
| +1 :green_heart: |  unit  |   0m 49s |  tez-protobuf-history-plugin in the patch passed.  |
| +1 :green_heart: |  unit  |  74m 19s |  root in the patch passed.  |
| +1 :green_heart: |  asflicense  |   6m 13s |  The patch does not generate ASF License warnings.  |
|  |   | 200m  3s |   |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.41 ServerAPI=1.41 base: https://ci-hadoop.apache.org/job/tez-multibranch/job/PR-218/2/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/tez/pull/218 |
| JIRA Issue | TEZ-4428 |
| Optional Tests | dupname asflicense hadolint shellcheck shelldocs javac javadoc unit xml compile yamllint |
| uname | Linux cc8a18a5d0a8 4.15.0-58-generic #64-Ubuntu SMP Tue Aug 6 11:12:41 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | personality/tez.sh |
| git revision | master / e5a557802 |
| Default Java | Private Build-1.8.0_312-8u312-b07-0ubuntu1~20.04-b07 |
| Multi-JDK versions | /usr/lib/jvm/java-11-openjdk-amd64:Private Build-11.0.15+10-Ubuntu-0ubuntu0.20.04.1 /usr/lib/jvm/java-8-openjdk-amd64:Private Build-1.8.0_312-8u312-b07-0ubuntu1~20.04-b07 |
|  Test Results | https://ci-hadoop.apache.org/job/tez-multibranch/job/PR-218/2/testReport/ |
| Max. process+thread count | 1462 (vs. ulimit of 5500) |
| modules | C: tez-api tez-runtime-internals tez-runtime-library tez-mapreduce tez-dag tez-ext-service-tests tez-plugins/tez-protobuf-history-plugin . U: . |
| Console output | https://ci-hadoop.apache.org/job/tez-multibranch/job/PR-218/2/console |
| versions | git=2.25.1 maven=3.6.3 shellcheck=0.7.1 hadolint=1.18.0-0-g76eee5c yamllint=1.24.2 |
| Powered by | Apache Yetus 0.12.0 https://yetus.apache.org |


This message was automatically generated.

**Pull request merged**
