### PR TITLE
TEZ-4581: ASF matomo integration for web site analytics

### PR DESCRIPTION
**Pull request by zabetak**
1. Use matomo for gathering usage statistics
2. Update the privacy policy link accordingly

### CODE REVIEW

**Comment by tez-yetus** [comment]
:confetti_ball: **+1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| +0 :ok: |  reexec  |  13m 47s |  Docker mode activated.  |
||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  0s |  No case conflicting files found.  |
| +1 :green_heart: |  @author  |   0m  0s |  The patch does not contain any @author tags.  |
||| _ master Compile Tests _ |
| +1 :green_heart: |  mvninstall  |  14m 19s |  master passed  |
| +1 :green_heart: |  mvnsite  |   0m 15s |  master passed  |
||| _ Patch Compile Tests _ |
| +1 :green_heart: |  mvninstall  |   0m  6s |  the patch passed  |
| +1 :green_heart: |  markdownlint  |   0m  0s |  The patch generated 0 new + 0 unchanged - 8 fixed = 0 total (was 8)  |
| +1 :green_heart: |  mvnsite  |   0m  5s |  the patch passed  |
| +1 :green_heart: |  whitespace  |   0m  0s |  The patch has no whitespace issues.  |
| +1 :green_heart: |  xml  |   0m  1s |  The patch has no ill-formed XML file.  |
||| _ Other Tests _ |
| +1 :green_heart: |  asflicense  |   0m 20s |  The patch does not generate ASF License warnings.  |
|  |   |  29m 20s |   |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.47 ServerAPI=1.47 base: https://ci-hadoop.apache.org/job/tez-multibranch/job/PR-375/1/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/tez/pull/375 |
| JIRA Issue | TEZ-4581 |
| Optional Tests | dupname asflicense markdownlint mvnsite xml |
| uname | Linux 1a4efde6c459 5.15.0-117-generic #127-Ubuntu SMP Fri Jul 5 20:13:28 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | personality/tez.sh |
| git revision | master / 607b2bc22 |
| Max. process+thread count | 77 (vs. ulimit of 5500) |
| modules | C: docs U: docs |
| Console output | https://ci-hadoop.apache.org/job/tez-multibranch/job/PR-375/1/console |
| versions | git=2.34.1 maven=3.6.3 markdownlint=0.23.2 |
| Powered by | Apache Yetus 0.12.0 https://yetus.apache.org |


This message was automatically generated.

**Comment by abstractdog** [comment]
thanks @zabetak  for this contribution!
I'm afraid the current site is out of sync with the xml files in the repo, hence I believe we might want to fix first
in the meantime, maybe we can add this manually to tez.apache.org, but let me check the webpage's state first

**Comment by abstractdog** [comment]
@zabetak : as TEZ-4587 is merged, can you please rebase this patch?

**Comment by zabetak** [comment]
@abstractdog I rebased the patch and checked that `mvn site:site` and `mvn site:run` work as expected.

**Comment by tez-yetus** [comment]
:confetti_ball: **+1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| +0 :ok: |  reexec  |   0m 10s |  Docker mode activated.  |
||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  0s |  No case conflicting files found.  |
| +1 :green_heart: |  @author  |   0m  0s |  The patch does not contain any @author tags.  |
||| _ master Compile Tests _ |
| +1 :green_heart: |  mvninstall  |   5m 40s |  master passed  |
| +1 :green_heart: |  mvnsite  |   1m  2s |  master passed  |
||| _ Patch Compile Tests _ |
| +1 :green_heart: |  mvninstall  |   0m  7s |  the patch passed  |
| +1 :green_heart: |  markdownlint  |   0m  1s |  The patch generated 0 new + 0 unchanged - 8 fixed = 0 total (was 8)  |
| +1 :green_heart: |  mvnsite  |   0m  8s |  the patch passed  |
| +1 :green_heart: |  whitespace  |   0m  0s |  The patch has no whitespace issues.  |
| +1 :green_heart: |  xml  |   0m  1s |  The patch has no ill-formed XML file.  |
||| _ Other Tests _ |
| +1 :green_heart: |  asflicense  |   0m 12s |  The patch does not generate ASF License warnings.  |
|  |   |   7m 46s |   |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.47 ServerAPI=1.47 base: https://ci-hadoop.apache.org/job/tez-multibranch/job/PR-375/2/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/tez/pull/375 |
| JIRA Issue | TEZ-4581 |
| Optional Tests | dupname asflicense markdownlint mvnsite xml |
| uname | Linux 032ea9ff63f6 5.15.0-124-generic #134-Ubuntu SMP Fri Sep 27 20:20:17 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | personality/tez.sh |
| git revision | master / 9efa6f14d |
| Max. process+thread count | 77 (vs. ulimit of 5500) |
| modules | C: docs U: docs |
| Console output | https://ci-hadoop.apache.org/job/tez-multibranch/job/PR-375/2/console |
| versions | git=2.34.1 maven=3.6.3 markdownlint=0.23.2 |
| Powered by | Apache Yetus 0.12.0 https://yetus.apache.org |


This message was automatically generated.

**Comment by abstractdog** [comment]
updated page from this PR, everything loooks good:
view-source:https://tez.apache.org/

matomo is included
privacy link points to the apache page

+1

**Review by abstractdog — APPROVED** [review]

**Pull request merged**
