### PR TITLE
TEZ-3966: Fix config file mime type 

### PR DESCRIPTION
**Pull request by rlukin**
to avoid error when "X-Content-Type-Options: nosniff" header enabled

### CODE REVIEW

**Comment by jteagles** [comment]
Please feel free to file a TEZ jira at https://issues.apache.org/jira/browse/TEZ to better track the issue and help give context to how to reproduce.

**Comment by rlukin** [comment]
@jteagles  https://issues.apache.org/jira/browse/TEZ-3966

**Comment by jteagles** [comment]
@rlukin, I have been able to reproduce this issue. Sorry for the delay in reviewing.
```
Refused to execute script from 'http://127.0.0.1:8000/config/configs.env' because its MIME type ('application/octet-stream') is not executable, and strict MIME type checking is enabled.
```

However, after applying this patch, I get a different error.
```
GET http://127.0.0.1:8000/config/configs.js net::ERR_ABORTED 404 (File not found)
```

Something is causing the configs.js file to not be included in the target directory or assembled into war file.

I believe this is likely incorrect, but perhaps you can help me understand or provide a fix.

**Comment by rlukin** [comment]
@jteagles Hi, unfortunately I haven't been working with that for several years and I'm not familiar with java and js. Sorry I can't help you. In the past I've figured out how to manually fix it on ambari installation by changing the source files and had created this MR. That's all I can recall.

**Comment by jteagles** [comment]
@rlukin, someone else found the answer to this file inclusion problem. 
https://github.com/apache/tez/blob/master/tez-ui/src/main/webapp/ember-cli-build.js#L47

By modifying this from '*.env' to "*.js" this does include configs.js, however it also includes other files
.//config/configs.js
.//config/build-info.js
.//config/environment.js
.//config/default-app-conf.js

Modifying from '*.env' to 'configs.js' limits the build to only include configs.js into the build.
Do you feel comfortable making this change? Otherwise, we can commit this change and create a follow-up jira to address configs.js file inclusion. Personally, I feel this change below should below in this PR for clarity.

```
diff --git tez-ui/src/main/webapp/ember-cli-build.js tez-ui/src/main/webapp/ember-cli-build.js
index 9b52210af..7bbc77d33 100644
--- tez-ui/src/main/webapp/ember-cli-build.js
+++ tez-ui/src/main/webapp/ember-cli-build.js
@@ -44,7 +44,7 @@ module.exports = function(defaults) {
 
   var configEnv = new Funnel('config', {
      srcDir: '/',
-     include: ['*.env'],
+     include: ['configs.js'],
      destDir: '/config'
   });
   var zipWorker = new Funnel('bower_components/zip-js', {
```

**Comment by rlukin** [comment]
@jteagles done. Do we need to update jira?

**Comment by jteagles** [comment]
Thanks for this change. Changes are now committed, @rlukin.

**Pull request merged**
