### PR TITLE
TEZ-4566: NPE in TezChild while fetching attemptId when container is asked to shut down

### PR DESCRIPTION
**Pull request by ayushtkn**

### CODE REVIEW

**Comment by tez-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| +0 :ok: |  reexec  |  24m 49s |  Docker mode activated.  |
||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  0s |  No case conflicting files found.  |
| +1 :green_heart: |  @author  |   0m  0s |  The patch does not contain any @author tags.  |
| -1 :x: |  test4tests  |   0m  0s |  The patch doesn't appear to include any new or modified tests. Please justify why no new tests are needed for this patch. Also please list what manual steps were performed to verify this patch.  |
||| _ master Compile Tests _ |
| +1 :green_heart: |  mvninstall  |  15m 32s |  master passed  |
| +1 :green_heart: |  compile  |   0m 28s |  master passed with JDK Ubuntu-11.0.22+7-post-Ubuntu-0ubuntu222.04.1  |
| +1 :green_heart: |  compile  |   0m 27s |  master passed with JDK Private Build-1.8.0_402-8u402-ga-2ubuntu1~22.04-b06  |
| +1 :green_heart: |  checkstyle  |   1m 24s |  master passed  |
| +1 :green_heart: |  javadoc  |   0m 38s |  master passed with JDK Ubuntu-11.0.22+7-post-Ubuntu-0ubuntu222.04.1  |
| +1 :green_heart: |  javadoc  |   0m 21s |  master passed with JDK Private Build-1.8.0_402-8u402-ga-2ubuntu1~22.04-b06  |
| +0 :ok: |  spotbugs  |   1m 22s |  Used deprecated FindBugs config; considering switching to SpotBugs.  |
| +1 :green_heart: |  findbugs  |   1m 20s |  master passed  |
||| _ Patch Compile Tests _ |
| +1 :green_heart: |  mvninstall  |   0m 16s |  the patch passed  |
| +1 :green_heart: |  compile  |   0m 16s |  the patch passed with JDK Ubuntu-11.0.22+7-post-Ubuntu-0ubuntu222.04.1  |
| +1 :green_heart: |  javac  |   0m 16s |  the patch passed  |
| +1 :green_heart: |  compile  |   0m 15s |  the patch passed with JDK Private Build-1.8.0_402-8u402-ga-2ubuntu1~22.04-b06  |
| +1 :green_heart: |  javac  |   0m 15s |  the patch passed  |
| +1 :green_heart: |  checkstyle  |   0m 10s |  tez-runtime-internals: The patch generated 0 new + 10 unchanged - 1 fixed = 10 total (was 11)  |
| +1 :green_heart: |  whitespace  |   0m  0s |  The patch has no whitespace issues.  |
| +1 :green_heart: |  javadoc  |   0m  8s |  the patch passed with JDK Ubuntu-11.0.22+7-post-Ubuntu-0ubuntu222.04.1  |
| +1 :green_heart: |  javadoc  |   0m  9s |  the patch passed with JDK Private Build-1.8.0_402-8u402-ga-2ubuntu1~22.04-b06  |
| +1 :green_heart: |  findbugs  |   0m 42s |  the patch passed  |
||| _ Other Tests _ |
| +1 :green_heart: |  unit  |   0m 48s |  tez-runtime-internals in the patch passed.  |
| +1 :green_heart: |  asflicense  |   0m 16s |  The patch does not generate ASF License warnings.  |
|  |   |  49m  3s |   |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.44 ServerAPI=1.44 base: https://ci-hadoop.apache.org/job/tez-multibranch/job/PR-358/1/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/tez/pull/358 |
| JIRA Issue | TEZ-4566 |
| Optional Tests | dupname asflicense javac javadoc unit spotbugs findbugs checkstyle compile |
| uname | Linux 07bd248eb2db 5.15.0-94-generic #104-Ubuntu SMP Tue Jan 9 15:25:40 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | personality/tez.sh |
| git revision | master / a1fcddb8b |
| Default Java | Private Build-1.8.0_402-8u402-ga-2ubuntu1~22.04-b06 |
| Multi-JDK versions | /usr/lib/jvm/java-11-openjdk-amd64:Ubuntu-11.0.22+7-post-Ubuntu-0ubuntu222.04.1 /usr/lib/jvm/java-8-openjdk-amd64:Private Build-1.8.0_402-8u402-ga-2ubuntu1~22.04-b06 |
|  Test Results | https://ci-hadoop.apache.org/job/tez-multibranch/job/PR-358/1/testReport/ |
| Max. process+thread count | 101 (vs. ulimit of 5500) |
| modules | C: tez-runtime-internals U: tez-runtime-internals |
| Console output | https://ci-hadoop.apache.org/job/tez-multibranch/job/PR-358/1/console |
| versions | git=2.34.1 maven=3.6.3 findbugs=3.0.1 |
| Powered by | Apache Yetus 0.12.0 https://yetus.apache.org |


This message was automatically generated.

**Comment by abstractdog** [comment]
this is a very weird edge case and I'm shocked we haven't bumped into it more often
the whole, moved block is useless when the container should die so this patch makes sense

this patch is fine if you can double-check by manually running with some UTs that are not running automatically here: tez-dag, tez-tests, can you please check that?

**Comment by ayushtkn** [comment]
One one of the LOG lines are there
```
2024-05-21T12:41:38,884  INFO [TezChild] app.TezTaskCommunicatorImpl: Container with id: container_1716320479875_0001_00_000024 is valid, but no longer registered, and will be killed
```

And for same there is NPE
```
2024-05-21T12:41:38,885  INFO [CallbackExecutor] launcher.LocalContainerLauncher: Container: container_1716320479875_0001_00_000024: Execution Failed: 
java.lang.NullPointerException: null
	at org.apache.tez.runtime.task.TezChild.run(TezChild.java:252) ~[tez-runtime-internals-0.10.3.jar:0.10.3]
```

**Comment by ayushtkn** [comment]
Ran the tests locally
**tez-dag**
```
INFO] --- surefire:3.0.0-M4:test (default-test) @ tez-dag ---
[INFO] 
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running org.apache.tez.dag.app.TestMemoryWithEvents
[WARNING] Tests run: 4, Failures: 0, Errors: 0, Skipped: 4, Time elapsed: 0.053 s - in org.apache.tez.dag.app.TestMemoryWithEvents
[INFO] Running org.apache.tez.dag.app.TestTaskCommunicatorManager1
[INFO] Tests run: 8, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 1.065 s - in org.apache.tez.dag.app.TestTaskCommunicatorManager1
[INFO] Running org.apache.tez.dag.app.launcher.TestDeletionTracker
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.174 s - in org.apache.tez.dag.app.launcher.TestDeletionTracker
[INFO] Running org.apache.tez.dag.app.launcher.TestContainerLauncherManager
[INFO] Tests run: 7, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.703 s - in org.apache.tez.dag.app.launcher.TestContainerLauncherManager
[INFO] Running org.apache.tez.dag.app.launcher.TestTezLocalCacheManager
[INFO] Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.677 s - in org.apache.tez.dag.app.launcher.TestTezLocalCacheManager
[INFO] Running org.apache.tez.dag.app.launcher.TestContainerLauncherWrapper
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.386 s - in org.apache.tez.dag.app.launcher.TestContainerLauncherWrapper
[INFO] Running org.apache.tez.dag.app.TestMockDAGAppMaster
[WARNING] Tests run: 18, Failures: 0, Errors: 0, Skipped: 3, Time elapsed: 7.382 s - in org.apache.tez.dag.app.TestMockDAGAppMaster
[INFO] Running org.apache.tez.dag.app.web.TestAMWebController
[INFO] Tests run: 16, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.926 s - in org.apache.tez.dag.app.web.TestAMWebController
[INFO] Running org.apache.tez.dag.app.TestDAGAppMaster
[INFO] Tests run: 10, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 4.33 s - in org.apache.tez.dag.app.TestDAGAppMaster
[INFO] Running org.apache.tez.dag.app.dag.impl.TestTaskAttempt
[INFO] Tests run: 26, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 1.321 s - in org.apache.tez.dag.app.dag.impl.TestTaskAttempt
[INFO] Running org.apache.tez.dag.app.dag.impl.TestCommit
[INFO] Tests run: 31, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 6.363 s - in org.apache.tez.dag.app.dag.impl.TestCommit
[INFO] Running org.apache.tez.dag.app.dag.impl.TestDAGRecovery
[INFO] Tests run: 25, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 2.463 s - in org.apache.tez.dag.app.dag.impl.TestDAGRecovery
[INFO] Running org.apache.tez.dag.app.dag.impl.TestImmediateStartVertexManager
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.428 s - in org.apache.tez.dag.app.dag.impl.TestImmediateStartVertexManager
[INFO] Running org.apache.tez.dag.app.dag.impl.TestVertexStats
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.173 s - in org.apache.tez.dag.app.dag.impl.TestVertexStats
[INFO] Running org.apache.tez.dag.app.dag.impl.TestTaskImpl
[INFO] Tests run: 37, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 1.095 s - in org.apache.tez.dag.app.dag.impl.TestTaskImpl
[INFO] Running org.apache.tez.dag.app.dag.impl.TestVertexImpl2
[INFO] Tests run: 8, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.874 s - in org.apache.tez.dag.app.dag.impl.TestVertexImpl2
[INFO] Running org.apache.tez.dag.app.dag.impl.TestEdge
[INFO] Tests run: 9, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.632 s - in org.apache.tez.dag.app.dag.impl.TestEdge
[INFO] Running org.apache.tez.dag.app.dag.impl.TestDAGImpl
[WARNING] Tests run: 42, Failures: 0, Errors: 0, Skipped: 1, Time elapsed: 9.88 s - in org.apache.tez.dag.app.dag.impl.TestDAGImpl
[INFO] Running org.apache.tez.dag.app.dag.impl.TestVertexImpl
[WARNING] Tests run: 102, Failures: 0, Errors: 0, Skipped: 1, Time elapsed: 3.294 s - in org.apache.tez.dag.app.dag.impl.TestVertexImpl
[INFO] Running org.apache.tez.dag.app.dag.impl.TestVertexManager
[INFO] Tests run: 5, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.84 s - in org.apache.tez.dag.app.dag.impl.TestVertexManager
[INFO] Running org.apache.tez.dag.app.dag.impl.TestDAGScheduler
[INFO] Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.518 s - in org.apache.tez.dag.app.dag.impl.TestDAGScheduler
[INFO] Running org.apache.tez.dag.app.dag.impl.TestRootInputVertexManager
[INFO] Tests run: 4, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.673 s - in org.apache.tez.dag.app.dag.impl.TestRootInputVertexManager
[INFO] Running org.apache.tez.dag.app.dag.impl.TestDAGSchedulerNaturalOrderControlled
[INFO] Tests run: 4, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.612 s - in org.apache.tez.dag.app.dag.impl.TestDAGSchedulerNaturalOrderControlled
[INFO] Running org.apache.tez.dag.app.dag.app.TestTezTaskCommunicatorManager
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.558 s - in org.apache.tez.dag.app.dag.app.TestTezTaskCommunicatorManager
[INFO] Running org.apache.tez.dag.app.dag.speculation.legacy.TestDataStatistics
[INFO] Tests run: 4, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.047 s - in org.apache.tez.dag.app.dag.speculation.legacy.TestDataStatistics
[INFO] Running org.apache.tez.dag.app.dag.TestStateChangeNotifier
[INFO] Tests run: 5, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.535 s - in org.apache.tez.dag.app.dag.TestStateChangeNotifier
[INFO] Running org.apache.tez.dag.app.dag.TestRootInputInitializerManager
[INFO] Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.688 s - in org.apache.tez.dag.app.dag.TestRootInputInitializerManager
[INFO] Running org.apache.tez.dag.app.TestTaskCommunicatorManager2
[INFO] Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.835 s - in org.apache.tez.dag.app.TestTaskCommunicatorManager2
[INFO] Running org.apache.tez.dag.app.TestTaskCommunicatorContextImpl
[INFO] Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.57 s - in org.apache.tez.dag.app.TestTaskCommunicatorContextImpl
[INFO] Running org.apache.tez.dag.app.TestPreemption
[INFO] Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 3.031 s - in org.apache.tez.dag.app.TestPreemption
[INFO] Running org.apache.tez.dag.app.TestSpeculation
[INFO] Tests run: 10, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 53.746 s - in org.apache.tez.dag.app.TestSpeculation
[INFO] Running org.apache.tez.dag.app.TestRecoveryParser
[INFO] Tests run: 16, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 5.495 s - in org.apache.tez.dag.app.TestRecoveryParser
[INFO] Running org.apache.tez.dag.app.TestTaskCommunicatorManager
[INFO] Tests run: 6, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.852 s - in org.apache.tez.dag.app.TestTaskCommunicatorManager
[INFO] Running org.apache.tez.dag.app.rm.TestLocalTaskSchedulerService
[INFO] Tests run: 6, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 1.235 s - in org.apache.tez.dag.app.rm.TestLocalTaskSchedulerService
[INFO] Running org.apache.tez.dag.app.rm.TestTaskSchedulerManager
[INFO] Tests run: 19, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 3.4 s - in org.apache.tez.dag.app.rm.TestTaskSchedulerManager
[INFO] Running org.apache.tez.dag.app.rm.container.TestAMContainer
[INFO] Tests run: 27, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.743 s - in org.apache.tez.dag.app.rm.container.TestAMContainer
[INFO] Running org.apache.tez.dag.app.rm.container.TestAMContainerMap
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.71 s - in org.apache.tez.dag.app.rm.container.TestAMContainerMap
[INFO] Running org.apache.tez.dag.app.rm.TestLocalTaskScheduler
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.606 s - in org.apache.tez.dag.app.rm.TestLocalTaskScheduler
[INFO] Running org.apache.tez.dag.app.rm.TestTaskSchedulerWrapper
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.502 s - in org.apache.tez.dag.app.rm.TestTaskSchedulerWrapper
[INFO] Running org.apache.tez.dag.app.rm.TestTaskScheduler
[INFO] Tests run: 11, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 6.368 s - in org.apache.tez.dag.app.rm.TestTaskScheduler
[INFO] Running org.apache.tez.dag.app.rm.TestContainerReuse
[INFO] Tests run: 11, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 6.46 s - in org.apache.tez.dag.app.rm.TestContainerReuse
[INFO] Running org.apache.tez.dag.app.rm.node.TestAMNodeTracker
[INFO] Tests run: 16, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.767 s - in org.apache.tez.dag.app.rm.node.TestAMNodeTracker
[INFO] Running org.apache.tez.dag.app.rm.TestDagAwareYarnTaskScheduler
[INFO] Tests run: 12, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 1.04 s - in org.apache.tez.dag.app.rm.TestDagAwareYarnTaskScheduler
[INFO] Running org.apache.tez.dag.app.rm.TestTezAMRMClient
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.518 s - in org.apache.tez.dag.app.rm.TestTezAMRMClient
[INFO] Running org.apache.tez.dag.app.TestTaskCommunicatorWrapper
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.555 s - in org.apache.tez.dag.app.TestTaskCommunicatorWrapper
[INFO] Running org.apache.tez.dag.utils.TestTaskSpecificLaunchCmdOption
[INFO] Tests run: 4, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.183 s - in org.apache.tez.dag.utils.TestTaskSpecificLaunchCmdOption
[INFO] Running org.apache.tez.dag.utils.TestSimple2LevelVersionComparator
[INFO] Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.086 s - in org.apache.tez.dag.utils.TestSimple2LevelVersionComparator
[INFO] Running org.apache.tez.dag.history.TestHistoryEventHandler
[INFO] Tests run: 4, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.761 s - in org.apache.tez.dag.history.TestHistoryEventHandler
[INFO] Running org.apache.tez.dag.history.TestHistoryEventType
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.063 s - in org.apache.tez.dag.history.TestHistoryEventType
[INFO] Running org.apache.tez.dag.history.recovery.TestRecoveryService
[INFO] Tests run: 9, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 41.405 s - in org.apache.tez.dag.history.recovery.TestRecoveryService
[INFO] Running org.apache.tez.dag.history.utils.TestDAGUtils
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.333 s - in org.apache.tez.dag.history.utils.TestDAGUtils
[INFO] Running org.apache.tez.dag.history.events.TestHistoryEventsProtoConversion
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.384 s - in org.apache.tez.dag.history.events.TestHistoryEventsProtoConversion
[INFO] Running org.apache.tez.dag.history.logging.impl.TestHistoryEventJsonConversion
[INFO] Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.277 s - in org.apache.tez.dag.history.logging.impl.TestHistoryEventJsonConversion
[INFO] Running org.apache.tez.dag.api.client.TestVertexStatusBuilder
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.052 s - in org.apache.tez.dag.api.client.TestVertexStatusBuilder
[INFO] Running org.apache.tez.dag.api.client.TestDAGClientServer
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.848 s - in org.apache.tez.dag.api.client.TestDAGClientServer
[INFO] Running org.apache.tez.dag.api.client.TestDAGClientHandler
[INFO] Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.693 s - in org.apache.tez.dag.api.client.TestDAGClientHandler
[INFO] Running org.apache.tez.dag.api.client.rpc.TestDAGClientAMProtocolBlockingPBServerImpl
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 2.108 s - in org.apache.tez.dag.api.client.rpc.TestDAGClientAMProtocolBlockingPBServerImpl
[INFO] 
[INFO] Results:
[INFO] 
[WARNING] Tests run: 555, Failures: 0, Errors: 0, Skipped: 9
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  03:42 min
[INFO] Finished at: 2024-05-22T01:22:35+05:30
[INFO] ------------------------------------------------------------------------

```

**tez-tests:**

```
INFO] --- surefire:3.0.0-M4:test (default-test) @ tez-tests ---
[INFO] 
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running org.apache.tez.test.TestAMRecovery
[INFO] Tests run: 7, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 186.781 s - in org.apache.tez.test.TestAMRecovery
[INFO] Running org.apache.tez.test.TestDAGRecovery
[INFO] Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 62.957 s - in org.apache.tez.test.TestDAGRecovery
[INFO] Running org.apache.tez.test.TestAM
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 30.974 s - in org.apache.tez.test.TestAM
[INFO] Running org.apache.tez.test.TestSecureShuffle
[INFO] Tests run: 4, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 209.982 s - in org.apache.tez.test.TestSecureShuffle
[INFO] Running org.apache.tez.test.TestFaultTolerance
[WARNING] Tests run: 26, Failures: 0, Errors: 0, Skipped: 1, Time elapsed: 160.094 s - in org.apache.tez.test.TestFaultTolerance
[INFO] Running org.apache.tez.test.TestDAGRecovery2
[INFO] Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 46.595 s - in org.apache.tez.test.TestDAGRecovery2
[INFO] Running org.apache.tez.test.TestLocalMode
[INFO] Tests run: 20, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 89.607 s - in org.apache.tez.test.TestLocalMode
[INFO] Running org.apache.tez.test.TestRecovery
[INFO] Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 311.018 s - in org.apache.tez.test.TestRecovery
[INFO] Running org.apache.tez.test.TestTaskErrorsUsingLocalMode
[INFO] Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 3.244 s - in org.apache.tez.test.TestTaskErrorsUsingLocalMode
[INFO] Running org.apache.tez.test.TestExceptionPropagation
[INFO] Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 37.404 s - in org.apache.tez.test.TestExceptionPropagation
[INFO] Running org.apache.tez.test.TestMiniTezCluster
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 3.962 s - in org.apache.tez.test.TestMiniTezCluster
[INFO] Running org.apache.tez.test.TestPipelinedShuffle
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 41.218 s - in org.apache.tez.test.TestPipelinedShuffle
[INFO] Running org.apache.tez.test.TestTezJobs
[INFO] Tests run: 23, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 228.908 s - in org.apache.tez.test.TestTezJobs
[INFO] Running org.apache.tez.mapreduce.TestMRRJobs
[INFO] Tests run: 5, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 79.377 s - in org.apache.tez.mapreduce.TestMRRJobs
[INFO] Running org.apache.tez.mapreduce.TestMRRJobsDAGApi
[INFO] Tests run: 14, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 126.176 s - in org.apache.tez.mapreduce.TestMRRJobsDAGApi
[INFO] 
[INFO] Results:
[INFO] 
[WARNING] Tests run: 114, Failures: 0, Errors: 0, Skipped: 1
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  27:15 min
[INFO] Finished at: 2024-05-22T01:50:20+05:30
[INFO] ------------------------------------------------------------------------
```

**Review by abstractdog — APPROVED** [review]
+1

**Pull request merged**
