### PR TITLE
TEZ-4374: Enable github action to compile with JDK 17

### PR DESCRIPTION
**Pull request by abstractdog**

### CODE REVIEW

**Comment by abstractdog** [comment]
this is supposed to fail until TEZ-4387 is not present on master

**Comment by tez-yetus** [comment]
:confetti_ball: **+1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| +0 :ok: |  reexec  |  23m 55s |  Docker mode activated.  |
||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  0s |  No case conflicting files found.  |
| +1 :green_heart: |  @author  |   0m  0s |  The patch does not contain any @author tags.  |
||| _ master Compile Tests _ |
||| _ Patch Compile Tests _ |
| +1 :green_heart: |  whitespace  |   0m  1s |  The patch has no whitespace issues.  |
| +1 :green_heart: |  yamllint  |   0m  0s |  There were no new yamllint issues.  |
||| _ Other Tests _ |
| +1 :green_heart: |  asflicense  |   0m 36s |  The patch does not generate ASF License warnings.  |
|  |   |  25m  2s |   |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.47 ServerAPI=1.47 base: https://ci-hadoop.apache.org/job/tez-multibranch/job/PR-386/1/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/tez/pull/386 |
| JIRA Issue | TEZ-4374 |
| Optional Tests | dupname asflicense yamllint |
| uname | Linux f4e5ac5f5b18 5.15.0-124-generic #134-Ubuntu SMP Fri Sep 27 20:20:17 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | personality/tez.sh |
| git revision | master / c77d37e5a |
| Max. process+thread count | 51 (vs. ulimit of 5500) |
| modules | C: . U: . |
| Console output | https://ci-hadoop.apache.org/job/tez-multibranch/job/PR-386/1/console |
| versions | git=2.34.1 maven=3.6.3 yamllint=1.24.2 |
| Powered by | Apache Yetus 0.12.0 https://yetus.apache.org |


This message was automatically generated.

**Comment by abstractdog** [comment]
@ayushtkn: could you take a look? this activates Java17 compilation in precommit (only compliation, no tests yes)

**Review by ayushtkn — APPROVED** [review]
LGTM

**Comment by ayushtkn** [comment]
@abstractdog This is Runtime compatibility right? not Compile time, for compile time, we should change this to 17:
https://github.com/apache/tez/blob/c7a3791e971e30b47ce3a4a465e507a43f609ade/pom.xml#L44

As of now it is hardcoded 1.8 which is JDK-8 for 17 it should be changed to 17, or is there some place we do that which I missed?

**Comment by tez-yetus** [comment]
:confetti_ball: **+1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| +0 :ok: |  reexec  |  23m 52s |  Docker mode activated.  |
||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  0s |  No case conflicting files found.  |
| +1 :green_heart: |  @author  |   0m  0s |  The patch does not contain any @author tags.  |
||| _ master Compile Tests _ |
||| _ Patch Compile Tests _ |
| +1 :green_heart: |  whitespace  |   0m  0s |  The patch has no whitespace issues.  |
| +1 :green_heart: |  yamllint  |   0m  0s |  There were no new yamllint issues.  |
||| _ Other Tests _ |
| +1 :green_heart: |  asflicense  |   1m 31s |  The patch does not generate ASF License warnings.  |
|  |   |  26m 19s |   |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.47 ServerAPI=1.47 base: https://ci-hadoop.apache.org/job/tez-multibranch/job/PR-386/2/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/tez/pull/386 |
| JIRA Issue | TEZ-4374 |
| Optional Tests | dupname asflicense yamllint |
| uname | Linux 8f9ccfed8c6a 5.15.0-124-generic #134-Ubuntu SMP Fri Sep 27 20:20:17 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | personality/tez.sh |
| git revision | master / c7a3791e9 |
| Max. process+thread count | 51 (vs. ulimit of 5500) |
| modules | C: . U: . |
| Console output | https://ci-hadoop.apache.org/job/tez-multibranch/job/PR-386/2/console |
| versions | git=2.34.1 maven=3.6.3 yamllint=1.24.2 |
| Powered by | Apache Yetus 0.12.0 https://yetus.apache.org |


This message was automatically generated.

**Comment by abstractdog** [comment]
> @abstractdog This is Runtime compatibility right? not Compile time, for compile time, we should change this to 17:
> 
> https://github.com/apache/tez/blob/c7a3791e971e30b47ce3a4a465e507a43f609ade/pom.xml#L44
> 
> As of now it is hardcoded 1.8 which is JDK-8 for 17 it should be changed to 17, or is there some place we do that which I missed?

hm, good question, I usually struggle with maven options like this honestly...what's driven by this patch is that the precommit will simply compile the source with different java versions, which is the same thing I achieve by pointing the java/javac etc. commands to a different JAVA_HOME (hence chaging java version) before compiling the code
whether maven should do any enforcement in this scenario is a different question

**Comment by ayushtkn** [comment]
As of now the byte code would be for JDK 8 only
https://stackoverflow.com/a/38883073

to have the byte code for JDK-17 we need to change that to 17

this is the offcial doc:
https://maven.apache.org/plugins/maven-compiler-plugin/examples/set-compiler-source-and-target.html

Maybe we can merge this with a changed title and explore the compile stuff in seperate ticket

**Comment by abstractdog** [comment]
> As of now the byte code would be for JDK 8 only https://stackoverflow.com/a/38883073
> 
> to have the byte code for JDK-17 we need to change that to 17
> 
> this is the offcial doc: https://maven.apache.org/plugins/maven-compiler-plugin/examples/set-compiler-source-and-target.html
> 
> Maybe we can merge this with a changed title and explore the compile stuff in seperate ticket

hm, okay, I just refreshed the source/target javac options a bit :D
what settings are recommended here?
in my understanding: the source version specifies the language features and syntax that the compiler should allow, while the target version specifies the bytecode compatibility for the Java runtime

according to official documentation (https://docs.oracle.com/javase/7/docs/technotes/tools/windows/javac.html#crosscomp-example) and other articles, -target defines the lowest JDK runtime version that we're about to make the code able to run against, I believe we haven't changed the project state at all from this point of view, right?
I mean, now with TEZ-4387 merged, we're able to compile against JDK17, but e.g. we haven't told that the minimum supported JDK version is anything greater than 8
hence the "Check compile-time compatibility with JDK 17 in precommit" makes sense

do you agree with the above points? what title do you recommend?

**Comment by ayushtkn** [comment]
We can change the title to mention Runtime rather than compile time, same as in Hadoop it has runtime capabilities but doesn’t claim compile time bcoz the maven version is set as 1.8 changing doesn’t work either, that is something we also need to see what happens in case of Tez

and for 1.0 we can bump it to 17 and claim compile time compat.

anyway I am +1 here

**Comment by abstractdog** [comment]
> We can change the title to mention Runtime rather than compile time, same as in Hadoop it has runtime capabilities but doesn’t claim compile time bcoz the maven version is set as 1.8 changing doesn’t work either, that is something we also need to see what happens in case of Tez
> 
> and for 1.0 we can bump it to 17 and claim compile time compat.
> 
> anyway I am +1 here

okay, I think I got your point, so it would be confusing to claim "compatibility" with stil using 1.8 -source and -target javac arguments
this PR does nothing more than enable a github action, that complies with the existing code with existing javac settings, so a title like this below is indeed more straightforward:
```
Enable github action to compile with JDK 17
```
wdyt?

**Comment by ayushtkn** [comment]
Sounds cool

**Pull request merged**
