### PR TITLE
TEZ-4447: Collect VertexStatus properly when DAGClientServer is not used (local mode without network)

### PR DESCRIPTION
**Pull request by abstractdog**

### CODE REVIEW

**Comment by tez-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| +0 :ok: |  reexec  |  36m 31s |  Docker mode activated.  |
||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  0s |  No case conflicting files found.  |
| +1 :green_heart: |  @author  |   0m  0s |  The patch does not contain any @author tags.  |
| +1 :green_heart: |  test4tests  |   0m  0s |  The patch appears to include 1 new or modified test files.  |
||| _ master Compile Tests _ |
| +0 :ok: |  mvndep  |   4m 33s |  Maven dependency ordering for branch  |
| +1 :green_heart: |  mvninstall  |  11m  3s |  master passed  |
| +1 :green_heart: |  compile  |   2m 55s |  master passed with JDK Ubuntu-11.0.16+8-post-Ubuntu-0ubuntu120.04  |
| +1 :green_heart: |  compile  |   2m 40s |  master passed with JDK Private Build-1.8.0_342-8u342-b07-0ubuntu1~20.04-b07  |
| +1 :green_heart: |  checkstyle  |   2m 28s |  master passed  |
| +1 :green_heart: |  javadoc  |   2m 45s |  master passed with JDK Ubuntu-11.0.16+8-post-Ubuntu-0ubuntu120.04  |
| +1 :green_heart: |  javadoc  |   2m 34s |  master passed with JDK Private Build-1.8.0_342-8u342-b07-0ubuntu1~20.04-b07  |
| +0 :ok: |  spotbugs  |   0m 54s |  Used deprecated FindBugs config; considering switching to SpotBugs.  |
| +1 :green_heart: |  findbugs  |   4m 57s |  master passed  |
||| _ Patch Compile Tests _ |
| +0 :ok: |  mvndep  |   0m  9s |  Maven dependency ordering for patch  |
| +1 :green_heart: |  mvninstall  |   1m 37s |  the patch passed  |
| +1 :green_heart: |  compile  |   1m 47s |  the patch passed with JDK Ubuntu-11.0.16+8-post-Ubuntu-0ubuntu120.04  |
| +1 :green_heart: |  javac  |   1m 47s |  the patch passed  |
| +1 :green_heart: |  compile  |   1m 31s |  the patch passed with JDK Private Build-1.8.0_342-8u342-b07-0ubuntu1~20.04-b07  |
| +1 :green_heart: |  javac  |   1m 31s |  the patch passed  |
| -0 :warning: |  checkstyle  |   0m 14s |  tez-api: The patch generated 1 new + 71 unchanged - 0 fixed = 72 total (was 71)  |
| +1 :green_heart: |  whitespace  |   0m  0s |  The patch has no whitespace issues.  |
| +1 :green_heart: |  javadoc  |   1m 26s |  the patch passed with JDK Ubuntu-11.0.16+8-post-Ubuntu-0ubuntu120.04  |
| +1 :green_heart: |  javadoc  |   1m 22s |  the patch passed with JDK Private Build-1.8.0_342-8u342-b07-0ubuntu1~20.04-b07  |
| +1 :green_heart: |  findbugs  |   4m  6s |  the patch passed  |
||| _ Other Tests _ |
| +1 :green_heart: |  unit  |   2m 13s |  tez-api in the patch passed.  |
| +1 :green_heart: |  unit  |   4m 56s |  tez-runtime-library in the patch passed.  |
| +1 :green_heart: |  unit  |   5m  7s |  tez-dag in the patch passed.  |
| -1 :x: |  unit  |  37m 58s |  tez-tests in the patch failed.  |
| +1 :green_heart: |  asflicense  |   0m 52s |  The patch does not generate ASF License warnings.  |
|  |   | 136m 17s |   |


| Reason | Tests |
|-------:|:------|
| Failed junit tests | tez.mapreduce.TestMRRJobs |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.41 ServerAPI=1.41 base: https://ci-hadoop.apache.org/job/tez-multibranch/job/PR-239/1/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/tez/pull/239 |
| JIRA Issue | TEZ-4447 |
| Optional Tests | dupname asflicense javac javadoc unit spotbugs findbugs checkstyle compile |
| uname | Linux ad47e7be58f7 4.15.0-191-generic #202-Ubuntu SMP Thu Aug 4 01:49:29 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | personality/tez.sh |
| git revision | master / 55b6031fa |
| Default Java | Private Build-1.8.0_342-8u342-b07-0ubuntu1~20.04-b07 |
| Multi-JDK versions | /usr/lib/jvm/java-11-openjdk-amd64:Ubuntu-11.0.16+8-post-Ubuntu-0ubuntu120.04 /usr/lib/jvm/java-8-openjdk-amd64:Private Build-1.8.0_342-8u342-b07-0ubuntu1~20.04-b07 |
| checkstyle | https://ci-hadoop.apache.org/job/tez-multibranch/job/PR-239/1/artifact/out/diff-checkstyle-tez-api.txt |
| unit | https://ci-hadoop.apache.org/job/tez-multibranch/job/PR-239/1/artifact/out/patch-unit-tez-tests.txt |
|  Test Results | https://ci-hadoop.apache.org/job/tez-multibranch/job/PR-239/1/testReport/ |
| Max. process+thread count | 2089 (vs. ulimit of 5500) |
| modules | C: tez-api tez-runtime-library tez-dag tez-tests U: . |
| Console output | https://ci-hadoop.apache.org/job/tez-multibranch/job/PR-239/1/console |
| versions | git=2.25.1 maven=3.6.3 findbugs=3.0.1 |
| Powered by | Apache Yetus 0.12.0 https://yetus.apache.org |


This message was automatically generated.

**Comment by tez-yetus** [comment]
:confetti_ball: **+1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| +0 :ok: |  reexec  |   1m  7s |  Docker mode activated.  |
||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  0s |  No case conflicting files found.  |
| +1 :green_heart: |  @author  |   0m  0s |  The patch does not contain any @author tags.  |
| +1 :green_heart: |  test4tests  |   0m  0s |  The patch appears to include 1 new or modified test files.  |
||| _ master Compile Tests _ |
| +0 :ok: |  mvndep  |   4m 41s |  Maven dependency ordering for branch  |
| +1 :green_heart: |  mvninstall  |  11m 10s |  master passed  |
| +1 :green_heart: |  compile  |   3m 37s |  master passed with JDK Ubuntu-11.0.16+8-post-Ubuntu-0ubuntu120.04  |
| +1 :green_heart: |  compile  |   3m 18s |  master passed with JDK Private Build-1.8.0_342-8u342-b07-0ubuntu1~20.04-b07  |
| +1 :green_heart: |  checkstyle  |   3m  1s |  master passed  |
| +1 :green_heart: |  javadoc  |   3m 24s |  master passed with JDK Ubuntu-11.0.16+8-post-Ubuntu-0ubuntu120.04  |
| +1 :green_heart: |  javadoc  |   3m  7s |  master passed with JDK Private Build-1.8.0_342-8u342-b07-0ubuntu1~20.04-b07  |
| +0 :ok: |  spotbugs  |   0m 55s |  Used deprecated FindBugs config; considering switching to SpotBugs.  |
| +1 :green_heart: |  findbugs  |   5m 58s |  master passed  |
||| _ Patch Compile Tests _ |
| +0 :ok: |  mvndep  |   0m  9s |  Maven dependency ordering for patch  |
| +1 :green_heart: |  mvninstall  |   1m 55s |  the patch passed  |
| +1 :green_heart: |  compile  |   2m 13s |  the patch passed with JDK Ubuntu-11.0.16+8-post-Ubuntu-0ubuntu120.04  |
| +1 :green_heart: |  javac  |   2m 13s |  the patch passed  |
| +1 :green_heart: |  compile  |   1m 54s |  the patch passed with JDK Private Build-1.8.0_342-8u342-b07-0ubuntu1~20.04-b07  |
| +1 :green_heart: |  javac  |   1m 54s |  the patch passed  |
| +1 :green_heart: |  checkstyle  |   1m 18s |  the patch passed  |
| +1 :green_heart: |  whitespace  |   0m  0s |  The patch has no whitespace issues.  |
| +1 :green_heart: |  javadoc  |   1m 46s |  the patch passed with JDK Ubuntu-11.0.16+8-post-Ubuntu-0ubuntu120.04  |
| +1 :green_heart: |  javadoc  |   1m 40s |  the patch passed with JDK Private Build-1.8.0_342-8u342-b07-0ubuntu1~20.04-b07  |
| +1 :green_heart: |  findbugs  |   4m 48s |  the patch passed  |
||| _ Other Tests _ |
| +1 :green_heart: |  unit  |   2m 16s |  tez-api in the patch passed.  |
| +1 :green_heart: |  unit  |   4m 58s |  tez-runtime-library in the patch passed.  |
| +1 :green_heart: |  unit  |   1m 20s |  tez-mapreduce in the patch passed.  |
| +1 :green_heart: |  unit  |   5m  8s |  tez-dag in the patch passed.  |
| +1 :green_heart: |  unit  |  37m 53s |  tez-tests in the patch passed.  |
| +1 :green_heart: |  asflicense  |   1m  5s |  The patch does not generate ASF License warnings.  |
|  |   | 109m 44s |   |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.41 ServerAPI=1.41 base: https://ci-hadoop.apache.org/job/tez-multibranch/job/PR-239/3/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/tez/pull/239 |
| JIRA Issue | TEZ-4447 |
| Optional Tests | dupname asflicense javac javadoc unit spotbugs findbugs checkstyle compile |
| uname | Linux 37efe7c97736 4.15.0-191-generic #202-Ubuntu SMP Thu Aug 4 01:49:29 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | personality/tez.sh |
| git revision | master / 55b6031fa |
| Default Java | Private Build-1.8.0_342-8u342-b07-0ubuntu1~20.04-b07 |
| Multi-JDK versions | /usr/lib/jvm/java-11-openjdk-amd64:Ubuntu-11.0.16+8-post-Ubuntu-0ubuntu120.04 /usr/lib/jvm/java-8-openjdk-amd64:Private Build-1.8.0_342-8u342-b07-0ubuntu1~20.04-b07 |
|  Test Results | https://ci-hadoop.apache.org/job/tez-multibranch/job/PR-239/3/testReport/ |
| Max. process+thread count | 1186 (vs. ulimit of 5500) |
| modules | C: tez-api tez-runtime-library tez-mapreduce tez-dag tez-tests U: . |
| Console output | https://ci-hadoop.apache.org/job/tez-multibranch/job/PR-239/3/console |
| versions | git=2.25.1 maven=3.6.3 findbugs=3.0.1 |
| Powered by | Apache Yetus 0.12.0 https://yetus.apache.org |


This message was automatically generated.

**Comment by rbalamohan** [comment]
I went through the changes. Core change is related to how "getVertexStatus" is obtained for DAGClientImplLocal. 

LGTM. +1.

**Comment by abstractdog** [comment]
yes, absolutely, thanks @rbalamohan  for the review!
I also tested this in the scope of [HIVE-26445](https://issues.apache.org/jira/browse/HIVE-26445)

**Pull request merged**
