### PR TITLE
TEZ-4526: Avoid calling LocationProvider#getPreferredLocations multiple times while generating grouped splits

### PR DESCRIPTION
**Pull request by SourabhBadhya**
TEZ-4526: Avoid calling LocationProvider#getPreferredLocations multiple times while generating grouped splits

### CODE REVIEW

**Comment by tez-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| +0 :ok: |  reexec  |  26m 20s |  Docker mode activated.  |
||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  0s |  No case conflicting files found.  |
| +1 :green_heart: |  @author  |   0m  0s |  The patch does not contain any @author tags.  |
| -1 :x: |  test4tests  |   0m  0s |  The patch doesn't appear to include any new or modified tests. Please justify why no new tests are needed for this patch. Also please list what manual steps were performed to verify this patch.  |
||| _ master Compile Tests _ |
| +1 :green_heart: |  mvninstall  |  17m 10s |  master passed  |
| +1 :green_heart: |  compile  |   0m 31s |  master passed with JDK Ubuntu-11.0.21+9-post-Ubuntu-0ubuntu122.04  |
| +1 :green_heart: |  compile  |   0m 29s |  master passed with JDK Private Build-1.8.0_392-8u392-ga-1~22.04-b08  |
| +1 :green_heart: |  checkstyle  |   1m 20s |  master passed  |
| +1 :green_heart: |  javadoc  |   0m 42s |  master passed with JDK Ubuntu-11.0.21+9-post-Ubuntu-0ubuntu122.04  |
| +1 :green_heart: |  javadoc  |   0m 27s |  master passed with JDK Private Build-1.8.0_392-8u392-ga-1~22.04-b08  |
| +0 :ok: |  spotbugs  |   1m 20s |  Used deprecated FindBugs config; considering switching to SpotBugs.  |
| +1 :green_heart: |  findbugs  |   1m 19s |  master passed  |
||| _ Patch Compile Tests _ |
| +1 :green_heart: |  mvninstall  |   0m 19s |  the patch passed  |
| +1 :green_heart: |  compile  |   0m 19s |  the patch passed with JDK Ubuntu-11.0.21+9-post-Ubuntu-0ubuntu122.04  |
| +1 :green_heart: |  javac  |   0m 19s |  the patch passed  |
| +1 :green_heart: |  compile  |   0m 17s |  the patch passed with JDK Private Build-1.8.0_392-8u392-ga-1~22.04-b08  |
| +1 :green_heart: |  javac  |   0m 17s |  the patch passed  |
| +1 :green_heart: |  checkstyle  |   0m 11s |  tez-mapreduce: The patch generated 0 new + 15 unchanged - 1 fixed = 15 total (was 16)  |
| +1 :green_heart: |  whitespace  |   0m  0s |  The patch has no whitespace issues.  |
| +1 :green_heart: |  javadoc  |   0m 17s |  the patch passed with JDK Ubuntu-11.0.21+9-post-Ubuntu-0ubuntu122.04  |
| +1 :green_heart: |  javadoc  |   0m 15s |  the patch passed with JDK Private Build-1.8.0_392-8u392-ga-1~22.04-b08  |
| +1 :green_heart: |  findbugs  |   0m 45s |  the patch passed  |
||| _ Other Tests _ |
| +1 :green_heart: |  unit  |   1m 29s |  tez-mapreduce in the patch passed.  |
| +1 :green_heart: |  asflicense  |   0m 18s |  The patch does not generate ASF License warnings.  |
|  |   |  53m 25s |   |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.43 ServerAPI=1.43 base: https://ci-hadoop.apache.org/job/tez-multibranch/job/PR-323/1/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/tez/pull/323 |
| JIRA Issue | TEZ-4526 |
| Optional Tests | dupname asflicense javac javadoc unit spotbugs findbugs checkstyle compile |
| uname | Linux 7316f1ac2dc5 5.15.0-88-generic #98-Ubuntu SMP Mon Oct 2 15:18:56 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | personality/tez.sh |
| git revision | master / 0c5cf6886 |
| Default Java | Private Build-1.8.0_392-8u392-ga-1~22.04-b08 |
| Multi-JDK versions | /usr/lib/jvm/java-11-openjdk-amd64:Ubuntu-11.0.21+9-post-Ubuntu-0ubuntu122.04 /usr/lib/jvm/java-8-openjdk-amd64:Private Build-1.8.0_392-8u392-ga-1~22.04-b08 |
|  Test Results | https://ci-hadoop.apache.org/job/tez-multibranch/job/PR-323/1/testReport/ |
| Max. process+thread count | 226 (vs. ulimit of 5500) |
| modules | C: tez-mapreduce U: tez-mapreduce |
| Console output | https://ci-hadoop.apache.org/job/tez-multibranch/job/PR-323/1/console |
| versions | git=2.34.1 maven=3.6.3 findbugs=3.0.1 |
| Powered by | Apache Yetus 0.12.0 https://yetus.apache.org |


This message was automatically generated.

**Comment by SourabhBadhya** [comment]
Requesting @rbalamohan @abstractdog for reviews.

**Comment by tez-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| +0 :ok: |  reexec  |  22m  9s |  Docker mode activated.  |
||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  0s |  No case conflicting files found.  |
| +1 :green_heart: |  @author  |   0m  0s |  The patch does not contain any @author tags.  |
| -1 :x: |  test4tests  |   0m  0s |  The patch doesn't appear to include any new or modified tests. Please justify why no new tests are needed for this patch. Also please list what manual steps were performed to verify this patch.  |
||| _ master Compile Tests _ |
| +1 :green_heart: |  mvninstall  |  15m 44s |  master passed  |
| +1 :green_heart: |  compile  |   0m 31s |  master passed with JDK Ubuntu-11.0.21+9-post-Ubuntu-0ubuntu122.04  |
| +1 :green_heart: |  compile  |   0m 30s |  master passed with JDK Private Build-1.8.0_392-8u392-ga-1~22.04-b08  |
| +1 :green_heart: |  checkstyle  |   1m 22s |  master passed  |
| +1 :green_heart: |  javadoc  |   0m 41s |  master passed with JDK Ubuntu-11.0.21+9-post-Ubuntu-0ubuntu122.04  |
| +1 :green_heart: |  javadoc  |   0m 27s |  master passed with JDK Private Build-1.8.0_392-8u392-ga-1~22.04-b08  |
| +0 :ok: |  spotbugs  |   1m 20s |  Used deprecated FindBugs config; considering switching to SpotBugs.  |
| +1 :green_heart: |  findbugs  |   1m 18s |  master passed  |
||| _ Patch Compile Tests _ |
| +1 :green_heart: |  mvninstall  |   0m 19s |  the patch passed  |
| +1 :green_heart: |  compile  |   0m 19s |  the patch passed with JDK Ubuntu-11.0.21+9-post-Ubuntu-0ubuntu122.04  |
| +1 :green_heart: |  javac  |   0m 19s |  the patch passed  |
| +1 :green_heart: |  compile  |   0m 18s |  the patch passed with JDK Private Build-1.8.0_392-8u392-ga-1~22.04-b08  |
| +1 :green_heart: |  javac  |   0m 18s |  the patch passed  |
| +1 :green_heart: |  checkstyle  |   0m 10s |  tez-mapreduce: The patch generated 0 new + 15 unchanged - 1 fixed = 15 total (was 16)  |
| +1 :green_heart: |  whitespace  |   0m  0s |  The patch has no whitespace issues.  |
| +1 :green_heart: |  javadoc  |   0m 17s |  the patch passed with JDK Ubuntu-11.0.21+9-post-Ubuntu-0ubuntu122.04  |
| +1 :green_heart: |  javadoc  |   0m 15s |  the patch passed with JDK Private Build-1.8.0_392-8u392-ga-1~22.04-b08  |
| +1 :green_heart: |  findbugs  |   0m 44s |  the patch passed  |
||| _ Other Tests _ |
| +1 :green_heart: |  unit  |   1m 33s |  tez-mapreduce in the patch passed.  |
| +1 :green_heart: |  asflicense  |   0m 16s |  The patch does not generate ASF License warnings.  |
|  |   |  47m 49s |   |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.43 ServerAPI=1.43 base: https://ci-hadoop.apache.org/job/tez-multibranch/job/PR-323/2/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/tez/pull/323 |
| JIRA Issue | TEZ-4526 |
| Optional Tests | dupname asflicense javac javadoc unit spotbugs findbugs checkstyle compile |
| uname | Linux 5b3a0ef9aa5f 5.15.0-88-generic #98-Ubuntu SMP Mon Oct 2 15:18:56 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | personality/tez.sh |
| git revision | master / 0c5cf6886 |
| Default Java | Private Build-1.8.0_392-8u392-ga-1~22.04-b08 |
| Multi-JDK versions | /usr/lib/jvm/java-11-openjdk-amd64:Ubuntu-11.0.21+9-post-Ubuntu-0ubuntu122.04 /usr/lib/jvm/java-8-openjdk-amd64:Private Build-1.8.0_392-8u392-ga-1~22.04-b08 |
|  Test Results | https://ci-hadoop.apache.org/job/tez-multibranch/job/PR-323/2/testReport/ |
| Max. process+thread count | 243 (vs. ulimit of 5500) |
| modules | C: tez-mapreduce U: tez-mapreduce |
| Console output | https://ci-hadoop.apache.org/job/tez-multibranch/job/PR-323/2/console |
| versions | git=2.34.1 maven=3.6.3 findbugs=3.0.1 |
| Powered by | Apache Yetus 0.12.0 https://yetus.apache.org |


This message was automatically generated.

**Comment by SourabhBadhya** [comment]
Time taken for grouping splits - Generated 30000 file splits and generated 1000 grouped splits with each grouped split having 30 file splits.
| Without patch  | With patch |
| ------------- | ------------- |
| 0.095s  |  0.078s |
| 0.08s |  0.081s |
| 0.081s | 0.078s |

I dont see a regression happening with the patch. I think I have addressed the regression comments on [TEZ-4069](https://issues.apache.org/jira/browse/TEZ-4069?focusedCommentId=17399946&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-17399946).

**Review by abstractdog — APPROVED** [review]
LGTM, thanks for the perf testing!

**Pull request merged**
