### PR TITLE
we have installed hadoop 3.2.X and hive 3.1.2 and tez installed 0.10

### PR DESCRIPTION
**Pull request by abinanths**
we have installed hadoop 3.2.X and hive 3.1.2 and tez installed 0.10

getting below error 

2021-06-30 10:15:45,132 [ERROR] [main] |app.DAGAppMaster|: Error starting DAGAppMaster
java.lang.NoSuchMethodError: com.google.common.base.Preconditions.checkArgument(ZLjava/lang/String;Ljava/lang/Object;)V
	at org.apache.hadoop.conf.Configuration.set(Configuration.java:1357)
	at org.apache.hadoop.conf.Configuration.set(Configuration.java:1338)
	at org.apache.tez.common.TezUtilsInternal.addUserSpecifiedTezConfiguration(TezUtilsInternal.java:84)
	at org.apache.tez.dag.app.DAGAppMaster.main(DAGAppMaster.java:2396)

### CODE REVIEW

**Comment by jteagles** [comment]
Something about this PR isn't correct as there are 58 commits. Are you targeting the correct branch?

**Comment by soliverr** [comment]
I found workaround here: https://issues.apache.org/jira/browse/TEZ-4074

**Comment by jteagles** [comment]
Given the work around should this PR be closed in favor of TEZ-4074 ?

**Comment by abstractdog** [comment]
closing this PR as it seems to have lots of noise and there is no Jira ticket mentioned
please reopen if you're about to work on this @abinanths 
recommended hive+tez combinations are: hive 3.x + tez 0.9.2, hive 4 (alpha currently) + tez 0.10.2

**Pull request closed without merging**
