### PR TITLE
TEZ-4542: Tez application may fail due to int overflow when record size is large and sort memory is low.

### PR DESCRIPTION
**Pull request by zhengchenyu**
See [TEZ-4542](https://issues.apache.org/jira/browse/TEZ-4542) for details.

### CODE REVIEW

**Comment by zhengchenyu** [comment]
@abstractdog @rbalamohan 
Can you please review this PR?

**Comment by tez-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| +0 :ok: |  reexec  |   0m 10s |  Docker mode activated.  |
||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  0s |  No case conflicting files found.  |
| +1 :green_heart: |  @author  |   0m  0s |  The patch does not contain any @author tags.  |
| +1 :green_heart: |  test4tests  |   0m  0s |  The patch appears to include 1 new or modified test files.  |
||| _ master Compile Tests _ |
| -1 :x: |  mvninstall  |   0m 18s |  root in master failed.  |
| -1 :x: |  compile  |   0m 19s |  tez-runtime-library in master failed with JDK Ubuntu-11.0.21+9-post-Ubuntu-0ubuntu122.04.  |
| -1 :x: |  compile  |   0m 18s |  tez-runtime-library in master failed with JDK Private Build-1.8.0_392-8u392-ga-1~22.04-b08.  |
| -0 :warning: |  checkstyle  |   0m 17s |  The patch fails to run checkstyle in tez-runtime-library  |
| -1 :x: |  javadoc  |   0m 18s |  tez-runtime-library in master failed with JDK Ubuntu-11.0.21+9-post-Ubuntu-0ubuntu122.04.  |
| -1 :x: |  javadoc  |   0m 18s |  tez-runtime-library in master failed with JDK Private Build-1.8.0_392-8u392-ga-1~22.04-b08.  |
| +0 :ok: |  spotbugs  |   1m 13s |  Used deprecated FindBugs config; considering switching to SpotBugs.  |
| -1 :x: |  findbugs  |   0m 18s |  tez-runtime-library in master failed.  |
||| _ Patch Compile Tests _ |
| -1 :x: |  mvninstall  |   0m 19s |  tez-runtime-library in the patch failed.  |
| -1 :x: |  compile  |   0m 18s |  tez-runtime-library in the patch failed with JDK Ubuntu-11.0.21+9-post-Ubuntu-0ubuntu122.04.  |
| -1 :x: |  javac  |   0m 18s |  tez-runtime-library in the patch failed with JDK Ubuntu-11.0.21+9-post-Ubuntu-0ubuntu122.04.  |
| -1 :x: |  compile  |   0m 18s |  tez-runtime-library in the patch failed with JDK Private Build-1.8.0_392-8u392-ga-1~22.04-b08.  |
| -1 :x: |  javac  |   0m 18s |  tez-runtime-library in the patch failed with JDK Private Build-1.8.0_392-8u392-ga-1~22.04-b08.  |
| -0 :warning: |  checkstyle  |   0m 16s |  The patch fails to run checkstyle in tez-runtime-library  |
| +1 :green_heart: |  whitespace  |   0m  0s |  The patch has no whitespace issues.  |
| -1 :x: |  javadoc  |   0m 18s |  tez-runtime-library in the patch failed with JDK Ubuntu-11.0.21+9-post-Ubuntu-0ubuntu122.04.  |
| -1 :x: |  javadoc  |   0m 17s |  tez-runtime-library in the patch failed with JDK Private Build-1.8.0_392-8u392-ga-1~22.04-b08.  |
| -1 :x: |  findbugs  |   0m 18s |  tez-runtime-library in the patch failed.  |
||| _ Other Tests _ |
| -1 :x: |  unit  |   4m 40s |  tez-runtime-library in the patch failed.  |
| +0 :ok: |  asflicense  |   1m  2s |  ASF License check generated no output?  |
|  |   |  10m 34s |   |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.44 ServerAPI=1.44 base: https://ci-hadoop.apache.org/job/tez-multibranch/job/PR-336/2/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/tez/pull/336 |
| JIRA Issue | TEZ-4542 |
| Optional Tests | dupname asflicense javac javadoc unit spotbugs findbugs checkstyle compile |
| uname | Linux a64fb9be0413 5.15.0-94-generic #104-Ubuntu SMP Tue Jan 9 15:25:40 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | personality/tez.sh |
| git revision | master / f8c2e11d0 |
| Default Java | Private Build-1.8.0_392-8u392-ga-1~22.04-b08 |
| Multi-JDK versions | /usr/lib/jvm/java-11-openjdk-amd64:Ubuntu-11.0.21+9-post-Ubuntu-0ubuntu122.04 /usr/lib/jvm/java-8-openjdk-amd64:Private Build-1.8.0_392-8u392-ga-1~22.04-b08 |
| mvninstall | https://ci-hadoop.apache.org/job/tez-multibranch/job/PR-336/2/artifact/out/branch-mvninstall-root.txt |
| compile | https://ci-hadoop.apache.org/job/tez-multibranch/job/PR-336/2/artifact/out/branch-compile-tez-runtime-library-jdkUbuntu-11.0.21+9-post-Ubuntu-0ubuntu122.04.txt |
| compile | https://ci-hadoop.apache.org/job/tez-multibranch/job/PR-336/2/artifact/out/branch-compile-tez-runtime-library-jdkPrivateBuild-1.8.0_392-8u392-ga-1~22.04-b08.txt |
| checkstyle | https://ci-hadoop.apache.org/job/tez-multibranch/job/PR-336/2/artifact/out/buildtool-branch-checkstyle-tez-runtime-library.txt |
| javadoc | https://ci-hadoop.apache.org/job/tez-multibranch/job/PR-336/2/artifact/out/branch-javadoc-tez-runtime-library-jdkUbuntu-11.0.21+9-post-Ubuntu-0ubuntu122.04.txt |
| javadoc | https://ci-hadoop.apache.org/job/tez-multibranch/job/PR-336/2/artifact/out/branch-javadoc-tez-runtime-library-jdkPrivateBuild-1.8.0_392-8u392-ga-1~22.04-b08.txt |
| findbugs | https://ci-hadoop.apache.org/job/tez-multibranch/job/PR-336/2/artifact/out/branch-findbugs-tez-runtime-library.txt |
| mvninstall | https://ci-hadoop.apache.org/job/tez-multibranch/job/PR-336/2/artifact/out/patch-mvninstall-tez-runtime-library.txt |
| compile | https://ci-hadoop.apache.org/job/tez-multibranch/job/PR-336/2/artifact/out/patch-compile-tez-runtime-library-jdkUbuntu-11.0.21+9-post-Ubuntu-0ubuntu122.04.txt |
| javac | https://ci-hadoop.apache.org/job/tez-multibranch/job/PR-336/2/artifact/out/patch-compile-tez-runtime-library-jdkUbuntu-11.0.21+9-post-Ubuntu-0ubuntu122.04.txt |
| compile | https://ci-hadoop.apache.org/job/tez-multibranch/job/PR-336/2/artifact/out/patch-compile-tez-runtime-library-jdkPrivateBuild-1.8.0_392-8u392-ga-1~22.04-b08.txt |
| javac | https://ci-hadoop.apache.org/job/tez-multibranch/job/PR-336/2/artifact/out/patch-compile-tez-runtime-library-jdkPrivateBuild-1.8.0_392-8u392-ga-1~22.04-b08.txt |
| checkstyle | https://ci-hadoop.apache.org/job/tez-multibranch/job/PR-336/2/artifact/out/buildtool-patch-checkstyle-tez-runtime-library.txt |
| javadoc | https://ci-hadoop.apache.org/job/tez-multibranch/job/PR-336/2/artifact/out/patch-javadoc-tez-runtime-library-jdkUbuntu-11.0.21+9-post-Ubuntu-0ubuntu122.04.txt |
| javadoc | https://ci-hadoop.apache.org/job/tez-multibranch/job/PR-336/2/artifact/out/patch-javadoc-tez-runtime-library-jdkPrivateBuild-1.8.0_392-8u392-ga-1~22.04-b08.txt |
| findbugs | https://ci-hadoop.apache.org/job/tez-multibranch/job/PR-336/2/artifact/out/patch-findbugs-tez-runtime-library.txt |
| unit | https://ci-hadoop.apache.org/job/tez-multibranch/job/PR-336/2/artifact/out/patch-unit-tez-runtime-library.txt |
|  Test Results | https://ci-hadoop.apache.org/job/tez-multibranch/job/PR-336/2/testReport/ |
| Max. process+thread count | 51 (vs. ulimit of 5500) |
| modules | C: tez-runtime-library U: tez-runtime-library |
| Console output | https://ci-hadoop.apache.org/job/tez-multibranch/job/PR-336/2/console |
| versions | git=2.34.1 maven=3.6.3 |
| Powered by | Apache Yetus 0.12.0 https://yetus.apache.org |


This message was automatically generated.

**Comment by tez-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| +0 :ok: |  reexec  |   0m 10s |  Docker mode activated.  |
||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  0s |  No case conflicting files found.  |
| +1 :green_heart: |  @author  |   0m  0s |  The patch does not contain any @author tags.  |
| +1 :green_heart: |  test4tests  |   0m  0s |  The patch appears to include 1 new or modified test files.  |
||| _ master Compile Tests _ |
| -1 :x: |  mvninstall  |   4m  1s |  root in master failed.  |
| -1 :x: |  compile  |   0m 18s |  tez-runtime-library in master failed with JDK Ubuntu-11.0.21+9-post-Ubuntu-0ubuntu122.04.  |
| -1 :x: |  compile  |   0m 18s |  tez-runtime-library in master failed with JDK Private Build-1.8.0_392-8u392-ga-1~22.04-b08.  |
| -0 :warning: |  checkstyle  |   1m 24s |  The patch fails to run checkstyle in tez-runtime-library  |
| -1 :x: |  javadoc  |   0m 18s |  tez-runtime-library in master failed with JDK Ubuntu-11.0.21+9-post-Ubuntu-0ubuntu122.04.  |
| +1 :green_heart: |  javadoc  |   3m 21s |  master passed with JDK Private Build-1.8.0_392-8u392-ga-1~22.04-b08  |
| +0 :ok: |  spotbugs  |   5m 19s |  Used deprecated FindBugs config; considering switching to SpotBugs.  |
| -1 :x: |  findbugs  |   0m 14s |  tez-runtime-library in master failed.  |
||| _ Patch Compile Tests _ |
| +1 :green_heart: |  mvninstall  |   0m 37s |  the patch passed  |
| +1 :green_heart: |  compile  |   0m 16s |  the patch passed with JDK Ubuntu-11.0.21+9-post-Ubuntu-0ubuntu122.04  |
| -1 :x: |  javac  |   0m 16s |  tez-runtime-library-jdkUbuntu-11.0.21+9-post-Ubuntu-0ubuntu122.04 with JDK Ubuntu-11.0.21+9-post-Ubuntu-0ubuntu122.04 generated 4 new + 0 unchanged - 0 fixed = 4 total (was 0)  |
| +1 :green_heart: |  compile  |   0m 13s |  the patch passed with JDK Private Build-1.8.0_392-8u392-ga-1~22.04-b08  |
| -1 :x: |  javac  |   0m 13s |  tez-runtime-library-jdkPrivateBuild-1.8.0_392-8u392-ga-1~22.04-b08 with JDK Private Build-1.8.0_392-8u392-ga-1~22.04-b08 generated 4 new + 0 unchanged - 0 fixed = 4 total (was 0)  |
| -0 :warning: |  checkstyle  |   0m 46s |  tez-runtime-library: The patch generated 115 new + 0 unchanged - 0 fixed = 115 total (was 0)  |
| +1 :green_heart: |  whitespace  |   0m  0s |  The patch has no whitespace issues.  |
| -1 :x: |  javadoc  |   0m 12s |  tez-runtime-library-jdkUbuntu-11.0.21+9-post-Ubuntu-0ubuntu122.04 with JDK Ubuntu-11.0.21+9-post-Ubuntu-0ubuntu122.04 generated 15 new + 0 unchanged - 0 fixed = 15 total (was 0)  |
| +1 :green_heart: |  javadoc  |   0m 11s |  the patch passed with JDK Private Build-1.8.0_392-8u392-ga-1~22.04-b08  |
| +1 :green_heart: |  findbugs  |   1m 19s |  the patch passed  |
||| _ Other Tests _ |
| -1 :x: |  unit  |   6m 19s |  tez-runtime-library in the patch failed.  |
| +1 :green_heart: |  asflicense  |   0m 16s |  The patch does not generate ASF License warnings.  |
|  |   |  20m 35s |   |


| Reason | Tests |
|-------:|:------|
| Failed junit tests | tez.runtime.library.utils.TestCodecUtils |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.44 ServerAPI=1.44 base: https://ci-hadoop.apache.org/job/tez-multibranch/job/PR-336/3/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/tez/pull/336 |
| JIRA Issue | TEZ-4542 |
| Optional Tests | dupname asflicense javac javadoc unit spotbugs findbugs checkstyle compile |
| uname | Linux ee9c142d5102 5.15.0-94-generic #104-Ubuntu SMP Tue Jan 9 15:25:40 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | personality/tez.sh |
| git revision | master / f8c2e11d0 |
| Default Java | Private Build-1.8.0_392-8u392-ga-1~22.04-b08 |
| Multi-JDK versions | /usr/lib/jvm/java-11-openjdk-amd64:Ubuntu-11.0.21+9-post-Ubuntu-0ubuntu122.04 /usr/lib/jvm/java-8-openjdk-amd64:Private Build-1.8.0_392-8u392-ga-1~22.04-b08 |
| mvninstall | https://ci-hadoop.apache.org/job/tez-multibranch/job/PR-336/3/artifact/out/branch-mvninstall-root.txt |
| compile | https://ci-hadoop.apache.org/job/tez-multibranch/job/PR-336/3/artifact/out/branch-compile-tez-runtime-library-jdkUbuntu-11.0.21+9-post-Ubuntu-0ubuntu122.04.txt |
| compile | https://ci-hadoop.apache.org/job/tez-multibranch/job/PR-336/3/artifact/out/branch-compile-tez-runtime-library-jdkPrivateBuild-1.8.0_392-8u392-ga-1~22.04-b08.txt |
| checkstyle | https://ci-hadoop.apache.org/job/tez-multibranch/job/PR-336/3/artifact/out/buildtool-branch-checkstyle-tez-runtime-library.txt |
| javadoc | https://ci-hadoop.apache.org/job/tez-multibranch/job/PR-336/3/artifact/out/branch-javadoc-tez-runtime-library-jdkUbuntu-11.0.21+9-post-Ubuntu-0ubuntu122.04.txt |
| findbugs | https://ci-hadoop.apache.org/job/tez-multibranch/job/PR-336/3/artifact/out/branch-findbugs-tez-runtime-library.txt |
| javac | https://ci-hadoop.apache.org/job/tez-multibranch/job/PR-336/3/artifact/out/diff-compile-javac-tez-runtime-library-jdkUbuntu-11.0.21+9-post-Ubuntu-0ubuntu122.04.txt |
| javac | https://ci-hadoop.apache.org/job/tez-multibranch/job/PR-336/3/artifact/out/diff-compile-javac-tez-runtime-library-jdkPrivateBuild-1.8.0_392-8u392-ga-1~22.04-b08.txt |
| checkstyle | https://ci-hadoop.apache.org/job/tez-multibranch/job/PR-336/3/artifact/out/diff-checkstyle-tez-runtime-library.txt |
| javadoc | https://ci-hadoop.apache.org/job/tez-multibranch/job/PR-336/3/artifact/out/diff-javadoc-javadoc-tez-runtime-library-jdkUbuntu-11.0.21+9-post-Ubuntu-0ubuntu122.04.txt |
| unit | https://ci-hadoop.apache.org/job/tez-multibranch/job/PR-336/3/artifact/out/patch-unit-tez-runtime-library.txt |
|  Test Results | https://ci-hadoop.apache.org/job/tez-multibranch/job/PR-336/3/testReport/ |
| Max. process+thread count | 1100 (vs. ulimit of 5500) |
| modules | C: tez-runtime-library U: tez-runtime-library |
| Console output | https://ci-hadoop.apache.org/job/tez-multibranch/job/PR-336/3/console |
| versions | git=2.34.1 maven=3.6.3 |
| Powered by | Apache Yetus 0.12.0 https://yetus.apache.org |


This message was automatically generated.

**Comment by zhengchenyu** [comment]
@abstractdog @rbalamohan Can you please review this PR?

**Comment by tez-yetus** [comment]
:confetti_ball: **+1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| +0 :ok: |  reexec  |  24m 13s |  Docker mode activated.  |
||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  0s |  No case conflicting files found.  |
| +1 :green_heart: |  @author  |   0m  0s |  The patch does not contain any @author tags.  |
| +1 :green_heart: |  test4tests  |   0m  0s |  The patch appears to include 1 new or modified test files.  |
||| _ master Compile Tests _ |
| +1 :green_heart: |  mvninstall  |  16m 35s |  master passed  |
| +1 :green_heart: |  compile  |   0m 36s |  master passed with JDK Ubuntu-11.0.21+9-post-Ubuntu-0ubuntu122.04  |
| +1 :green_heart: |  compile  |   0m 34s |  master passed with JDK Private Build-1.8.0_392-8u392-ga-1~22.04-b08  |
| +1 :green_heart: |  checkstyle  |   1m 31s |  master passed  |
| +1 :green_heart: |  javadoc  |   0m 49s |  master passed with JDK Ubuntu-11.0.21+9-post-Ubuntu-0ubuntu122.04  |
| +1 :green_heart: |  javadoc  |   0m 31s |  master passed with JDK Private Build-1.8.0_392-8u392-ga-1~22.04-b08  |
| +0 :ok: |  spotbugs  |   1m 42s |  Used deprecated FindBugs config; considering switching to SpotBugs.  |
| +1 :green_heart: |  findbugs  |   1m 40s |  master passed  |
||| _ Patch Compile Tests _ |
| +1 :green_heart: |  mvninstall  |   0m 22s |  the patch passed  |
| +1 :green_heart: |  compile  |   0m 23s |  the patch passed with JDK Ubuntu-11.0.21+9-post-Ubuntu-0ubuntu122.04  |
| +1 :green_heart: |  javac  |   0m 23s |  the patch passed  |
| +1 :green_heart: |  compile  |   0m 20s |  the patch passed with JDK Private Build-1.8.0_392-8u392-ga-1~22.04-b08  |
| +1 :green_heart: |  javac  |   0m 20s |  the patch passed  |
| +1 :green_heart: |  checkstyle  |   0m 17s |  the patch passed  |
| +1 :green_heart: |  whitespace  |   0m  0s |  The patch has no whitespace issues.  |
| +1 :green_heart: |  javadoc  |   0m 19s |  the patch passed with JDK Ubuntu-11.0.21+9-post-Ubuntu-0ubuntu122.04  |
| +1 :green_heart: |  javadoc  |   0m 18s |  the patch passed with JDK Private Build-1.8.0_392-8u392-ga-1~22.04-b08  |
| +1 :green_heart: |  findbugs  |   0m 57s |  the patch passed  |
||| _ Other Tests _ |
| +1 :green_heart: |  unit  |   9m 27s |  tez-runtime-library in the patch passed.  |
| +1 :green_heart: |  asflicense  |   0m 18s |  The patch does not generate ASF License warnings.  |
|  |   |  60m 10s |   |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.44 ServerAPI=1.44 base: https://ci-hadoop.apache.org/job/tez-multibranch/job/PR-336/4/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/tez/pull/336 |
| JIRA Issue | TEZ-4542 |
| Optional Tests | dupname asflicense javac javadoc unit spotbugs findbugs checkstyle compile |
| uname | Linux e6c6a2d8c92f 5.15.0-91-generic #101-Ubuntu SMP Tue Nov 14 13:30:08 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | personality/tez.sh |
| git revision | master / f8c2e11d0 |
| Default Java | Private Build-1.8.0_392-8u392-ga-1~22.04-b08 |
| Multi-JDK versions | /usr/lib/jvm/java-11-openjdk-amd64:Ubuntu-11.0.21+9-post-Ubuntu-0ubuntu122.04 /usr/lib/jvm/java-8-openjdk-amd64:Private Build-1.8.0_392-8u392-ga-1~22.04-b08 |
|  Test Results | https://ci-hadoop.apache.org/job/tez-multibranch/job/PR-336/4/testReport/ |
| Max. process+thread count | 2100 (vs. ulimit of 5500) |
| modules | C: tez-runtime-library U: tez-runtime-library |
| Console output | https://ci-hadoop.apache.org/job/tez-multibranch/job/PR-336/4/console |
| versions | git=2.34.1 maven=3.6.3 findbugs=3.0.1 |
| Powered by | Apache Yetus 0.12.0 https://yetus.apache.org |


This message was automatically generated.

**Comment by zhengchenyu** [comment]
@abstractdog Can you please review this PR?

**Comment by abstractdog** [comment]
the affected lines were touch by @rbalamohan in the past frequently, he is the pipelined sorted expert, is there a chance you can take a look on this tiny patch?

**Comment by rbalamohan** [comment]
LGTM. +1.

BTW, pipelinesorter is the brainchild of @t3rmin4t0r .  :)

**Pull request merged**
