### PR TITLE
TEZ-4310: Avoid duplicated precommit comments

### PR DESCRIPTION
**Pull request by abstractdog**

### CODE REVIEW

**Comment by tez-yetus** [comment]
:confetti_ball: **+1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| +0 :ok: |  reexec  |  12m 53s |  Docker mode activated.  |
||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  0s |  No case conflicting files found.  |
| +0 :ok: |  shelldocs  |   0m  0s |  Shelldocs was not available.  |
| +1 :green_heart: |  @author  |   0m  0s |  The patch does not contain any @author tags.  |
||| _ master Compile Tests _ |
||| _ Patch Compile Tests _ |
| +1 :green_heart: |  shellcheck  |   0m  0s |  There were no new shellcheck issues.  |
| +1 :green_heart: |  whitespace  |   0m  1s |  The patch has no whitespace issues.  |
||| _ Other Tests _ |
| +1 :green_heart: |  asflicense  |   1m  2s |  The patch does not generate ASF License warnings.  |
|  |   |  14m 38s |   |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.41 ServerAPI=1.41 base: https://ci-hadoop.apache.org/job/tez-multibranch/job/PR-176/1/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/tez/pull/176 |
| JIRA Issue | TEZ-4310 |
| Optional Tests | dupname asflicense shellcheck shelldocs |
| uname | Linux be2f097da1eb 4.15.0-161-generic #169-Ubuntu SMP Fri Oct 15 13:41:54 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | personality/tez.sh |
| git revision | master / 41cbc17aa |
| Max. process+thread count | 51 (vs. ulimit of 5500) |
| modules | C: . U: . |
| Console output | https://ci-hadoop.apache.org/job/tez-multibranch/job/PR-176/1/console |
| versions | git=2.25.1 maven=3.6.3 shellcheck=0.7.1 |
| Powered by | Apache Yetus 0.12.0 https://yetus.apache.org |


This message was automatically generated.

**Comment by abstractdog** [comment]
can you approve this change @jteagles? looks like it's working:
1. the comment made by tez-yetus hasn't gone back to jira (no duplicates)
2. the jira has kept successfully linked to this PR

**Review by jteagles — APPROVED** [review]
+1

**Comment by abstractdog** [comment]
let me check, I'm opening a PR against branch-0.9

**Pull request merged**
