### PR TITLE
TEZ-4473: Remove pointless MDC_LOGGING message from logs if there is no custom MDC key.

### PR DESCRIPTION
**Pull request by ayushtkn**

### CODE REVIEW

**Comment by tez-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| +0 :ok: |  reexec  |  25m 58s |  Docker mode activated.  |
||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  0s |  No case conflicting files found.  |
| +1 :green_heart: |  @author  |   0m  0s |  The patch does not contain any @author tags.  |
| -1 :x: |  test4tests  |   0m  0s |  The patch doesn't appear to include any new or modified tests. Please justify why no new tests are needed for this patch. Also please list what manual steps were performed to verify this patch.  |
||| _ master Compile Tests _ |
| +0 :ok: |  mvndep  |   6m  3s |  Maven dependency ordering for branch  |
| -1 :x: |  mvninstall  |   8m 51s |  root in master failed.  |
| +1 :green_heart: |  compile  |   0m 43s |  master passed with JDK Ubuntu-11.0.19+7-post-Ubuntu-0ubuntu122.04.1  |
| +1 :green_heart: |  compile  |   0m 39s |  master passed with JDK Private Build-1.8.0_362-8u372-ga~us1-0ubuntu1~22.04-b09  |
| +1 :green_heart: |  checkstyle  |   0m 47s |  master passed  |
| +1 :green_heart: |  javadoc  |   0m 57s |  master passed with JDK Ubuntu-11.0.19+7-post-Ubuntu-0ubuntu122.04.1  |
| +1 :green_heart: |  javadoc  |   0m 38s |  master passed with JDK Private Build-1.8.0_362-8u372-ga~us1-0ubuntu1~22.04-b09  |
| +0 :ok: |  spotbugs  |   0m 31s |  Used deprecated FindBugs config; considering switching to SpotBugs.  |
| +1 :green_heart: |  findbugs  |   1m 44s |  master passed  |
||| _ Patch Compile Tests _ |
| +0 :ok: |  mvndep  |   0m 10s |  Maven dependency ordering for patch  |
| +1 :green_heart: |  mvninstall  |   0m 37s |  the patch passed  |
| +1 :green_heart: |  compile  |   0m 39s |  the patch passed with JDK Ubuntu-11.0.19+7-post-Ubuntu-0ubuntu122.04.1  |
| +1 :green_heart: |  javac  |   0m 39s |  the patch passed  |
| +1 :green_heart: |  compile  |   0m 35s |  the patch passed with JDK Private Build-1.8.0_362-8u372-ga~us1-0ubuntu1~22.04-b09  |
| +1 :green_heart: |  javac  |   0m 35s |  the patch passed  |
| +1 :green_heart: |  checkstyle  |   0m 22s |  the patch passed  |
| +1 :green_heart: |  whitespace  |   0m  0s |  The patch has no whitespace issues.  |
| +1 :green_heart: |  javadoc  |   0m 34s |  the patch passed with JDK Ubuntu-11.0.19+7-post-Ubuntu-0ubuntu122.04.1  |
| +1 :green_heart: |  javadoc  |   0m 35s |  the patch passed with JDK Private Build-1.8.0_362-8u372-ga~us1-0ubuntu1~22.04-b09  |
| +1 :green_heart: |  findbugs  |   1m 39s |  the patch passed  |
||| _ Other Tests _ |
| +1 :green_heart: |  unit  |   2m 18s |  tez-api in the patch passed.  |
| +1 :green_heart: |  unit  |   0m 26s |  tez-common in the patch passed.  |
| +1 :green_heart: |  asflicense  |   0m 24s |  The patch does not generate ASF License warnings.  |
|  |   |  55m 43s |   |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.43 ServerAPI=1.43 base: https://ci-hadoop.apache.org/job/tez-multibranch/job/PR-294/1/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/tez/pull/294 |
| JIRA Issue | TEZ-4473 |
| Optional Tests | dupname asflicense javac javadoc unit spotbugs findbugs checkstyle compile |
| uname | Linux f741bbafba3b 4.15.0-212-generic #223-Ubuntu SMP Tue May 23 13:09:22 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | personality/tez.sh |
| git revision | master / d20f3347d |
| Default Java | Private Build-1.8.0_362-8u372-ga~us1-0ubuntu1~22.04-b09 |
| Multi-JDK versions | /usr/lib/jvm/java-11-openjdk-amd64:Ubuntu-11.0.19+7-post-Ubuntu-0ubuntu122.04.1 /usr/lib/jvm/java-8-openjdk-amd64:Private Build-1.8.0_362-8u372-ga~us1-0ubuntu1~22.04-b09 |
| mvninstall | https://ci-hadoop.apache.org/job/tez-multibranch/job/PR-294/1/artifact/out/branch-mvninstall-root.txt |
|  Test Results | https://ci-hadoop.apache.org/job/tez-multibranch/job/PR-294/1/testReport/ |
| Max. process+thread count | 422 (vs. ulimit of 5500) |
| modules | C: tez-api tez-common U: . |
| Console output | https://ci-hadoop.apache.org/job/tez-multibranch/job/PR-294/1/console |
| versions | git=2.34.1 maven=3.6.3 findbugs=3.0.1 |
| Powered by | Apache Yetus 0.12.0 https://yetus.apache.org |


This message was automatically generated.

**Comment by tez-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| +0 :ok: |  reexec  |  26m  0s |  Docker mode activated.  |
||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  0s |  No case conflicting files found.  |
| +1 :green_heart: |  @author  |   0m  0s |  The patch does not contain any @author tags.  |
| -1 :x: |  test4tests  |   0m  0s |  The patch doesn't appear to include any new or modified tests. Please justify why no new tests are needed for this patch. Also please list what manual steps were performed to verify this patch.  |
||| _ master Compile Tests _ |
| +0 :ok: |  mvndep  |   6m  1s |  Maven dependency ordering for branch  |
| +1 :green_heart: |  mvninstall  |  12m 27s |  master passed  |
| +1 :green_heart: |  compile  |   1m 10s |  master passed with JDK Ubuntu-11.0.19+7-post-Ubuntu-0ubuntu122.04.1  |
| +1 :green_heart: |  compile  |   1m  9s |  master passed with JDK Private Build-1.8.0_362-8u372-ga~us1-0ubuntu1~22.04-b09  |
| +1 :green_heart: |  checkstyle  |   1m 17s |  master passed  |
| +1 :green_heart: |  javadoc  |   1m 20s |  master passed with JDK Ubuntu-11.0.19+7-post-Ubuntu-0ubuntu122.04.1  |
| +1 :green_heart: |  javadoc  |   1m 10s |  master passed with JDK Private Build-1.8.0_362-8u372-ga~us1-0ubuntu1~22.04-b09  |
| +0 :ok: |  spotbugs  |   0m 47s |  Used deprecated FindBugs config; considering switching to SpotBugs.  |
| +1 :green_heart: |  findbugs  |   2m 19s |  master passed  |
||| _ Patch Compile Tests _ |
| +0 :ok: |  mvndep  |   0m 10s |  Maven dependency ordering for patch  |
| +1 :green_heart: |  mvninstall  |   0m 38s |  the patch passed  |
| +1 :green_heart: |  compile  |   0m 39s |  the patch passed with JDK Ubuntu-11.0.19+7-post-Ubuntu-0ubuntu122.04.1  |
| +1 :green_heart: |  javac  |   0m 39s |  the patch passed  |
| +1 :green_heart: |  compile  |   0m 34s |  the patch passed with JDK Private Build-1.8.0_362-8u372-ga~us1-0ubuntu1~22.04-b09  |
| +1 :green_heart: |  javac  |   0m 34s |  the patch passed  |
| +1 :green_heart: |  checkstyle  |   0m 22s |  the patch passed  |
| +1 :green_heart: |  whitespace  |   0m  0s |  The patch has no whitespace issues.  |
| +1 :green_heart: |  javadoc  |   0m 34s |  the patch passed with JDK Ubuntu-11.0.19+7-post-Ubuntu-0ubuntu122.04.1  |
| +1 :green_heart: |  javadoc  |   0m 34s |  the patch passed with JDK Private Build-1.8.0_362-8u372-ga~us1-0ubuntu1~22.04-b09  |
| +1 :green_heart: |  findbugs  |   1m 36s |  the patch passed  |
||| _ Other Tests _ |
| +1 :green_heart: |  unit  |   2m 18s |  tez-api in the patch passed.  |
| +1 :green_heart: |  unit  |   0m 27s |  tez-common in the patch passed.  |
| +1 :green_heart: |  asflicense  |   0m 24s |  The patch does not generate ASF License warnings.  |
|  |   |  62m 40s |   |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.43 ServerAPI=1.43 base: https://ci-hadoop.apache.org/job/tez-multibranch/job/PR-294/2/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/tez/pull/294 |
| JIRA Issue | TEZ-4473 |
| Optional Tests | dupname asflicense javac javadoc unit spotbugs findbugs checkstyle compile |
| uname | Linux 7f857fc8594b 4.15.0-212-generic #223-Ubuntu SMP Tue May 23 13:09:22 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | personality/tez.sh |
| git revision | master / d20f3347d |
| Default Java | Private Build-1.8.0_362-8u372-ga~us1-0ubuntu1~22.04-b09 |
| Multi-JDK versions | /usr/lib/jvm/java-11-openjdk-amd64:Ubuntu-11.0.19+7-post-Ubuntu-0ubuntu122.04.1 /usr/lib/jvm/java-8-openjdk-amd64:Private Build-1.8.0_362-8u372-ga~us1-0ubuntu1~22.04-b09 |
|  Test Results | https://ci-hadoop.apache.org/job/tez-multibranch/job/PR-294/2/testReport/ |
| Max. process+thread count | 592 (vs. ulimit of 5500) |
| modules | C: tez-api tez-common U: . |
| Console output | https://ci-hadoop.apache.org/job/tez-multibranch/job/PR-294/2/console |
| versions | git=2.34.1 maven=3.6.3 findbugs=3.0.1 |
| Powered by | Apache Yetus 0.12.0 https://yetus.apache.org |


This message was automatically generated.

**Comment by ayushtkn** [comment]
The reason for the change lies here:
https://issues.apache.org/jira/browse/TEZ-4473?focusedCommentId=17735558&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-17735558

Th conf.getStrings(..,..) creates issues: The method description from the hadoop-code

https://github.com/apache/hadoop/blob/cebcb44d377710db6d4cff45f0b956f5a3372f51/hadoop-common-project/hadoop-common/src/main/java/org/apache/hadoop/conf/Configuration.java#L2317-L2322

In case of ``null`` it returns the default value, which screws up the subsequent checks below

**Review by abstractdog — APPROVED** [review]
+1

**Pull request merged**
