### PR TITLE
TEZ-4524 - Upgrade commons-codec to 1.15

### PR DESCRIPTION
**Pull request by BilwaST**

### CODE REVIEW

**Comment by tez-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| +0 :ok: |  reexec  |  26m 23s |  Docker mode activated.  |
||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  0s |  No case conflicting files found.  |
| +1 :green_heart: |  @author  |   0m  0s |  The patch does not contain any @author tags.  |
| -1 :x: |  test4tests  |   0m  0s |  The patch doesn't appear to include any new or modified tests. Please justify why no new tests are needed for this patch. Also please list what manual steps were performed to verify this patch.  |
||| _ master Compile Tests _ |
| +1 :green_heart: |  mvninstall  |  17m 51s |  master passed  |
| +1 :green_heart: |  compile  |   2m 17s |  master passed with JDK Ubuntu-11.0.21+9-post-Ubuntu-0ubuntu122.04  |
| +1 :green_heart: |  compile  |   2m  6s |  master passed with JDK Private Build-1.8.0_392-8u392-ga-1~22.04-b08  |
| +1 :green_heart: |  javadoc  |   1m 42s |  master passed with JDK Ubuntu-11.0.21+9-post-Ubuntu-0ubuntu122.04  |
| +1 :green_heart: |  javadoc  |   1m 10s |  master passed with JDK Private Build-1.8.0_392-8u392-ga-1~22.04-b08  |
||| _ Patch Compile Tests _ |
| +1 :green_heart: |  mvninstall  |   4m  1s |  the patch passed  |
| +1 :green_heart: |  compile  |   2m 16s |  the patch passed with JDK Ubuntu-11.0.21+9-post-Ubuntu-0ubuntu122.04  |
| +1 :green_heart: |  javac  |   2m 16s |  the patch passed  |
| +1 :green_heart: |  compile  |   2m  4s |  the patch passed with JDK Private Build-1.8.0_392-8u392-ga-1~22.04-b08  |
| +1 :green_heart: |  javac  |   2m  4s |  the patch passed  |
| +1 :green_heart: |  whitespace  |   0m  0s |  The patch has no whitespace issues.  |
| +1 :green_heart: |  xml  |   0m  2s |  The patch has no ill-formed XML file.  |
| +1 :green_heart: |  javadoc  |   1m 11s |  the patch passed with JDK Ubuntu-11.0.21+9-post-Ubuntu-0ubuntu122.04  |
| +1 :green_heart: |  javadoc  |   1m  9s |  the patch passed with JDK Private Build-1.8.0_392-8u392-ga-1~22.04-b08  |
||| _ Other Tests _ |
| -1 :x: |  unit  |  16m  8s |  root in the patch failed.  |
| +1 :green_heart: |  asflicense  |   0m 36s |  The patch does not generate ASF License warnings.  |
|  |   |  80m  3s |   |


| Reason | Tests |
|-------:|:------|
| Failed junit tests | tez.dag.app.TestSpeculation |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.43 ServerAPI=1.43 base: https://ci-hadoop.apache.org/job/tez-multibranch/job/PR-321/1/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/tez/pull/321 |
| Optional Tests | dupname asflicense javac javadoc unit xml compile |
| uname | Linux d481752fbfd3 5.15.0-88-generic #98-Ubuntu SMP Mon Oct 2 15:18:56 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | personality/tez.sh |
| git revision | master / 0c5cf6886 |
| Default Java | Private Build-1.8.0_392-8u392-ga-1~22.04-b08 |
| Multi-JDK versions | /usr/lib/jvm/java-11-openjdk-amd64:Ubuntu-11.0.21+9-post-Ubuntu-0ubuntu122.04 /usr/lib/jvm/java-8-openjdk-amd64:Private Build-1.8.0_392-8u392-ga-1~22.04-b08 |
| unit | https://ci-hadoop.apache.org/job/tez-multibranch/job/PR-321/1/artifact/out/patch-unit-root.txt |
|  Test Results | https://ci-hadoop.apache.org/job/tez-multibranch/job/PR-321/1/testReport/ |
| Max. process+thread count | 2100 (vs. ulimit of 5500) |
| modules | C: . U: . |
| Console output | https://ci-hadoop.apache.org/job/tez-multibranch/job/PR-321/1/console |
| versions | git=2.34.1 maven=3.6.3 |
| Powered by | Apache Yetus 0.12.0 https://yetus.apache.org |


This message was automatically generated.

**Comment by abstractdog** [comment]
@BilwaST thanks for the patch
can you please check if the failures are related to this upgrade?

**Comment by BilwaST** [comment]
I ran the failed UT locally and it passes. Its not related to my changes. Thank you

**Comment by abstractdog** [comment]
TestSpeculation is flaky sometimes, I'll check and if it passes for me too, we can merge this I believe

**Comment by ayushtkn** [comment]
I ran the test locally with this PR & it is passing for me
```
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running org.apache.tez.dag.app.TestSpeculation
[INFO] Tests run: 10, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 25.274 s - in org.apache.tez.dag.app.TestSpeculation
[INFO] 
[INFO] Results:
[INFO] 
[INFO] Tests run: 10, Failures: 0, Errors: 0, Skipped: 0

```

**Comment by abstractdog** [comment]
cool, +1

**Review by abstractdog — APPROVED** [review]

**Pull request merged**
