### PR TITLE
TEZ-4431: Apache Tez Release 0.10.2: update SNAPSHOT versions, DOAP file

### PR DESCRIPTION
**Pull request by abstractdog**

### CODE REVIEW

**Comment by tez-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| +0 :ok: |  reexec  |  32m 51s |  Docker mode activated.  |
||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  0s |  No case conflicting files found.  |
| +1 :green_heart: |  @author  |   0m  0s |  The patch does not contain any @author tags.  |
| -1 :x: |  test4tests  |   0m  0s |  The patch doesn't appear to include any new or modified tests. Please justify why no new tests are needed for this patch. Also please list what manual steps were performed to verify this patch.  |
||| _ master Compile Tests _ |
| +0 :ok: |  mvndep  |   6m 45s |  Maven dependency ordering for branch  |
| +1 :green_heart: |  mvninstall  |   9m 32s |  master passed  |
| +1 :green_heart: |  compile  |  26m 53s |  master passed with JDK Private Build-11.0.15+10-Ubuntu-0ubuntu0.20.04.1  |
| +1 :green_heart: |  compile  |  25m 47s |  master passed with JDK Private Build-1.8.0_312-8u312-b07-0ubuntu1~20.04-b07  |
| +1 :green_heart: |  javadoc  |  24m 40s |  master passed with JDK Private Build-11.0.15+10-Ubuntu-0ubuntu0.20.04.1  |
| +1 :green_heart: |  javadoc  |  23m 15s |  master passed with JDK Private Build-1.8.0_312-8u312-b07-0ubuntu1~20.04-b07  |
||| _ Patch Compile Tests _ |
| +1 :green_heart: |  mvninstall  |   3m 53s |  master passed  |
| +0 :ok: |  mvndep  |   4m 42s |  Maven dependency ordering for patch  |
| +1 :green_heart: |  mvninstall  |  29m 41s |  the patch passed  |
| +1 :green_heart: |  compile  |  26m 38s |  the patch passed with JDK Private Build-11.0.15+10-Ubuntu-0ubuntu0.20.04.1  |
| +1 :green_heart: |  javac  |  26m 38s |  the patch passed  |
| +1 :green_heart: |  compile  |  25m 30s |  the patch passed with JDK Private Build-1.8.0_312-8u312-b07-0ubuntu1~20.04-b07  |
| +1 :green_heart: |  javac  |  25m 30s |  the patch passed  |
| +1 :green_heart: |  whitespace  |   0m  0s |  The patch has no whitespace issues.  |
| +1 :green_heart: |  xml  |   0m 40s |  The patch has no ill-formed XML file.  |
| +1 :green_heart: |  javadoc  |  24m 28s |  the patch passed with JDK Private Build-11.0.15+10-Ubuntu-0ubuntu0.20.04.1  |
| +1 :green_heart: |  javadoc  |  23m 12s |  the patch passed with JDK Private Build-1.8.0_312-8u312-b07-0ubuntu1~20.04-b07  |
||| _ Other Tests _ |
| +1 :green_heart: |  unit  |   0m 49s |  hadoop-shim in the patch passed.  |
| +1 :green_heart: |  unit  |   2m 35s |  tez-api in the patch passed.  |
| +1 :green_heart: |  unit  |   0m 40s |  tez-build-tools in the patch passed.  |
| +1 :green_heart: |  unit  |   0m 55s |  tez-common in the patch passed.  |
| +1 :green_heart: |  unit  |   1m  6s |  tez-runtime-internals in the patch passed.  |
| +1 :green_heart: |  unit  |   5m 53s |  tez-runtime-library in the patch passed.  |
| +1 :green_heart: |  unit  |   1m 50s |  tez-mapreduce in the patch passed.  |
| +1 :green_heart: |  unit  |   0m 45s |  tez-examples in the patch passed.  |
| +1 :green_heart: |  unit  |   5m 44s |  tez-dag in the patch passed.  |
| +1 :green_heart: |  unit  |  40m 29s |  tez-tests in the patch passed.  |
| +1 :green_heart: |  unit  |   4m 44s |  tez-ext-service-tests in the patch passed.  |
| +1 :green_heart: |  unit  |   1m 58s |  tez-ui in the patch passed.  |
| +1 :green_heart: |  unit  |   9m 55s |  tez-plugins in the patch passed.  |
| +1 :green_heart: |  unit  |   1m  1s |  tez-protobuf-history-plugin in the patch passed.  |
| +1 :green_heart: |  unit  |   2m 11s |  tez-yarn-timeline-history in the patch passed.  |
| +1 :green_heart: |  unit  |   2m 26s |  tez-yarn-timeline-history-with-acls in the patch passed.  |
| +1 :green_heart: |  unit  |   0m 52s |  tez-yarn-timeline-cache-plugin in the patch passed.  |
| +1 :green_heart: |  unit  |   2m 11s |  tez-yarn-timeline-history-with-fs in the patch passed.  |
| +1 :green_heart: |  unit  |   3m  0s |  tez-history-parser in the patch passed.  |
| +1 :green_heart: |  unit  |   3m 20s |  tez-aux-services in the patch passed.  |
| +1 :green_heart: |  unit  |   3m 25s |  tez-tools in the patch passed.  |
| +1 :green_heart: |  unit  |   3m 18s |  analyzers in the patch passed.  |
| +1 :green_heart: |  unit  |   3m 23s |  job-analyzer in the patch passed.  |
| +1 :green_heart: |  unit  |   0m 50s |  tez-javadoc-tools in the patch passed.  |
| +1 :green_heart: |  unit  |   0m 52s |  hadoop-shim-impls in the patch passed.  |
| +1 :green_heart: |  unit  |   0m 52s |  hadoop-shim-2.8 in the patch passed.  |
| +1 :green_heart: |  unit  |   0m 50s |  tez-dist in the patch passed.  |
| +1 :green_heart: |  unit  |   0m 46s |  docs in the patch passed.  |
| +1 :green_heart: |  unit  |  72m 13s |  root in the patch passed.  |
| +1 :green_heart: |  unit  |   0m 51s |  hadoop-shim-2.7 in the patch passed.  |
| +1 :green_heart: |  unit  |   0m 51s |  tez-tfile-parser in the patch passed.  |
| +1 :green_heart: |  asflicense  |  19m 46s |  The patch does not generate ASF License warnings.  |
|  |   | 490m 39s |   |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.41 ServerAPI=1.41 base: https://ci-hadoop.apache.org/job/tez-multibranch/job/PR-234/1/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/tez/pull/234 |
| JIRA Issue | TEZ-4431 |
| Optional Tests | dupname asflicense javac javadoc unit xml compile |
| uname | Linux d658837938cc 4.15.0-175-generic #184-Ubuntu SMP Thu Mar 24 17:48:36 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | personality/tez.sh |
| git revision | master / 5e31e4d97 |
| Default Java | Private Build-1.8.0_312-8u312-b07-0ubuntu1~20.04-b07 |
| Multi-JDK versions | /usr/lib/jvm/java-11-openjdk-amd64:Private Build-11.0.15+10-Ubuntu-0ubuntu0.20.04.1 /usr/lib/jvm/java-8-openjdk-amd64:Private Build-1.8.0_312-8u312-b07-0ubuntu1~20.04-b07 |
|  Test Results | https://ci-hadoop.apache.org/job/tez-multibranch/job/PR-234/1/testReport/ |
| Max. process+thread count | 2099 (vs. ulimit of 5500) |
| modules | C: hadoop-shim tez-api tez-build-tools tez-common tez-runtime-internals tez-runtime-library tez-mapreduce tez-examples tez-dag tez-tests tez-ext-service-tests tez-ui tez-plugins tez-plugins/tez-protobuf-history-plugin tez-plugins/tez-yarn-timeline-history tez-plugins/tez-yarn-timeline-history-with-acls tez-plugins/tez-yarn-timeline-cache-plugin tez-plugins/tez-yarn-timeline-history-with-fs tez-plugins/tez-history-parser tez-plugins/tez-aux-services tez-tools tez-tools/analyzers tez-tools/analyzers/job-analyzer tez-tools/tez-javadoc-tools hadoop-shim-impls hadoop-shim-impls/hadoop-shim-2.8 tez-dist docs . hadoop-shim-impls/hadoop-shim-2.7 tez-tools/tez-tfile-parser U: . |
| Console output | https://ci-hadoop.apache.org/job/tez-multibranch/job/PR-234/1/console |
| versions | git=2.25.1 maven=3.6.3 |
| Powered by | Apache Yetus 0.12.0 https://yetus.apache.org |


This message was automatically generated.

**Review by ayushtkn — APPROVED** [review]
LGTM

**Comment by abstractdog** [comment]
thanks @ayushtkn!
can I have a committer approval on this @rbalamohan? tez 0.10.2 is already released, this is just the usual post-release work

**Comment by rbalamohan** [comment]
LGTM. +1

**Pull request merged**
