### PR TITLE
TEZ-4467: Migrate from Travis CI to GitHub Actions - pt2: remove .travis.yml

### PR DESCRIPTION
**Pull request by abstractdog**

### CODE REVIEW

**Comment by tez-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| +0 :ok: |  reexec  |   0m 41s |  Docker mode activated.  |
||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  0s |  No case conflicting files found.  |
| +1 :green_heart: |  @author  |   0m  0s |  The patch does not contain any @author tags.  |
||| _ master Compile Tests _ |
||| _ Patch Compile Tests _ |
| +1 :green_heart: |  whitespace  |   0m  0s |  The patch has no whitespace issues.  |
| -1 :x: |  yamllint  |   0m  1s |  The patch generated 2 new + 1 unchanged - 1 fixed = 3 total (was 2)  |
||| _ Other Tests _ |
| +1 :green_heart: |  asflicense  |   1m  3s |  The patch does not generate ASF License warnings.  |
|  |   |   2m 28s |   |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.42 ServerAPI=1.42 base: https://ci-hadoop.apache.org/job/tez-multibranch/job/PR-269/1/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/tez/pull/269 |
| JIRA Issue | TEZ-4467 |
| Optional Tests | dupname asflicense yamllint |
| uname | Linux 5a2b95467676 4.15.0-200-generic #211-Ubuntu SMP Thu Nov 24 18:16:04 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | personality/tez.sh |
| git revision | master / 97cc788ce |
| yamllint | https://ci-hadoop.apache.org/job/tez-multibranch/job/PR-269/1/artifact/out/diff-patch-yamllint.txt |
| Max. process+thread count | 51 (vs. ulimit of 5500) |
| modules | C: . U: . |
| Console output | https://ci-hadoop.apache.org/job/tez-multibranch/job/PR-269/1/console |
| versions | git=2.34.1 maven=3.6.3 yamllint=1.24.2 |
| Powered by | Apache Yetus 0.12.0 https://yetus.apache.org |


This message was automatically generated.

**Comment by tez-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| +0 :ok: |  reexec  |   0m 39s |  Docker mode activated.  |
||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  0s |  No case conflicting files found.  |
| +1 :green_heart: |  @author  |   0m  0s |  The patch does not contain any @author tags.  |
||| _ master Compile Tests _ |
||| _ Patch Compile Tests _ |
| +1 :green_heart: |  whitespace  |   0m  0s |  The patch has no whitespace issues.  |
| -1 :x: |  yamllint  |   0m  1s |  The patch generated 1 new + 1 unchanged - 1 fixed = 2 total (was 2)  |
||| _ Other Tests _ |
| +1 :green_heart: |  asflicense  |   1m  1s |  The patch does not generate ASF License warnings.  |
|  |   |   2m 23s |   |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.42 ServerAPI=1.42 base: https://ci-hadoop.apache.org/job/tez-multibranch/job/PR-269/2/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/tez/pull/269 |
| JIRA Issue | TEZ-4467 |
| Optional Tests | dupname asflicense yamllint |
| uname | Linux 22b1543549fb 4.15.0-200-generic #211-Ubuntu SMP Thu Nov 24 18:16:04 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | personality/tez.sh |
| git revision | master / 97cc788ce |
| yamllint | https://ci-hadoop.apache.org/job/tez-multibranch/job/PR-269/2/artifact/out/diff-patch-yamllint.txt |
| Max. process+thread count | 51 (vs. ulimit of 5500) |
| modules | C: . U: . |
| Console output | https://ci-hadoop.apache.org/job/tez-multibranch/job/PR-269/2/console |
| versions | git=2.34.1 maven=3.6.3 yamllint=1.24.2 |
| Powered by | Apache Yetus 0.12.0 https://yetus.apache.org |


This message was automatically generated.

**Comment by tez-yetus** [comment]
:confetti_ball: **+1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| +0 :ok: |  reexec  |   0m 35s |  Docker mode activated.  |
||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  0s |  No case conflicting files found.  |
| +1 :green_heart: |  @author  |   0m  0s |  The patch does not contain any @author tags.  |
||| _ master Compile Tests _ |
||| _ Patch Compile Tests _ |
| +1 :green_heart: |  whitespace  |   0m  0s |  The patch has no whitespace issues.  |
| +1 :green_heart: |  yamllint  |   0m  1s |  The patch generated 0 new + 0 unchanged - 2 fixed = 0 total (was 2)  |
||| _ Other Tests _ |
| +1 :green_heart: |  asflicense  |   1m  1s |  The patch does not generate ASF License warnings.  |
|  |   |   2m 21s |   |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.42 ServerAPI=1.42 base: https://ci-hadoop.apache.org/job/tez-multibranch/job/PR-269/5/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/tez/pull/269 |
| JIRA Issue | TEZ-4467 |
| Optional Tests | dupname asflicense yamllint |
| uname | Linux ff2ae3c9b0e7 4.15.0-200-generic #211-Ubuntu SMP Thu Nov 24 18:16:04 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | personality/tez.sh |
| git revision | master / be994890d |
| Max. process+thread count | 46 (vs. ulimit of 5500) |
| modules | C: . U: . |
| Console output | https://ci-hadoop.apache.org/job/tez-multibranch/job/PR-269/5/console |
| versions | git=2.34.1 maven=3.6.3 yamllint=1.24.2 |
| Powered by | Apache Yetus 0.12.0 https://yetus.apache.org |


This message was automatically generated.

**Comment by tez-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| +0 :ok: |  reexec  |   0m 39s |  Docker mode activated.  |
||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  0s |  No case conflicting files found.  |
| +1 :green_heart: |  @author  |   0m  0s |  The patch does not contain any @author tags.  |
| -1 :x: |  test4tests  |   0m  0s |  The patch doesn't appear to include any new or modified tests. Please justify why no new tests are needed for this patch. Also please list what manual steps were performed to verify this patch.  |
||| _ master Compile Tests _ |
| +1 :green_heart: |  mvninstall  |  15m 39s |  master passed  |
| +1 :green_heart: |  compile  |   2m 16s |  master passed with JDK Ubuntu-11.0.17+8-post-Ubuntu-1ubuntu222.04  |
| +1 :green_heart: |  compile  |   2m  8s |  master passed with JDK Private Build-1.8.0_352-8u352-ga-1~22.04-b08  |
| +1 :green_heart: |  javadoc  |   2m 36s |  master passed with JDK Ubuntu-11.0.17+8-post-Ubuntu-1ubuntu222.04  |
| +1 :green_heart: |  javadoc  |   1m 50s |  master passed with JDK Private Build-1.8.0_352-8u352-ga-1~22.04-b08  |
||| _ Patch Compile Tests _ |
| +1 :green_heart: |  mvninstall  |   3m 59s |  the patch passed  |
| +1 :green_heart: |  compile  |   2m 12s |  the patch passed with JDK Ubuntu-11.0.17+8-post-Ubuntu-1ubuntu222.04  |
| +1 :green_heart: |  javac  |   2m 12s |  the patch passed  |
| +1 :green_heart: |  compile  |   1m 58s |  the patch passed with JDK Private Build-1.8.0_352-8u352-ga-1~22.04-b08  |
| +1 :green_heart: |  javac  |   1m 58s |  the patch passed  |
| +1 :green_heart: |  whitespace  |   0m  0s |  The patch has no whitespace issues.  |
| +1 :green_heart: |  xml  |   0m  1s |  The patch has no ill-formed XML file.  |
| +1 :green_heart: |  yamllint  |   0m  0s |  The patch generated 0 new + 0 unchanged - 2 fixed = 0 total (was 2)  |
| +1 :green_heart: |  javadoc  |   2m  3s |  the patch passed with JDK Ubuntu-11.0.17+8-post-Ubuntu-1ubuntu222.04  |
| +1 :green_heart: |  javadoc  |   1m 45s |  the patch passed with JDK Private Build-1.8.0_352-8u352-ga-1~22.04-b08  |
||| _ Other Tests _ |
| +1 :green_heart: |  unit  |  73m 22s |  root in the patch passed.  |
| +1 :green_heart: |  asflicense  |   0m 39s |  The patch does not generate ASF License warnings.  |
|  |   | 112m 14s |   |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.42 ServerAPI=1.42 base: https://ci-hadoop.apache.org/job/tez-multibranch/job/PR-269/4/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/tez/pull/269 |
| JIRA Issue | TEZ-4467 |
| Optional Tests | dupname asflicense javac javadoc unit xml compile yamllint |
| uname | Linux 2151293f45d3 4.15.0-200-generic #211-Ubuntu SMP Thu Nov 24 18:16:04 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | personality/tez.sh |
| git revision | master / be994890d |
| Default Java | Private Build-1.8.0_352-8u352-ga-1~22.04-b08 |
| Multi-JDK versions | /usr/lib/jvm/java-11-openjdk-amd64:Ubuntu-11.0.17+8-post-Ubuntu-1ubuntu222.04 /usr/lib/jvm/java-8-openjdk-amd64:Private Build-1.8.0_352-8u352-ga-1~22.04-b08 |
|  Test Results | https://ci-hadoop.apache.org/job/tez-multibranch/job/PR-269/4/testReport/ |
| Max. process+thread count | 1923 (vs. ulimit of 5500) |
| modules | C: . U: . |
| Console output | https://ci-hadoop.apache.org/job/tez-multibranch/job/PR-269/4/console |
| versions | git=2.34.1 maven=3.6.3 yamllint=1.24.2 |
| Powered by | Apache Yetus 0.12.0 https://yetus.apache.org |


This message was automatically generated.

**Comment by abstractdog** [comment]
can you please approve this one @rbalamohan, @jteagles?
here is the history:
1. I needed to merge another PR to see GitHub actions in action :) that's why it successfully kicked off 4 different Build CI steps here (https://github.com/apache/tez/pull/270)
2. this PR is about to remove .travis.yml
3. also confirmed that the background precommit test runs (see results above)

travis is EOL from Feb15, so please review and let me merge this one

**Comment by abstractdog** [comment]
please someone review, this is already working on master, we should cleanup the old travis.yml

**Review by ayushtkn — APPROVED** [review]
LGTM
Travis CI is gone, good to cleanup

**Comment by abstractdog** [comment]
> LGTM Travis CI is gone, good to cleanup

thanks @ayushtkn  for the review!
I'm about to merge this even with the absence of a tez committer review, this is an obvious cleanup task

**Comment by ayushtkn** [comment]
hmm, no say in project maters but worth exploring CTR for Tez
https://www.apache.org/foundation/glossary.html#CommitThenReview

**Comment by ayushtkn** [comment]
yetus does that: https://www.mail-archive.com/dev@yetus.apache.org/msg01319.html

**Comment by abstractdog** [comment]
thanks @ayushtkn  for taking a look
CTR is definitely the way to go in case of Tez considering the current state of the community, let me think about that

**Pull request merged**
