### PR TITLE
TEZ-4557: Revert TEZ-4303, NoClassDefFoundError because of missing httpclient jar

### PR DESCRIPTION
**Pull request by Aggarwal-Raghav**
Please refer to [TEZ-4557](https://issues.apache.org/jira/browse/TEZ-4557), for error stacktrace.

### CODE REVIEW

**Comment by tez-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| +0 :ok: |  reexec  |  23m 22s |  Docker mode activated.  |
||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  0s |  No case conflicting files found.  |
| +1 :green_heart: |  @author  |   0m  0s |  The patch does not contain any @author tags.  |
| -1 :x: |  test4tests  |   0m  0s |  The patch doesn't appear to include any new or modified tests. Please justify why no new tests are needed for this patch. Also please list what manual steps were performed to verify this patch.  |
||| _ master Compile Tests _ |
| +1 :green_heart: |  mvninstall  |  17m 39s |  master passed  |
| +1 :green_heart: |  compile  |   2m 13s |  master passed with JDK Ubuntu-11.0.22+7-post-Ubuntu-0ubuntu222.04.1  |
| +1 :green_heart: |  compile  |   2m  4s |  master passed with JDK Private Build-1.8.0_402-8u402-ga-2ubuntu1~22.04-b06  |
| +1 :green_heart: |  javadoc  |   1m 43s |  master passed with JDK Ubuntu-11.0.22+7-post-Ubuntu-0ubuntu222.04.1  |
| +1 :green_heart: |  javadoc  |   1m  8s |  master passed with JDK Private Build-1.8.0_402-8u402-ga-2ubuntu1~22.04-b06  |
||| _ Patch Compile Tests _ |
| +1 :green_heart: |  mvninstall  |   4m 15s |  the patch passed  |
| +1 :green_heart: |  compile  |   2m 13s |  the patch passed with JDK Ubuntu-11.0.22+7-post-Ubuntu-0ubuntu222.04.1  |
| +1 :green_heart: |  javac  |   2m 13s |  the patch passed  |
| +1 :green_heart: |  compile  |   2m  4s |  the patch passed with JDK Private Build-1.8.0_402-8u402-ga-2ubuntu1~22.04-b06  |
| +1 :green_heart: |  javac  |   2m  4s |  the patch passed  |
| +1 :green_heart: |  whitespace  |   0m  0s |  The patch has no whitespace issues.  |
| +1 :green_heart: |  xml  |   0m  1s |  The patch has no ill-formed XML file.  |
| +1 :green_heart: |  javadoc  |   1m 11s |  the patch passed with JDK Ubuntu-11.0.22+7-post-Ubuntu-0ubuntu222.04.1  |
| +1 :green_heart: |  javadoc  |   1m  8s |  the patch passed with JDK Private Build-1.8.0_402-8u402-ga-2ubuntu1~22.04-b06  |
||| _ Other Tests _ |
| -1 :x: |  unit  |  49m 17s |  root in the patch failed.  |
| +1 :green_heart: |  asflicense  |   0m 38s |  The patch does not generate ASF License warnings.  |
|  |   | 110m  7s |   |


| Reason | Tests |
|-------:|:------|
| Failed junit tests | tez.test.TestDAGRecovery |
|   | tez.test.TestAMRecovery |
|   | tez.test.TestRecovery |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.44 ServerAPI=1.44 base: https://ci-hadoop.apache.org/job/tez-multibranch/job/PR-349/1/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/tez/pull/349 |
| JIRA Issue | TEZ-4557 |
| Optional Tests | dupname asflicense javac javadoc unit xml compile |
| uname | Linux 8a1bc3b622ac 5.15.0-94-generic #104-Ubuntu SMP Tue Jan 9 15:25:40 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | personality/tez.sh |
| git revision | master / a77f8ef9f |
| Default Java | Private Build-1.8.0_402-8u402-ga-2ubuntu1~22.04-b06 |
| Multi-JDK versions | /usr/lib/jvm/java-11-openjdk-amd64:Ubuntu-11.0.22+7-post-Ubuntu-0ubuntu222.04.1 /usr/lib/jvm/java-8-openjdk-amd64:Private Build-1.8.0_402-8u402-ga-2ubuntu1~22.04-b06 |
| unit | https://ci-hadoop.apache.org/job/tez-multibranch/job/PR-349/1/artifact/out/patch-unit-root.txt |
|  Test Results | https://ci-hadoop.apache.org/job/tez-multibranch/job/PR-349/1/testReport/ |
| Max. process+thread count | 1322 (vs. ulimit of 5500) |
| modules | C: . U: . |
| Console output | https://ci-hadoop.apache.org/job/tez-multibranch/job/PR-349/1/console |
| versions | git=2.34.1 maven=3.6.3 |
| Powered by | Apache Yetus 0.12.0 https://yetus.apache.org |


This message was automatically generated.

**Comment by Aggarwal-Raghav** [comment]
@abstractdog, can you please review this?

**Comment by abstractdog** [comment]
> @abstractdog, can you please review this?

according to my [jira comment](https://issues.apache.org/jira/browse/TEZ-4557?focusedCommentId=17859483&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-17859483), I'm about to approve this
can you rebase your PR on top of master @Aggarwal-Raghav to get a green precommit test run

**Comment by Aggarwal-Raghav** [comment]
Rebased. Thanks for the review @abstractdog.

**Comment by Aggarwal-Raghav** [comment]
Will force push the commit again, as there is failure in git workflows. Error seems unrelated to the patch.
`Error:  Failed to execute goal com.github.eirslett:frontend-maven-plugin:1.8.0:install-node-and-yarn (install node and yarn) on project tez-ui: Could not download Node.js: Got error code 500 from the server. -> [Help 1]`

**Comment by tez-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| +0 :ok: |  reexec  |  21m 55s |  Docker mode activated.  |
||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  0s |  No case conflicting files found.  |
| +1 :green_heart: |  @author  |   0m  0s |  The patch does not contain any @author tags.  |
| -1 :x: |  test4tests  |   0m  0s |  The patch doesn't appear to include any new or modified tests. Please justify why no new tests are needed for this patch. Also please list what manual steps were performed to verify this patch.  |
||| _ master Compile Tests _ |
| +1 :green_heart: |  mvninstall  |  17m 55s |  master passed  |
| +1 :green_heart: |  compile  |   2m 15s |  master passed with JDK Ubuntu-11.0.23+9-post-Ubuntu-1ubuntu122.04.1  |
| +1 :green_heart: |  compile  |   2m  4s |  master passed with JDK Private Build-1.8.0_412-8u412-ga-1~22.04.1-b08  |
| +1 :green_heart: |  javadoc  |   1m 47s |  master passed with JDK Ubuntu-11.0.23+9-post-Ubuntu-1ubuntu122.04.1  |
| +1 :green_heart: |  javadoc  |   1m  9s |  master passed with JDK Private Build-1.8.0_412-8u412-ga-1~22.04.1-b08  |
||| _ Patch Compile Tests _ |
| +1 :green_heart: |  mvninstall  |   4m 24s |  the patch passed  |
| +1 :green_heart: |  compile  |   2m 16s |  the patch passed with JDK Ubuntu-11.0.23+9-post-Ubuntu-1ubuntu122.04.1  |
| +1 :green_heart: |  javac  |   2m 16s |  the patch passed  |
| +1 :green_heart: |  compile  |   2m  7s |  the patch passed with JDK Private Build-1.8.0_412-8u412-ga-1~22.04.1-b08  |
| +1 :green_heart: |  javac  |   2m  7s |  the patch passed  |
| +1 :green_heart: |  whitespace  |   0m  0s |  The patch has no whitespace issues.  |
| +1 :green_heart: |  xml  |   0m  1s |  The patch has no ill-formed XML file.  |
| +1 :green_heart: |  javadoc  |   1m 11s |  the patch passed with JDK Ubuntu-11.0.23+9-post-Ubuntu-1ubuntu122.04.1  |
| +1 :green_heart: |  javadoc  |   1m 11s |  the patch passed with JDK Private Build-1.8.0_412-8u412-ga-1~22.04.1-b08  |
||| _ Other Tests _ |
| -1 :x: |  unit  |  79m  0s |  root in the patch failed.  |
| +1 :green_heart: |  asflicense  |   0m 37s |  The patch does not generate ASF License warnings.  |
|  |   | 138m 59s |   |


| Reason | Tests |
|-------:|:------|
| Failed junit tests | tez.analyzer.TestAnalyzer |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.44 ServerAPI=1.44 base: https://ci-hadoop.apache.org/job/tez-multibranch/job/PR-349/2/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/tez/pull/349 |
| JIRA Issue | TEZ-4557 |
| Optional Tests | dupname asflicense javac javadoc unit xml compile |
| uname | Linux fbec81ac4d43 5.15.0-94-generic #104-Ubuntu SMP Tue Jan 9 15:25:40 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | personality/tez.sh |
| git revision | master / 19b2351a9 |
| Default Java | Private Build-1.8.0_412-8u412-ga-1~22.04.1-b08 |
| Multi-JDK versions | /usr/lib/jvm/java-11-openjdk-amd64:Ubuntu-11.0.23+9-post-Ubuntu-1ubuntu122.04.1 /usr/lib/jvm/java-8-openjdk-amd64:Private Build-1.8.0_412-8u412-ga-1~22.04.1-b08 |
| unit | https://ci-hadoop.apache.org/job/tez-multibranch/job/PR-349/2/artifact/out/patch-unit-root.txt |
|  Test Results | https://ci-hadoop.apache.org/job/tez-multibranch/job/PR-349/2/testReport/ |
| Max. process+thread count | 2100 (vs. ulimit of 5500) |
| modules | C: . U: . |
| Console output | https://ci-hadoop.apache.org/job/tez-multibranch/job/PR-349/2/console |
| versions | git=2.34.1 maven=3.6.3 |
| Powered by | Apache Yetus 0.12.0 https://yetus.apache.org |


This message was automatically generated.

**Comment by tez-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| +0 :ok: |  reexec  |   0m 12s |  Docker mode activated.  |
||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  0s |  No case conflicting files found.  |
| +1 :green_heart: |  @author  |   0m  0s |  The patch does not contain any @author tags.  |
| -1 :x: |  test4tests  |   0m  0s |  The patch doesn't appear to include any new or modified tests. Please justify why no new tests are needed for this patch. Also please list what manual steps were performed to verify this patch.  |
||| _ master Compile Tests _ |
| +1 :green_heart: |  mvninstall  |  17m  3s |  master passed  |
| +1 :green_heart: |  compile  |   2m 26s |  master passed with JDK Ubuntu-11.0.23+9-post-Ubuntu-1ubuntu122.04.1  |
| +1 :green_heart: |  compile  |   2m 14s |  master passed with JDK Private Build-1.8.0_412-8u412-ga-1~22.04.1-b08  |
| +1 :green_heart: |  javadoc  |   1m 39s |  master passed with JDK Ubuntu-11.0.23+9-post-Ubuntu-1ubuntu122.04.1  |
| +1 :green_heart: |  javadoc  |   1m 10s |  master passed with JDK Private Build-1.8.0_412-8u412-ga-1~22.04.1-b08  |
||| _ Patch Compile Tests _ |
| +1 :green_heart: |  mvninstall  |   4m 41s |  the patch passed  |
| +1 :green_heart: |  compile  |   2m 33s |  the patch passed with JDK Ubuntu-11.0.23+9-post-Ubuntu-1ubuntu122.04.1  |
| +1 :green_heart: |  javac  |   2m 33s |  the patch passed  |
| +1 :green_heart: |  compile  |   2m 19s |  the patch passed with JDK Private Build-1.8.0_412-8u412-ga-1~22.04.1-b08  |
| +1 :green_heart: |  javac  |   2m 19s |  the patch passed  |
| +1 :green_heart: |  whitespace  |   0m  0s |  The patch has no whitespace issues.  |
| +1 :green_heart: |  xml  |   0m  2s |  The patch has no ill-formed XML file.  |
| +1 :green_heart: |  javadoc  |   1m 14s |  the patch passed with JDK Ubuntu-11.0.23+9-post-Ubuntu-1ubuntu122.04.1  |
| +1 :green_heart: |  javadoc  |   1m 11s |  the patch passed with JDK Private Build-1.8.0_412-8u412-ga-1~22.04.1-b08  |
||| _ Other Tests _ |
| -1 :x: |  unit  |  79m 55s |  root in the patch failed.  |
| +1 :green_heart: |  asflicense  |   0m 38s |  The patch does not generate ASF License warnings.  |
|  |   | 118m 35s |   |


| Reason | Tests |
|-------:|:------|
| Failed junit tests | tez.analyzer.TestAnalyzer |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.44 ServerAPI=1.44 base: https://ci-hadoop.apache.org/job/tez-multibranch/job/PR-349/3/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/tez/pull/349 |
| JIRA Issue | TEZ-4557 |
| Optional Tests | dupname asflicense javac javadoc unit xml compile |
| uname | Linux d845255c0666 5.15.0-94-generic #104-Ubuntu SMP Tue Jan 9 15:25:40 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | personality/tez.sh |
| git revision | master / 19b2351a9 |
| Default Java | Private Build-1.8.0_412-8u412-ga-1~22.04.1-b08 |
| Multi-JDK versions | /usr/lib/jvm/java-11-openjdk-amd64:Ubuntu-11.0.23+9-post-Ubuntu-1ubuntu122.04.1 /usr/lib/jvm/java-8-openjdk-amd64:Private Build-1.8.0_412-8u412-ga-1~22.04.1-b08 |
| unit | https://ci-hadoop.apache.org/job/tez-multibranch/job/PR-349/3/artifact/out/patch-unit-root.txt |
|  Test Results | https://ci-hadoop.apache.org/job/tez-multibranch/job/PR-349/3/testReport/ |
| Max. process+thread count | 2099 (vs. ulimit of 5500) |
| modules | C: . U: . |
| Console output | https://ci-hadoop.apache.org/job/tez-multibranch/job/PR-349/3/console |
| versions | git=2.34.1 maven=3.6.3 |
| Powered by | Apache Yetus 0.12.0 https://yetus.apache.org |


This message was automatically generated.

**Comment by Aggarwal-Raghav** [comment]
Test seems to be passing on local
Screenshot 2024-06-25 at 7 24 51 PM

will trigger the CI one more time!

**Comment by Aggarwal-Raghav** [comment]
Wasn't aware of it, have triggered it now 🥲.

**Comment by tez-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| +0 :ok: |  reexec  |   0m 12s |  Docker mode activated.  |
||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  0s |  No case conflicting files found.  |
| +1 :green_heart: |  @author  |   0m  0s |  The patch does not contain any @author tags.  |
| -1 :x: |  test4tests  |   0m  0s |  The patch doesn't appear to include any new or modified tests. Please justify why no new tests are needed for this patch. Also please list what manual steps were performed to verify this patch.  |
||| _ master Compile Tests _ |
| +1 :green_heart: |  mvninstall  |  16m 45s |  master passed  |
| +1 :green_heart: |  compile  |   2m 16s |  master passed with JDK Ubuntu-11.0.23+9-post-Ubuntu-1ubuntu122.04.1  |
| +1 :green_heart: |  compile  |   2m  3s |  master passed with JDK Private Build-1.8.0_412-8u412-ga-1~22.04.1-b08  |
| +1 :green_heart: |  javadoc  |   1m 45s |  master passed with JDK Ubuntu-11.0.23+9-post-Ubuntu-1ubuntu122.04.1  |
| +1 :green_heart: |  javadoc  |   1m  9s |  master passed with JDK Private Build-1.8.0_412-8u412-ga-1~22.04.1-b08  |
||| _ Patch Compile Tests _ |
| +1 :green_heart: |  mvninstall  |   4m 14s |  the patch passed  |
| +1 :green_heart: |  compile  |   2m 14s |  the patch passed with JDK Ubuntu-11.0.23+9-post-Ubuntu-1ubuntu122.04.1  |
| +1 :green_heart: |  javac  |   2m 14s |  the patch passed  |
| +1 :green_heart: |  compile  |   2m  4s |  the patch passed with JDK Private Build-1.8.0_412-8u412-ga-1~22.04.1-b08  |
| +1 :green_heart: |  javac  |   2m  4s |  the patch passed  |
| +1 :green_heart: |  whitespace  |   0m  0s |  The patch has no whitespace issues.  |
| +1 :green_heart: |  xml  |   0m  1s |  The patch has no ill-formed XML file.  |
| +1 :green_heart: |  javadoc  |   1m 11s |  the patch passed with JDK Ubuntu-11.0.23+9-post-Ubuntu-1ubuntu122.04.1  |
| +1 :green_heart: |  javadoc  |   1m 10s |  the patch passed with JDK Private Build-1.8.0_412-8u412-ga-1~22.04.1-b08  |
||| _ Other Tests _ |
| -1 :x: |  unit  |  61m 10s |  root in the patch failed.  |
| +1 :green_heart: |  asflicense  |   0m 40s |  The patch does not generate ASF License warnings.  |
|  |   |  98m  5s |   |


| Reason | Tests |
|-------:|:------|
| Failed junit tests | tez.test.TestRecovery |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.44 ServerAPI=1.44 base: https://ci-hadoop.apache.org/job/tez-multibranch/job/PR-349/4/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/tez/pull/349 |
| JIRA Issue | TEZ-4557 |
| Optional Tests | dupname asflicense javac javadoc unit xml compile |
| uname | Linux c67e5978f752 5.15.0-94-generic #104-Ubuntu SMP Tue Jan 9 15:25:40 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | personality/tez.sh |
| git revision | master / 19b2351a9 |
| Default Java | Private Build-1.8.0_412-8u412-ga-1~22.04.1-b08 |
| Multi-JDK versions | /usr/lib/jvm/java-11-openjdk-amd64:Ubuntu-11.0.23+9-post-Ubuntu-1ubuntu122.04.1 /usr/lib/jvm/java-8-openjdk-amd64:Private Build-1.8.0_412-8u412-ga-1~22.04.1-b08 |
| unit | https://ci-hadoop.apache.org/job/tez-multibranch/job/PR-349/4/artifact/out/patch-unit-root.txt |
|  Test Results | https://ci-hadoop.apache.org/job/tez-multibranch/job/PR-349/4/testReport/ |
| Max. process+thread count | 2100 (vs. ulimit of 5500) |
| modules | C: . U: . |
| Console output | https://ci-hadoop.apache.org/job/tez-multibranch/job/PR-349/4/console |
| versions | git=2.34.1 maven=3.6.3 |
| Powered by | Apache Yetus 0.12.0 https://yetus.apache.org |


This message was automatically generated.

**Comment by deniskuzZ** [comment]
@abstractdog, is there a possibility of Tez release that includes this fix before Hive-4.0.1
cc @ayushtkn

**Comment by abstractdog** [comment]
> @abstractdog, is there a possibility of Tez release that includes this fix before Hive-4.0.1 cc @ayushtkn, @dengzhhu653

not sure, even if we merge this now, and initiate a release process for Tez 0.10.4, it's a matter of weeks, usually at least a month until we get PMC member votes

**Review by abstractdog — APPROVED** [review]

**Comment by abstractdog** [comment]
ignoring any further recovery flaky failures, merging this to master

**Pull request merged**
