### PR TITLE
TEZ-4493: Upgrade Hadoop to 3.3.6

### PR DESCRIPTION
**Pull request by ayushtkn**

### CODE REVIEW

**Comment by tez-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| +0 :ok: |  reexec  |  20m 37s |  Docker mode activated.  |
||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  0s |  No case conflicting files found.  |
| +1 :green_heart: |  @author  |   0m  0s |  The patch does not contain any @author tags.  |
| -1 :x: |  test4tests  |   0m  0s |  The patch doesn't appear to include any new or modified tests. Please justify why no new tests are needed for this patch. Also please list what manual steps were performed to verify this patch.  |
||| _ master Compile Tests _ |
| -1 :x: |  mvninstall  |  13m 36s |  root in master failed.  |
| -1 :x: |  compile  |   1m 18s |  root in master failed with JDK Ubuntu-11.0.18+10-post-Ubuntu-0ubuntu122.04.  |
| -1 :x: |  compile  |   1m 11s |  root in master failed with JDK Private Build-1.8.0_362-8u362-ga-0ubuntu1~22.04-b09.  |
| +1 :green_heart: |  javadoc  |   2m 30s |  master passed with JDK Ubuntu-11.0.18+10-post-Ubuntu-0ubuntu122.04  |
| +1 :green_heart: |  javadoc  |   1m 45s |  master passed with JDK Private Build-1.8.0_362-8u362-ga-0ubuntu1~22.04-b09  |
||| _ Patch Compile Tests _ |
| -1 :x: |  mvninstall  |   4m 27s |  root in the patch failed.  |
| -1 :x: |  compile  |   1m 18s |  root in the patch failed with JDK Ubuntu-11.0.18+10-post-Ubuntu-0ubuntu122.04.  |
| -1 :x: |  javac  |   1m 18s |  root in the patch failed with JDK Ubuntu-11.0.18+10-post-Ubuntu-0ubuntu122.04.  |
| -1 :x: |  compile  |   1m 11s |  root in the patch failed with JDK Private Build-1.8.0_362-8u362-ga-0ubuntu1~22.04-b09.  |
| -1 :x: |  javac  |   1m 11s |  root in the patch failed with JDK Private Build-1.8.0_362-8u362-ga-0ubuntu1~22.04-b09.  |
| +1 :green_heart: |  whitespace  |   0m  0s |  The patch has no whitespace issues.  |
| +1 :green_heart: |  xml  |   0m  2s |  The patch has no ill-formed XML file.  |
| +1 :green_heart: |  javadoc  |   2m  3s |  the patch passed with JDK Ubuntu-11.0.18+10-post-Ubuntu-0ubuntu122.04  |
| +1 :green_heart: |  javadoc  |   1m 44s |  the patch passed with JDK Private Build-1.8.0_362-8u362-ga-0ubuntu1~22.04-b09  |
||| _ Other Tests _ |
| -1 :x: |  unit  |  73m  8s |  root in the patch failed.  |
| +1 :green_heart: |  asflicense  |   0m 36s |  The patch does not generate ASF License warnings.  |
|  |   | 126m 29s |   |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.42 ServerAPI=1.42 base: https://ci-hadoop.apache.org/job/tez-multibranch/job/PR-285/1/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/tez/pull/285 |
| Optional Tests | dupname asflicense javac javadoc unit xml compile |
| uname | Linux 2a15668d002f 4.15.0-206-generic #217-Ubuntu SMP Fri Feb 3 19:10:13 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | personality/tez.sh |
| git revision | master / 249e017b3 |
| Default Java | Private Build-1.8.0_362-8u362-ga-0ubuntu1~22.04-b09 |
| Multi-JDK versions | /usr/lib/jvm/java-11-openjdk-amd64:Ubuntu-11.0.18+10-post-Ubuntu-0ubuntu122.04 /usr/lib/jvm/java-8-openjdk-amd64:Private Build-1.8.0_362-8u362-ga-0ubuntu1~22.04-b09 |
| mvninstall | https://ci-hadoop.apache.org/job/tez-multibranch/job/PR-285/1/artifact/out/branch-mvninstall-root.txt |
| compile | https://ci-hadoop.apache.org/job/tez-multibranch/job/PR-285/1/artifact/out/branch-compile-root-jdkUbuntu-11.0.18+10-post-Ubuntu-0ubuntu122.04.txt |
| compile | https://ci-hadoop.apache.org/job/tez-multibranch/job/PR-285/1/artifact/out/branch-compile-root-jdkPrivateBuild-1.8.0_362-8u362-ga-0ubuntu1~22.04-b09.txt |
| mvninstall | https://ci-hadoop.apache.org/job/tez-multibranch/job/PR-285/1/artifact/out/patch-mvninstall-root.txt |
| compile | https://ci-hadoop.apache.org/job/tez-multibranch/job/PR-285/1/artifact/out/patch-compile-root-jdkUbuntu-11.0.18+10-post-Ubuntu-0ubuntu122.04.txt |
| javac | https://ci-hadoop.apache.org/job/tez-multibranch/job/PR-285/1/artifact/out/patch-compile-root-jdkUbuntu-11.0.18+10-post-Ubuntu-0ubuntu122.04.txt |
| compile | https://ci-hadoop.apache.org/job/tez-multibranch/job/PR-285/1/artifact/out/patch-compile-root-jdkPrivateBuild-1.8.0_362-8u362-ga-0ubuntu1~22.04-b09.txt |
| javac | https://ci-hadoop.apache.org/job/tez-multibranch/job/PR-285/1/artifact/out/patch-compile-root-jdkPrivateBuild-1.8.0_362-8u362-ga-0ubuntu1~22.04-b09.txt |
| unit | https://ci-hadoop.apache.org/job/tez-multibranch/job/PR-285/1/artifact/out/patch-unit-root.txt |
|  Test Results | https://ci-hadoop.apache.org/job/tez-multibranch/job/PR-285/1/testReport/ |
| Max. process+thread count | 2100 (vs. ulimit of 5500) |
| modules | C: . U: . |
| Console output | https://ci-hadoop.apache.org/job/tez-multibranch/job/PR-285/1/console |
| versions | git=2.34.1 maven=3.6.3 |
| Powered by | Apache Yetus 0.12.0 https://yetus.apache.org |


This message was automatically generated.

**Comment by tez-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| +0 :ok: |  reexec  |  22m 57s |  Docker mode activated.  |
||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  0s |  No case conflicting files found.  |
| +1 :green_heart: |  @author  |   0m  0s |  The patch does not contain any @author tags.  |
| -1 :x: |  test4tests  |   0m  0s |  The patch doesn't appear to include any new or modified tests. Please justify why no new tests are needed for this patch. Also please list what manual steps were performed to verify this patch.  |
||| _ master Compile Tests _ |
| -1 :x: |  mvninstall  |  13m 40s |  root in master failed.  |
| -1 :x: |  compile  |   1m 18s |  root in master failed with JDK Ubuntu-11.0.18+10-post-Ubuntu-0ubuntu122.04.  |
| -1 :x: |  compile  |   1m 10s |  root in master failed with JDK Private Build-1.8.0_362-8u362-ga-0ubuntu1~22.04-b09.  |
| +1 :green_heart: |  javadoc  |   2m 28s |  master passed with JDK Ubuntu-11.0.18+10-post-Ubuntu-0ubuntu122.04  |
| +1 :green_heart: |  javadoc  |   1m 42s |  master passed with JDK Private Build-1.8.0_362-8u362-ga-0ubuntu1~22.04-b09  |
||| _ Patch Compile Tests _ |
| -1 :x: |  mvninstall  |   4m 25s |  root in the patch failed.  |
| -1 :x: |  compile  |   1m 20s |  root in the patch failed with JDK Ubuntu-11.0.18+10-post-Ubuntu-0ubuntu122.04.  |
| -1 :x: |  javac  |   1m 20s |  root in the patch failed with JDK Ubuntu-11.0.18+10-post-Ubuntu-0ubuntu122.04.  |
| -1 :x: |  compile  |   1m 12s |  root in the patch failed with JDK Private Build-1.8.0_362-8u362-ga-0ubuntu1~22.04-b09.  |
| -1 :x: |  javac  |   1m 12s |  root in the patch failed with JDK Private Build-1.8.0_362-8u362-ga-0ubuntu1~22.04-b09.  |
| +1 :green_heart: |  whitespace  |   0m  0s |  The patch has no whitespace issues.  |
| +1 :green_heart: |  xml  |   0m  1s |  The patch has no ill-formed XML file.  |
| +1 :green_heart: |  javadoc  |   2m  0s |  the patch passed with JDK Ubuntu-11.0.18+10-post-Ubuntu-0ubuntu122.04  |
| +1 :green_heart: |  javadoc  |   1m 43s |  the patch passed with JDK Private Build-1.8.0_362-8u362-ga-0ubuntu1~22.04-b09  |
||| _ Other Tests _ |
| -1 :x: |  unit  |  70m 55s |  root in the patch failed.  |
| +1 :green_heart: |  asflicense  |   0m 36s |  The patch does not generate ASF License warnings.  |
|  |   | 126m 31s |   |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.42 ServerAPI=1.42 base: https://ci-hadoop.apache.org/job/tez-multibranch/job/PR-285/2/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/tez/pull/285 |
| Optional Tests | dupname asflicense javac javadoc unit xml compile |
| uname | Linux 3fd3c6c6d481 4.15.0-206-generic #217-Ubuntu SMP Fri Feb 3 19:10:13 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | personality/tez.sh |
| git revision | master / 249e017b3 |
| Default Java | Private Build-1.8.0_362-8u362-ga-0ubuntu1~22.04-b09 |
| Multi-JDK versions | /usr/lib/jvm/java-11-openjdk-amd64:Ubuntu-11.0.18+10-post-Ubuntu-0ubuntu122.04 /usr/lib/jvm/java-8-openjdk-amd64:Private Build-1.8.0_362-8u362-ga-0ubuntu1~22.04-b09 |
| mvninstall | https://ci-hadoop.apache.org/job/tez-multibranch/job/PR-285/2/artifact/out/branch-mvninstall-root.txt |
| compile | https://ci-hadoop.apache.org/job/tez-multibranch/job/PR-285/2/artifact/out/branch-compile-root-jdkUbuntu-11.0.18+10-post-Ubuntu-0ubuntu122.04.txt |
| compile | https://ci-hadoop.apache.org/job/tez-multibranch/job/PR-285/2/artifact/out/branch-compile-root-jdkPrivateBuild-1.8.0_362-8u362-ga-0ubuntu1~22.04-b09.txt |
| mvninstall | https://ci-hadoop.apache.org/job/tez-multibranch/job/PR-285/2/artifact/out/patch-mvninstall-root.txt |
| compile | https://ci-hadoop.apache.org/job/tez-multibranch/job/PR-285/2/artifact/out/patch-compile-root-jdkUbuntu-11.0.18+10-post-Ubuntu-0ubuntu122.04.txt |
| javac | https://ci-hadoop.apache.org/job/tez-multibranch/job/PR-285/2/artifact/out/patch-compile-root-jdkUbuntu-11.0.18+10-post-Ubuntu-0ubuntu122.04.txt |
| compile | https://ci-hadoop.apache.org/job/tez-multibranch/job/PR-285/2/artifact/out/patch-compile-root-jdkPrivateBuild-1.8.0_362-8u362-ga-0ubuntu1~22.04-b09.txt |
| javac | https://ci-hadoop.apache.org/job/tez-multibranch/job/PR-285/2/artifact/out/patch-compile-root-jdkPrivateBuild-1.8.0_362-8u362-ga-0ubuntu1~22.04-b09.txt |
| unit | https://ci-hadoop.apache.org/job/tez-multibranch/job/PR-285/2/artifact/out/patch-unit-root.txt |
|  Test Results | https://ci-hadoop.apache.org/job/tez-multibranch/job/PR-285/2/testReport/ |
| Max. process+thread count | 1532 (vs. ulimit of 5500) |
| modules | C: . U: . |
| Console output | https://ci-hadoop.apache.org/job/tez-multibranch/job/PR-285/2/console |
| versions | git=2.34.1 maven=3.6.3 |
| Powered by | Apache Yetus 0.12.0 https://yetus.apache.org |


This message was automatically generated.

**Comment by tez-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| +0 :ok: |  reexec  |  23m  5s |  Docker mode activated.  |
||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  0s |  No case conflicting files found.  |
| +1 :green_heart: |  @author  |   0m  0s |  The patch does not contain any @author tags.  |
| -1 :x: |  test4tests  |   0m  0s |  The patch doesn't appear to include any new or modified tests. Please justify why no new tests are needed for this patch. Also please list what manual steps were performed to verify this patch.  |
||| _ master Compile Tests _ |
| +0 :ok: |  mvndep  |   5m 48s |  Maven dependency ordering for branch  |
| +1 :green_heart: |  mvninstall  |   7m 28s |  master passed  |
| +1 :green_heart: |  compile  |   3m 15s |  master passed with JDK Ubuntu-11.0.19+7-post-Ubuntu-0ubuntu122.04.1  |
| +1 :green_heart: |  compile  |   2m 53s |  master passed with JDK Private Build-1.8.0_362-8u372-ga~us1-0ubuntu1~22.04-b09  |
| +1 :green_heart: |  checkstyle  |   1m 28s |  master passed  |
| +1 :green_heart: |  javadoc  |   2m 57s |  master passed with JDK Ubuntu-11.0.19+7-post-Ubuntu-0ubuntu122.04.1  |
| +1 :green_heart: |  javadoc  |   2m 27s |  master passed with JDK Private Build-1.8.0_362-8u372-ga~us1-0ubuntu1~22.04-b09  |
| +0 :ok: |  spotbugs  |   7m 27s |  Used deprecated FindBugs config; considering switching to SpotBugs.  |
| +1 :green_heart: |  findbugs  |   8m 48s |  master passed  |
||| _ Patch Compile Tests _ |
| +0 :ok: |  mvndep  |   2m 31s |  Maven dependency ordering for patch  |
| +1 :green_heart: |  mvninstall  |   5m 21s |  the patch passed  |
| +1 :green_heart: |  compile  |   3m 22s |  the patch passed with JDK Ubuntu-11.0.19+7-post-Ubuntu-0ubuntu122.04.1  |
| +1 :green_heart: |  javac  |   3m 22s |  the patch passed  |
| +1 :green_heart: |  compile  |   2m 50s |  the patch passed with JDK Private Build-1.8.0_362-8u372-ga~us1-0ubuntu1~22.04-b09  |
| +1 :green_heart: |  javac  |   2m 50s |  the patch passed  |
| +1 :green_heart: |  checkstyle  |   1m 25s |  the patch passed  |
| +1 :green_heart: |  whitespace  |   0m  0s |  The patch has no whitespace issues.  |
| +1 :green_heart: |  xml  |   0m  1s |  The patch has no ill-formed XML file.  |
| +1 :green_heart: |  javadoc  |   2m 51s |  the patch passed with JDK Ubuntu-11.0.19+7-post-Ubuntu-0ubuntu122.04.1  |
| +1 :green_heart: |  javadoc  |   2m 26s |  the patch passed with JDK Private Build-1.8.0_362-8u372-ga~us1-0ubuntu1~22.04-b09  |
| +1 :green_heart: |  findbugs  |   8m 44s |  the patch passed  |
||| _ Other Tests _ |
| +1 :green_heart: |  unit  |   5m 25s |  tez-dag in the patch passed.  |
| -1 :x: |  unit  |  58m 57s |  root in the patch failed.  |
| +1 :green_heart: |  asflicense  |   0m 58s |  The patch does not generate ASF License warnings.  |
|  |   | 155m 34s |   |


| Reason | Tests |
|-------:|:------|
| Failed junit tests | tez.test.TestTezJobs |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.43 ServerAPI=1.43 base: https://ci-hadoop.apache.org/job/tez-multibranch/job/PR-285/5/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/tez/pull/285 |
| JIRA Issue | TEZ-4493 |
| Optional Tests | dupname asflicense javac javadoc unit xml compile spotbugs findbugs checkstyle |
| uname | Linux d83b3e104e80 4.15.0-206-generic #217-Ubuntu SMP Fri Feb 3 19:10:13 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | personality/tez.sh |
| git revision | master / 86b11997b |
| Default Java | Private Build-1.8.0_362-8u372-ga~us1-0ubuntu1~22.04-b09 |
| Multi-JDK versions | /usr/lib/jvm/java-11-openjdk-amd64:Ubuntu-11.0.19+7-post-Ubuntu-0ubuntu122.04.1 /usr/lib/jvm/java-8-openjdk-amd64:Private Build-1.8.0_362-8u372-ga~us1-0ubuntu1~22.04-b09 |
| unit | https://ci-hadoop.apache.org/job/tez-multibranch/job/PR-285/5/artifact/out/patch-unit-root.txt |
|  Test Results | https://ci-hadoop.apache.org/job/tez-multibranch/job/PR-285/5/testReport/ |
| Max. process+thread count | 2090 (vs. ulimit of 5500) |
| modules | C: tez-dag . U: . |
| Console output | https://ci-hadoop.apache.org/job/tez-multibranch/job/PR-285/5/console |
| versions | git=2.34.1 maven=3.6.3 findbugs=3.0.1 |
| Powered by | Apache Yetus 0.12.0 https://yetus.apache.org |


This message was automatically generated.

**Comment by tez-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| +0 :ok: |  reexec  |  27m 53s |  Docker mode activated.  |
||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  0s |  No case conflicting files found.  |
| +1 :green_heart: |  @author  |   0m  0s |  The patch does not contain any @author tags.  |
| -1 :x: |  test4tests  |   0m  0s |  The patch doesn't appear to include any new or modified tests. Please justify why no new tests are needed for this patch. Also please list what manual steps were performed to verify this patch.  |
||| _ master Compile Tests _ |
| +0 :ok: |  mvndep  |   6m 43s |  Maven dependency ordering for branch  |
| +1 :green_heart: |  mvninstall  |  11m 23s |  master passed  |
| +1 :green_heart: |  compile  |   3m  6s |  master passed with JDK Ubuntu-11.0.19+7-post-Ubuntu-0ubuntu122.04.1  |
| +1 :green_heart: |  compile  |   2m 53s |  master passed with JDK Private Build-1.8.0_362-8u372-ga~us1-0ubuntu1~22.04-b09  |
| +1 :green_heart: |  checkstyle  |   1m 47s |  master passed  |
| +1 :green_heart: |  javadoc  |   3m  3s |  master passed with JDK Ubuntu-11.0.19+7-post-Ubuntu-0ubuntu122.04.1  |
| +1 :green_heart: |  javadoc  |   2m 32s |  master passed with JDK Private Build-1.8.0_362-8u372-ga~us1-0ubuntu1~22.04-b09  |
| +0 :ok: |  spotbugs  |   6m 48s |  Used deprecated FindBugs config; considering switching to SpotBugs.  |
| +1 :green_heart: |  findbugs  |   8m 25s |  master passed  |
||| _ Patch Compile Tests _ |
| +0 :ok: |  mvndep  |   2m 34s |  Maven dependency ordering for patch  |
| +1 :green_heart: |  mvninstall  |   5m 17s |  the patch passed  |
| +1 :green_heart: |  compile  |   3m 28s |  the patch passed with JDK Ubuntu-11.0.19+7-post-Ubuntu-0ubuntu122.04.1  |
| +1 :green_heart: |  javac  |   3m 28s |  the patch passed  |
| +1 :green_heart: |  compile  |   2m 59s |  the patch passed with JDK Private Build-1.8.0_362-8u372-ga~us1-0ubuntu1~22.04-b09  |
| +1 :green_heart: |  javac  |   2m 59s |  the patch passed  |
| +1 :green_heart: |  checkstyle  |   1m 32s |  the patch passed  |
| +1 :green_heart: |  whitespace  |   0m  0s |  The patch has no whitespace issues.  |
| +1 :green_heart: |  xml  |   0m  1s |  The patch has no ill-formed XML file.  |
| +1 :green_heart: |  javadoc  |   2m 57s |  the patch passed with JDK Ubuntu-11.0.19+7-post-Ubuntu-0ubuntu122.04.1  |
| +1 :green_heart: |  javadoc  |   2m 32s |  the patch passed with JDK Private Build-1.8.0_362-8u372-ga~us1-0ubuntu1~22.04-b09  |
| +1 :green_heart: |  findbugs  |   7m 43s |  the patch passed  |
||| _ Other Tests _ |
| +1 :green_heart: |  unit  |   5m 34s |  tez-dag in the patch passed.  |
| +1 :green_heart: |  unit  |  76m  7s |  root in the patch passed.  |
| +1 :green_heart: |  asflicense  |   1m  8s |  The patch does not generate ASF License warnings.  |
|  |   | 182m 26s |   |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.43 ServerAPI=1.43 base: https://ci-hadoop.apache.org/job/tez-multibranch/job/PR-285/4/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/tez/pull/285 |
| JIRA Issue | TEZ-4493 |
| Optional Tests | dupname asflicense javac javadoc unit xml compile spotbugs findbugs checkstyle |
| uname | Linux f9295f1d1a06 4.15.0-206-generic #217-Ubuntu SMP Fri Feb 3 19:10:13 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | personality/tez.sh |
| git revision | master / 86b11997b |
| Default Java | Private Build-1.8.0_362-8u372-ga~us1-0ubuntu1~22.04-b09 |
| Multi-JDK versions | /usr/lib/jvm/java-11-openjdk-amd64:Ubuntu-11.0.19+7-post-Ubuntu-0ubuntu122.04.1 /usr/lib/jvm/java-8-openjdk-amd64:Private Build-1.8.0_362-8u372-ga~us1-0ubuntu1~22.04-b09 |
|  Test Results | https://ci-hadoop.apache.org/job/tez-multibranch/job/PR-285/4/testReport/ |
| Max. process+thread count | 2100 (vs. ulimit of 5500) |
| modules | C: tez-dag . U: . |
| Console output | https://ci-hadoop.apache.org/job/tez-multibranch/job/PR-285/4/console |
| versions | git=2.34.1 maven=3.6.3 findbugs=3.0.1 |
| Powered by | Apache Yetus 0.12.0 https://yetus.apache.org |


This message was automatically generated.

**Comment by ayushtkn** [comment]
have rebased it, last build was clean.
@abstractdog can you help review

**Comment by tez-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| +0 :ok: |  reexec  |   0m 19s |  Docker mode activated.  |
||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  0s |  No case conflicting files found.  |
| +1 :green_heart: |  @author  |   0m  0s |  The patch does not contain any @author tags.  |
| -1 :x: |  test4tests  |   0m  0s |  The patch doesn't appear to include any new or modified tests. Please justify why no new tests are needed for this patch. Also please list what manual steps were performed to verify this patch.  |
||| _ master Compile Tests _ |
| +0 :ok: |  mvndep  |   6m 33s |  Maven dependency ordering for branch  |
| +1 :green_heart: |  mvninstall  |   9m 41s |  master passed  |
| +1 :green_heart: |  compile  |   3m 16s |  master passed with JDK Ubuntu-11.0.19+7-post-Ubuntu-0ubuntu122.04.1  |
| +1 :green_heart: |  compile  |   2m 56s |  master passed with JDK Private Build-1.8.0_362-8u372-ga~us1-0ubuntu1~22.04-b09  |
| +1 :green_heart: |  checkstyle  |   1m 55s |  master passed  |
| +1 :green_heart: |  javadoc  |   1m 54s |  master passed with JDK Ubuntu-11.0.19+7-post-Ubuntu-0ubuntu122.04.1  |
| +1 :green_heart: |  javadoc  |   1m 30s |  master passed with JDK Private Build-1.8.0_362-8u372-ga~us1-0ubuntu1~22.04-b09  |
| +0 :ok: |  spotbugs  |   6m 51s |  Used deprecated FindBugs config; considering switching to SpotBugs.  |
| +1 :green_heart: |  findbugs  |   8m 36s |  master passed  |
| -0 :warning: |  patch  |   7m  6s |  Used diff version of patch file. Binary files and potentially other changes not applied. Please rebase and squash commits if necessary.  |
||| _ Patch Compile Tests _ |
| +0 :ok: |  mvndep  |   1m 36s |  Maven dependency ordering for patch  |
| +1 :green_heart: |  mvninstall  |   5m 16s |  the patch passed  |
| +1 :green_heart: |  compile  |   3m 25s |  the patch passed with JDK Ubuntu-11.0.19+7-post-Ubuntu-0ubuntu122.04.1  |
| +1 :green_heart: |  javac  |   3m 25s |  the patch passed  |
| +1 :green_heart: |  compile  |   3m  5s |  the patch passed with JDK Private Build-1.8.0_362-8u372-ga~us1-0ubuntu1~22.04-b09  |
| +1 :green_heart: |  javac  |   3m  5s |  the patch passed  |
| +1 :green_heart: |  checkstyle  |   1m 35s |  the patch passed  |
| +1 :green_heart: |  whitespace  |   0m  0s |  The patch has no whitespace issues.  |
| +1 :green_heart: |  xml  |   0m  2s |  The patch has no ill-formed XML file.  |
| +1 :green_heart: |  javadoc  |   1m 45s |  the patch passed with JDK Ubuntu-11.0.19+7-post-Ubuntu-0ubuntu122.04.1  |
| +1 :green_heart: |  javadoc  |   1m 40s |  the patch passed with JDK Private Build-1.8.0_362-8u372-ga~us1-0ubuntu1~22.04-b09  |
| +1 :green_heart: |  findbugs  |   8m 11s |  the patch passed  |
||| _ Other Tests _ |
| +1 :green_heart: |  unit  |   5m 34s |  tez-dag in the patch passed.  |
| +1 :green_heart: |  unit  |  76m 50s |  root in the patch passed.  |
| +1 :green_heart: |  asflicense  |   1m 14s |  The patch does not generate ASF License warnings.  |
|  |   | 149m 44s |   |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.43 ServerAPI=1.43 base: https://ci-hadoop.apache.org/job/tez-multibranch/job/PR-285/7/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/tez/pull/285 |
| JIRA Issue | TEZ-4493 |
| Optional Tests | dupname asflicense javac javadoc unit xml compile spotbugs findbugs checkstyle |
| uname | Linux 871749dec8b2 4.15.0-212-generic #223-Ubuntu SMP Tue May 23 13:09:22 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | personality/tez.sh |
| git revision | master / 7a56e9bd9 |
| Default Java | Private Build-1.8.0_362-8u372-ga~us1-0ubuntu1~22.04-b09 |
| Multi-JDK versions | /usr/lib/jvm/java-11-openjdk-amd64:Ubuntu-11.0.19+7-post-Ubuntu-0ubuntu122.04.1 /usr/lib/jvm/java-8-openjdk-amd64:Private Build-1.8.0_362-8u372-ga~us1-0ubuntu1~22.04-b09 |
|  Test Results | https://ci-hadoop.apache.org/job/tez-multibranch/job/PR-285/7/testReport/ |
| Max. process+thread count | 2100 (vs. ulimit of 5500) |
| modules | C: tez-dag . U: . |
| Console output | https://ci-hadoop.apache.org/job/tez-multibranch/job/PR-285/7/console |
| versions | git=2.34.1 maven=3.6.3 findbugs=3.0.1 |
| Powered by | Apache Yetus 0.12.0 https://yetus.apache.org |


This message was automatically generated.

**Comment by ayushtkn** [comment]
the jenkins build is clean, the github action failed with strange error. can not download node js
https://github.com/apache/tez/actions/runs/5386817096/jobs/9777325089?pr=285

sounds unrelated

**Comment by abstractdog** [comment]
> the jenkins build is clean, the github action failed with strange error. can not download node js https://github.com/apache/tez/actions/runs/5386817096/jobs/9777325089?pr=285
> 
> sounds unrelated

agreed, absolutely, however the rest of the github actions were cancelled...can you restart precommit? I guess it was intermittent and we're going to see a full green run

**Comment by tez-yetus** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| +0 :ok: |  reexec  |   0m 18s |  Docker mode activated.  |
||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  0s |  No case conflicting files found.  |
| +1 :green_heart: |  @author  |   0m  0s |  The patch does not contain any @author tags.  |
| -1 :x: |  test4tests  |   0m  0s |  The patch doesn't appear to include any new or modified tests. Please justify why no new tests are needed for this patch. Also please list what manual steps were performed to verify this patch.  |
||| _ master Compile Tests _ |
| +0 :ok: |  mvndep  |   6m 49s |  Maven dependency ordering for branch  |
| +1 :green_heart: |  mvninstall  |  10m  0s |  master passed  |
| +1 :green_heart: |  compile  |   3m  9s |  master passed with JDK Ubuntu-11.0.19+7-post-Ubuntu-0ubuntu122.04.1  |
| +1 :green_heart: |  compile  |   2m 55s |  master passed with JDK Private Build-1.8.0_362-8u372-ga~us1-0ubuntu1~22.04-b09  |
| +1 :green_heart: |  checkstyle  |   1m 55s |  master passed  |
| +1 :green_heart: |  javadoc  |   1m 53s |  master passed with JDK Ubuntu-11.0.19+7-post-Ubuntu-0ubuntu122.04.1  |
| +1 :green_heart: |  javadoc  |   1m 35s |  master passed with JDK Private Build-1.8.0_362-8u372-ga~us1-0ubuntu1~22.04-b09  |
| +0 :ok: |  spotbugs  |   6m  0s |  Used deprecated FindBugs config; considering switching to SpotBugs.  |
| +1 :green_heart: |  findbugs  |   7m 40s |  master passed  |
||| _ Patch Compile Tests _ |
| +0 :ok: |  mvndep  |   1m 30s |  Maven dependency ordering for patch  |
| +1 :green_heart: |  mvninstall  |   4m 56s |  the patch passed  |
| +1 :green_heart: |  compile  |   3m 11s |  the patch passed with JDK Ubuntu-11.0.19+7-post-Ubuntu-0ubuntu122.04.1  |
| +1 :green_heart: |  javac  |   3m 11s |  the patch passed  |
| +1 :green_heart: |  compile  |   2m 56s |  the patch passed with JDK Private Build-1.8.0_362-8u372-ga~us1-0ubuntu1~22.04-b09  |
| +1 :green_heart: |  javac  |   2m 56s |  the patch passed  |
| +1 :green_heart: |  checkstyle  |   1m 31s |  the patch passed  |
| +1 :green_heart: |  whitespace  |   0m  0s |  The patch has no whitespace issues.  |
| +1 :green_heart: |  xml  |   0m  1s |  The patch has no ill-formed XML file.  |
| +1 :green_heart: |  javadoc  |   1m 44s |  the patch passed with JDK Ubuntu-11.0.19+7-post-Ubuntu-0ubuntu122.04.1  |
| +1 :green_heart: |  javadoc  |   1m 39s |  the patch passed with JDK Private Build-1.8.0_362-8u372-ga~us1-0ubuntu1~22.04-b09  |
| +1 :green_heart: |  findbugs  |   7m 31s |  the patch passed  |
||| _ Other Tests _ |
| -1 :x: |  unit  |   5m 35s |  tez-dag in the patch passed.  |
| -1 :x: |  unit  |  16m 34s |  root in the patch failed.  |
| +1 :green_heart: |  asflicense  |   1m  2s |  The patch does not generate ASF License warnings.  |
|  |   |  87m 11s |   |


| Reason | Tests |
|-------:|:------|
| Failed junit tests | tez.dag.app.TestSpeculation |
|   | tez.dag.app.TestSpeculation |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.43 ServerAPI=1.43 base: https://ci-hadoop.apache.org/job/tez-multibranch/job/PR-285/8/artifact/out/Dockerfile |
| GITHUB PR | https://github.com/apache/tez/pull/285 |
| JIRA Issue | TEZ-4493 |
| Optional Tests | dupname asflicense javac javadoc unit xml compile spotbugs findbugs checkstyle |
| uname | Linux 30b720e29384 4.15.0-212-generic #223-Ubuntu SMP Tue May 23 13:09:22 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | personality/tez.sh |
| git revision | master / 7a56e9bd9 |
| Default Java | Private Build-1.8.0_362-8u372-ga~us1-0ubuntu1~22.04-b09 |
| Multi-JDK versions | /usr/lib/jvm/java-11-openjdk-amd64:Ubuntu-11.0.19+7-post-Ubuntu-0ubuntu122.04.1 /usr/lib/jvm/java-8-openjdk-amd64:Private Build-1.8.0_362-8u372-ga~us1-0ubuntu1~22.04-b09 |
| unit | https://ci-hadoop.apache.org/job/tez-multibranch/job/PR-285/8/artifact/out/patch-unit-tez-dag.txt |
| unit | https://ci-hadoop.apache.org/job/tez-multibranch/job/PR-285/8/artifact/out/patch-unit-root.txt |
|  Test Results | https://ci-hadoop.apache.org/job/tez-multibranch/job/PR-285/8/testReport/ |
| Max. process+thread count | 2100 (vs. ulimit of 5500) |
| modules | C: tez-dag . U: . |
| Console output | https://ci-hadoop.apache.org/job/tez-multibranch/job/PR-285/8/console |
| versions | git=2.34.1 maven=3.6.3 findbugs=3.0.1 |
| Powered by | Apache Yetus 0.12.0 https://yetus.apache.org |


This message was automatically generated.

**Review by abstractdog — APPROVED** [review]
+1

**Pull request merged**
